// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: converge/worker/v1/worker.proto

// Package converge.worker.v1 is the PUBLIC worker↔broker work-distribution API —
// the SINGLE cross-language contract every worker SDK (Go, and future TypeScript /
// Java / … bindings) wraps. It is the ONLY tissue that connects a worker in ANY
// language to a broker: an SDK generates these stubs and speaks exactly this
// service. It is deliberately SEPARATE from the internal broker↔broker mesh
// (converge.mesh.v1, generated into internal/meshpb) so the mesh can evolve —
// new frames, new routing RPCs — WITHOUT regenerating or breaking this public
// contract that N language SDKs depend on. The dependency is one-way: the mesh
// proto IMPORTS this one (a forwarded task reuses StageTask/StageComplete/Interest
// byte-for-byte); this proto never references the mesh.
//
// All workers — in-process and remote — are DUMB Connect clients of a BROKER.
// A broker owns a contiguous tile of the work_queue shard space (assigned by
// the same Resharder that tiles workers today, retargeted to the "broker"
// role), runs the FOR UPDATE SKIP LOCKED claim, and STREAMS individual STAGE
// TASKS to connected workers. The worker holds NO shard, NO DB handle, NO
// worker_id: it runs the PURE provider stage (compose / work / rollup / delete /
// operate) and returns its result. The broker is the lease-holder and does ALL
// the DB reads/writes around every stage (the gate read, ApplyComposeResult,
// ListDescendants, AppendOutbox, …) under its own worker_id, so the existing
// fence + at-least-once redelivery are reused unchanged.
//
// Wire discipline: the large opaque fields (spec, status, provider_config — a
// large composer spec can be tens of MB) ride as `bytes` (the stored json.RawMessage, NO
// re-marshal). The structured stage inputs/outputs (desired children, edges,
// configs, the rollup subtree) ride as JSON-encoded `bytes` blobs — the accepted
// cost of remoting every stage. UUIDs ride as their 16 raw bytes.
package workerpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	workerpb "github.com/salesforce/converge/sdk-go/workerpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkerServiceName is the fully-qualified name of the WorkerService service.
	WorkerServiceName = "converge.worker.v1.WorkerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkerServiceWorkStreamProcedure is the fully-qualified name of the WorkerService's WorkStream
	// RPC.
	WorkerServiceWorkStreamProcedure = "/converge.worker.v1.WorkerService/WorkStream"
	// WorkerServiceGetProviderConfigProcedure is the fully-qualified name of the WorkerService's
	// GetProviderConfig RPC.
	WorkerServiceGetProviderConfigProcedure = "/converge.worker.v1.WorkerService/GetProviderConfig"
)

// WorkerServiceClient is a client for the converge.worker.v1.WorkerService service.
type WorkerServiceClient interface {
	// WorkStream is the worker↔broker work channel — a BIDIRECTIONAL stream. A worker
	// opens it ONCE, sends a Subscribe client message advertising the kinds it can
	// execute (and, on a reconnect, its still-live in-flight tasks), and thereafter:
	//   - RECEIVES WorkStreamServerMsgs (a claimed STAGE TASK to run, or a live CONFIG/
	//     BUNDLE update pushed when an operator edits a kind's default), and
	//   - SENDS a StageComplete (a finished stage's result), an Interest (readiness),
	//     or a WorkHeartbeat (per-task liveness) back UP THE SAME STREAM.
	//
	// A StageComplete is fenced on the epoch it carries, so ANY broker can write it —
	// the worker's own broker, a broker it reconnects to after a rollout, or a peer
	// that ran a forwarded task. The completion still rides the stream (not a unary
	// RPC) so it reaches a live broker directly rather than being LB-misrouted to one
	// that would have to relay it; but correctness no longer depends on it landing on
	// the ORIGINAL claimer — the durable (claim_epoch, generation, manifest_version)
	// fence makes the write owner-independent. A worker that reconnects to a different
	// broker redelivers its buffered results there and they land unchanged.
	WorkStream(context.Context) *connect.BidiStreamForClient[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg]
	// GetProviderConfig returns the CURRENT default providerconfig document for
	// each requested kind (the doc named after the kind, or empty if none). The
	// broker serves it live from its ProviderConfigCache, so a dumb worker — which has NO
	// database — primes each kind's default config at startup and refreshes it
	// periodically (the PULL half; the broker also PUSHES changes). The per-resource
	// CUSTOM override still rides in each StageTask; the worker merges
	// default ⊕ override itself (converge.EffectiveConfig).
	GetProviderConfig(context.Context, *connect.Request[workerpb.GetProviderConfigRequest]) (*connect.Response[workerpb.GetProviderConfigResponse], error)
}

// NewWorkerServiceClient constructs a client for the converge.worker.v1.WorkerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workerServiceMethods := workerpb.File_converge_worker_v1_worker_proto.Services().ByName("WorkerService").Methods()
	return &workerServiceClient{
		workStream: connect.NewClient[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg](
			httpClient,
			baseURL+WorkerServiceWorkStreamProcedure,
			connect.WithSchema(workerServiceMethods.ByName("WorkStream")),
			connect.WithClientOptions(opts...),
		),
		getProviderConfig: connect.NewClient[workerpb.GetProviderConfigRequest, workerpb.GetProviderConfigResponse](
			httpClient,
			baseURL+WorkerServiceGetProviderConfigProcedure,
			connect.WithSchema(workerServiceMethods.ByName("GetProviderConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workerServiceClient implements WorkerServiceClient.
type workerServiceClient struct {
	workStream        *connect.Client[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg]
	getProviderConfig *connect.Client[workerpb.GetProviderConfigRequest, workerpb.GetProviderConfigResponse]
}

// WorkStream calls converge.worker.v1.WorkerService.WorkStream.
func (c *workerServiceClient) WorkStream(ctx context.Context) *connect.BidiStreamForClient[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg] {
	return c.workStream.CallBidiStream(ctx)
}

// GetProviderConfig calls converge.worker.v1.WorkerService.GetProviderConfig.
func (c *workerServiceClient) GetProviderConfig(ctx context.Context, req *connect.Request[workerpb.GetProviderConfigRequest]) (*connect.Response[workerpb.GetProviderConfigResponse], error) {
	return c.getProviderConfig.CallUnary(ctx, req)
}

// WorkerServiceHandler is an implementation of the converge.worker.v1.WorkerService service.
type WorkerServiceHandler interface {
	// WorkStream is the worker↔broker work channel — a BIDIRECTIONAL stream. A worker
	// opens it ONCE, sends a Subscribe client message advertising the kinds it can
	// execute (and, on a reconnect, its still-live in-flight tasks), and thereafter:
	//   - RECEIVES WorkStreamServerMsgs (a claimed STAGE TASK to run, or a live CONFIG/
	//     BUNDLE update pushed when an operator edits a kind's default), and
	//   - SENDS a StageComplete (a finished stage's result), an Interest (readiness),
	//     or a WorkHeartbeat (per-task liveness) back UP THE SAME STREAM.
	//
	// A StageComplete is fenced on the epoch it carries, so ANY broker can write it —
	// the worker's own broker, a broker it reconnects to after a rollout, or a peer
	// that ran a forwarded task. The completion still rides the stream (not a unary
	// RPC) so it reaches a live broker directly rather than being LB-misrouted to one
	// that would have to relay it; but correctness no longer depends on it landing on
	// the ORIGINAL claimer — the durable (claim_epoch, generation, manifest_version)
	// fence makes the write owner-independent. A worker that reconnects to a different
	// broker redelivers its buffered results there and they land unchanged.
	WorkStream(context.Context, *connect.BidiStream[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg]) error
	// GetProviderConfig returns the CURRENT default providerconfig document for
	// each requested kind (the doc named after the kind, or empty if none). The
	// broker serves it live from its ProviderConfigCache, so a dumb worker — which has NO
	// database — primes each kind's default config at startup and refreshes it
	// periodically (the PULL half; the broker also PUSHES changes). The per-resource
	// CUSTOM override still rides in each StageTask; the worker merges
	// default ⊕ override itself (converge.EffectiveConfig).
	GetProviderConfig(context.Context, *connect.Request[workerpb.GetProviderConfigRequest]) (*connect.Response[workerpb.GetProviderConfigResponse], error)
}

// NewWorkerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkerServiceHandler(svc WorkerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workerServiceMethods := workerpb.File_converge_worker_v1_worker_proto.Services().ByName("WorkerService").Methods()
	workerServiceWorkStreamHandler := connect.NewBidiStreamHandler(
		WorkerServiceWorkStreamProcedure,
		svc.WorkStream,
		connect.WithSchema(workerServiceMethods.ByName("WorkStream")),
		connect.WithHandlerOptions(opts...),
	)
	workerServiceGetProviderConfigHandler := connect.NewUnaryHandler(
		WorkerServiceGetProviderConfigProcedure,
		svc.GetProviderConfig,
		connect.WithSchema(workerServiceMethods.ByName("GetProviderConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/converge.worker.v1.WorkerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkerServiceWorkStreamProcedure:
			workerServiceWorkStreamHandler.ServeHTTP(w, r)
		case WorkerServiceGetProviderConfigProcedure:
			workerServiceGetProviderConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkerServiceHandler struct{}

func (UnimplementedWorkerServiceHandler) WorkStream(context.Context, *connect.BidiStream[workerpb.WorkStreamClientMsg, workerpb.WorkStreamServerMsg]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("converge.worker.v1.WorkerService.WorkStream is not implemented"))
}

func (UnimplementedWorkerServiceHandler) GetProviderConfig(context.Context, *connect.Request[workerpb.GetProviderConfigRequest]) (*connect.Response[workerpb.GetProviderConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("converge.worker.v1.WorkerService.GetProviderConfig is not implemented"))
}
