// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: converge/worker/v1/worker.proto

// Package converge.worker.v1 is the PUBLIC worker↔broker work-distribution API —
// the SINGLE cross-language contract every worker SDK (Go, and future TypeScript /
// Java / … bindings) wraps. It is the ONLY tissue that connects a worker in ANY
// language to a broker: an SDK generates these stubs and speaks exactly this
// service. It is deliberately SEPARATE from the internal broker↔broker mesh
// (converge.mesh.v1, generated into internal/meshpb) so the mesh can evolve —
// new frames, new routing RPCs — WITHOUT regenerating or breaking this public
// contract that N language SDKs depend on. The dependency is one-way: the mesh
// proto IMPORTS this one (a forwarded task reuses StageTask/StageComplete/Interest
// byte-for-byte); this proto never references the mesh.
//
// All workers — in-process and remote — are DUMB Connect clients of a BROKER.
// A broker owns a contiguous tile of the work_queue shard space (assigned by
// the same Resharder that tiles workers today, retargeted to the "broker"
// role), runs the FOR UPDATE SKIP LOCKED claim, and STREAMS individual STAGE
// TASKS to connected workers. The worker holds NO shard, NO DB handle, NO
// worker_id: it runs the PURE provider stage (compose / work / rollup / delete /
// operate) and returns its result. The broker is the lease-holder and does ALL
// the DB reads/writes around every stage (the gate read, ApplyComposeResult,
// ListDescendants, AppendOutbox, …) under its own worker_id, so the existing
// fence + at-least-once redelivery are reused unchanged.
//
// Wire discipline: the large opaque fields (spec, status, provider_config — a
// large composer spec can be tens of MB) ride as `bytes` (the stored json.RawMessage, NO
// re-marshal). The structured stage inputs/outputs (desired children, edges,
// configs, the rollup subtree) ride as JSON-encoded `bytes` blobs — the accepted
// cost of remoting every stage. UUIDs ride as their 16 raw bytes.

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stage selects WHICH provider stage a StageTask carries. The worker runs the
// matching pure pipeline (RunComposeStages / RunWorkStages / …) and returns the
// matching result in StageComplete.
type Stage int32

const (
	Stage_STAGE_UNSPECIFIED Stage = 0
	Stage_STAGE_COMPOSE     Stage = 1 // RunCompose → desired children/edges/configs
	Stage_STAGE_WORK        Stage = 2 // RunWork → status (the leaf provisioning stage)
	Stage_STAGE_ROLLUP      Stage = 3 // RunRollup → rolled-up status (input: the subtree)
	Stage_STAGE_DELETE      Stage = 4 // RunDelete → ok (finalizer teardown)
	Stage_STAGE_OPERATE     Stage = 5 // RunOperate → verb output
	Stage_STAGE_REACT       Stage = 6 // RunReact → side effect on a lifecycle transition
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_COMPOSE",
		2: "STAGE_WORK",
		3: "STAGE_ROLLUP",
		4: "STAGE_DELETE",
		5: "STAGE_OPERATE",
		6: "STAGE_REACT",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"STAGE_COMPOSE":     1,
		"STAGE_WORK":        2,
		"STAGE_ROLLUP":      3,
		"STAGE_DELETE":      4,
		"STAGE_OPERATE":     5,
		"STAGE_REACT":       6,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_converge_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_converge_worker_v1_worker_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

// Transition is the resource lifecycle edge a reactor delivery fired on — the
// wire form of converge.Transition. It is a CLOSED set (mirrors the DB CHECK on
// reactor_bindings.transition / lifecycle_outbox.transition), so it rides as an
// enum, not a loose string: an out-of-set value can't cross the wire.
type Transition int32

const (
	Transition_TRANSITION_UNSPECIFIED Transition = 0
	Transition_TRANSITION_CREATED     Transition = 1
	Transition_TRANSITION_SYNCED      Transition = 2
	Transition_TRANSITION_DEGRADED    Transition = 3
	Transition_TRANSITION_FAILED      Transition = 4
	Transition_TRANSITION_DELETED     Transition = 5
)

// Enum value maps for Transition.
var (
	Transition_name = map[int32]string{
		0: "TRANSITION_UNSPECIFIED",
		1: "TRANSITION_CREATED",
		2: "TRANSITION_SYNCED",
		3: "TRANSITION_DEGRADED",
		4: "TRANSITION_FAILED",
		5: "TRANSITION_DELETED",
	}
	Transition_value = map[string]int32{
		"TRANSITION_UNSPECIFIED": 0,
		"TRANSITION_CREATED":     1,
		"TRANSITION_SYNCED":      2,
		"TRANSITION_DEGRADED":    3,
		"TRANSITION_FAILED":      4,
		"TRANSITION_DELETED":     5,
	}
)

func (x Transition) Enum() *Transition {
	p := new(Transition)
	*p = x
	return p
}

func (x Transition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transition) Descriptor() protoreflect.EnumDescriptor {
	return file_converge_worker_v1_worker_proto_enumTypes[1].Descriptor()
}

func (Transition) Type() protoreflect.EnumType {
	return &file_converge_worker_v1_worker_proto_enumTypes[1]
}

func (x Transition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transition.Descriptor instead.
func (Transition) EnumDescriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

// WorkStreamClientMsg is one message a WORKER sends UP the WorkStream. The FIRST
// message MUST be a Subscribe (it advertises the kinds + concurrency, opening the
// session, and on a RECONNECT re-advertises the worker's still-live in-flight tasks
// so the new broker adopts their liveness). Subsequent messages are a StageComplete
// (a finished stage's result), an Interest (a per-kind readiness flip), or a
// WorkHeartbeat (per-task liveness attestation). Carrying the completion on the
// stream — not a separate unary RPC — pins it to a broker that can fence it (immune
// to LB misrouting; see WorkStream).
//
// LIVENESS is worker-ATTESTED, not inferred from the connection: the stream being
// open proves the PROCESS is alive, but NOT that a given task's handler is making
// progress (it can wedge on a live TCP connection). The worker periodically sends a
// WorkHeartbeat listing exactly the tasks whose handlers are progressing; the broker
// refreshes work_queue.heartbeat_at only for those, so a silent or hung task falls
// out of the attested set and the reaper reclaims it. Interest is the separate axis
// for per-kind readiness ("stop sending me THIS (kind, kind_version)'s work" without
// dropping the stream; see Interest, has_worker=false = RS-).
type WorkStreamClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WorkStreamClientMsg_Subscribe
	//	*WorkStreamClientMsg_Complete
	//	*WorkStreamClientMsg_Interest
	//	*WorkStreamClientMsg_Heartbeat
	Body          isWorkStreamClientMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkStreamClientMsg) Reset() {
	*x = WorkStreamClientMsg{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkStreamClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkStreamClientMsg) ProtoMessage() {}

func (x *WorkStreamClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkStreamClientMsg.ProtoReflect.Descriptor instead.
func (*WorkStreamClientMsg) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkStreamClientMsg) GetBody() isWorkStreamClientMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WorkStreamClientMsg) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamClientMsg_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *WorkStreamClientMsg) GetComplete() *StageComplete {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamClientMsg_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *WorkStreamClientMsg) GetInterest() *Interest {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamClientMsg_Interest); ok {
			return x.Interest
		}
	}
	return nil
}

func (x *WorkStreamClientMsg) GetHeartbeat() *WorkHeartbeat {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamClientMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isWorkStreamClientMsg_Body interface {
	isWorkStreamClientMsg_Body()
}

type WorkStreamClientMsg_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"` // FIRST message: open the session (kinds + max_inflight + resumed tasks)
}

type WorkStreamClientMsg_Complete struct {
	Complete *StageComplete `protobuf:"bytes,2,opt,name=complete,proto3,oneof"` // a finished stage's result → resolves the lease
}

type WorkStreamClientMsg_Interest struct {
	Interest *Interest `protobuf:"bytes,3,opt,name=interest,proto3,oneof"` // per-kind readiness flip (has_worker: RS+/RS-); see Interest
}

type WorkStreamClientMsg_Heartbeat struct {
	Heartbeat *WorkHeartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"` // per-task liveness attestation (progressing lease_tokens)
}

func (*WorkStreamClientMsg_Subscribe) isWorkStreamClientMsg_Body() {}

func (*WorkStreamClientMsg_Complete) isWorkStreamClientMsg_Body() {}

func (*WorkStreamClientMsg_Interest) isWorkStreamClientMsg_Body() {}

func (*WorkStreamClientMsg_Heartbeat) isWorkStreamClientMsg_Body() {}

// Subscribe is the opening message of a WorkStream: it advertises what the worker
// can run and its concurrency, so the broker marks it a live consumer and sizes
// its per-kind fanout buffer headroom.
type Subscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A worker does not report its own identity: the broker derives the connected
	// client's identity from the connection it OBSERVES (the mTLS client cert's SPIFFE
	// ID, a trusted service-mesh header, or the peer IP) for the connected-worker
	// cluster view + the "running on <worker>" attribution.
	//
	// kinds this worker can execute (the (kind, version) pairs of its registered providers).
	Kinds []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// worker's local concurrency ceiling; sizes per-kind buffer headroom.
	MaxInflight uint32 `protobuf:"varint,2,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	// kind_versions is the PARALLEL per-kind web-API version array: kinds[i] is served
	// at kind_version kind_versions[i] (v1, v2 — integers, no minor/micro). A worker serving
	// vpc/v1 AND vpc/v2 sends kinds=["vpc","vpc"], kind_versions=[1,2]. Routing is
	// STRICT exact (kind, kind_version): a worker serves ONLY the exact kind versions it lists —
	// there is no "any"/wildcard kind_version. A SHORTER kind_versions than kinds defaults its
	// missing entries to kind_version 1 (v1).
	KindVersions []int32 `protobuf:"varint,3,rep,packed,name=kind_versions,json=kindVersions,proto3" json:"kind_versions,omitempty"`
	// resumed carries the worker's STILL-LIVE in-flight tasks on a RECONNECT: the
	// (lease_token, claim_epoch) of every task whose handler is still running or whose
	// computed result is buffered for redelivery. The broker the worker lands on adopts
	// their liveness immediately — it starts refreshing work_queue.heartbeat_at for these
	// epochs (fenced), so a task that migrated from a dead broker to this one stays fresh
	// and is not reaped out from under the live worker. Empty on a first connect.
	Resumed       []*ResumedTask `protobuf:"bytes,4,rep,name=resumed,proto3" json:"resumed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribe) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Subscribe) GetMaxInflight() uint32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *Subscribe) GetKindVersions() []int32 {
	if x != nil {
		return x.KindVersions
	}
	return nil
}

func (x *Subscribe) GetResumed() []*ResumedTask {
	if x != nil {
		return x.Resumed
	}
	return nil
}

// ResumedTask identifies one in-flight task a reconnecting worker is still executing
// (or holding a buffered result for), by the same (lease_token, claim_epoch) the
// StageTask carried. The broker adopts its liveness (epoch-fenced heartbeat) so the
// migrated task isn't reaped while the worker finishes and redelivers its result.
type ResumedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseToken    string                 `protobuf:"bytes,1,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	ClaimEpoch    int64                  `protobuf:"varint,2,opt,name=claim_epoch,json=claimEpoch,proto3" json:"claim_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumedTask) Reset() {
	*x = ResumedTask{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumedTask) ProtoMessage() {}

func (x *ResumedTask) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumedTask.ProtoReflect.Descriptor instead.
func (*ResumedTask) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ResumedTask) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ResumedTask) GetClaimEpoch() int64 {
	if x != nil {
		return x.ClaimEpoch
	}
	return 0
}

// WorkStreamServerMsg is one message the BROKER sends DOWN the WorkStream: a stage
// task to run, or a live providerconfig update (spec + bundle together). Exactly one
// field set. There is no down-direction keepalive: liveness is worker-ATTESTED (the
// worker sends WorkHeartbeat frames UP), so a dead/silent worker is detected by the
// ABSENCE of attestation (the reaper reclaims its unrefreshed leases), and a dead
// broker is detected by the worker's own reconnect loop.
type WorkStreamServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WorkStreamServerMsg_Task
	//	*WorkStreamServerMsg_Config
	Body          isWorkStreamServerMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkStreamServerMsg) Reset() {
	*x = WorkStreamServerMsg{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkStreamServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkStreamServerMsg) ProtoMessage() {}

func (x *WorkStreamServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkStreamServerMsg.ProtoReflect.Descriptor instead.
func (*WorkStreamServerMsg) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkStreamServerMsg) GetBody() isWorkStreamServerMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WorkStreamServerMsg) GetTask() *StageTask {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamServerMsg_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *WorkStreamServerMsg) GetConfig() *ProviderConfigUpdate {
	if x != nil {
		if x, ok := x.Body.(*WorkStreamServerMsg_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isWorkStreamServerMsg_Body interface {
	isWorkStreamServerMsg_Body()
}

type WorkStreamServerMsg_Task struct {
	Task *StageTask `protobuf:"bytes,1,opt,name=task,proto3,oneof"` // a claimed pure stage to run → reply with a StageComplete
}

type WorkStreamServerMsg_Config struct {
	Config *ProviderConfigUpdate `protobuf:"bytes,2,opt,name=config,proto3,oneof"` // a kind's new default providerconfig (spec + bundle), pushed whole
}

func (*WorkStreamServerMsg_Task) isWorkStreamServerMsg_Body() {}

func (*WorkStreamServerMsg_Config) isWorkStreamServerMsg_Body() {}

// WorkHeartbeat is the worker's per-task liveness attestation. The worker sends ONE
// coalesced frame per tick (not one per task) listing the lease_tokens of the tasks
// whose handlers are actively PROGRESSING — a token drops out the instant its handler
// stops making progress (a wedged handler stops attesting even though its goroutine is
// alive), which is what makes this attest execution, not mere process/TCP liveness.
// The broker refreshes work_queue.heartbeat_at only for these tokens (fenced on the
// echoed claim_epoch), so a silent or hung task is not kept fresh and the reaper
// reclaims it within one liveness window. The two arrays are positional (lease_token[i]
// ↔ claim_epoch[i]); an empty frame (no progressing tasks) is valid and refreshes
// nothing.
type WorkHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseToken    []string               `protobuf:"bytes,1,rep,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	ClaimEpoch    []int64                `protobuf:"varint,2,rep,packed,name=claim_epoch,json=claimEpoch,proto3" json:"claim_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkHeartbeat) Reset() {
	*x = WorkHeartbeat{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkHeartbeat) ProtoMessage() {}

func (x *WorkHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkHeartbeat) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkHeartbeat) GetLeaseToken() []string {
	if x != nil {
		return x.LeaseToken
	}
	return nil
}

func (x *WorkHeartbeat) GetClaimEpoch() []int64 {
	if x != nil {
		return x.ClaimEpoch
	}
	return nil
}

// ProviderConfigUpdate pushes a kind's CURRENT default providerconfig — the WHOLE
// thing, spec + bundle together — to a connected worker the instant an operator edits
// it (the broker's ProviderConfigCache observes providerconfig_changed and broadcasts to every
// WorkStream advertising that kind). A providerconfig is a MONOLITH of {config spec,
// opaque data/bundle}; this push carries both, mirroring the pull's ProviderConfigEntry,
// so the two axes are never observed torn or out of order. The worker applies it into
// its live ConfigCache, so the next task observes the new config without waiting for the
// periodic GetProviderConfig poll. Both fields empty = the default was deleted (worker
// clears it); a present-but-empty half means that half is absent (a config with no
// bundle sends config, leaves bundle empty).
type ProviderConfigUpdate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Kind        string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	KindVersion int32                  `protobuf:"varint,2,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"` // web-API version this default is for (v1, v2); unset = 1. A push
	// targets ONLY workers serving that exact (kind, kind_version) — a v2
	// edit never lands in a v1 worker's cache — and the worker routes it
	// into its (kind, kind_version) cache slot by this field.
	Config        []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // json.RawMessage config document (spec); empty = absent/deleted
	Bundle        []byte `protobuf:"bytes,4,opt,name=bundle,proto3" json:"bundle,omitempty"` // providerconfigs.data bundle; empty = absent/deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfigUpdate) Reset() {
	*x = ProviderConfigUpdate{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfigUpdate) ProtoMessage() {}

func (x *ProviderConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfigUpdate.ProtoReflect.Descriptor instead.
func (*ProviderConfigUpdate) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderConfigUpdate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderConfigUpdate) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

func (x *ProviderConfigUpdate) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProviderConfigUpdate) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

// StageTask is one pure provider stage to run. It is a SELF-CONTAINED work
// reference: it carries everything the broker needs to fence the result WITHOUT
// re-reading the lease from its own memory, so ANY broker can accept the resulting
// Complete — the worker's own broker, a broker it reconnects to after a rollout, or
// a peer that ran a forwarded task. The fence is (claim_epoch, generation,
// manifest_version); lease_token is the unguessable per-claim handle re-verified
// against the durable row (anti-spray).
//
// The per-stage INPUT is a TYPED proto envelope (not a JSON blob): the structural
// collections (the rollup subtree, compose children/edges/configs) are real proto
// messages so the wire never JSON-marshals thousands of objects. Only the OPAQUE
// provider JSON (a Resource's spec/status, a ChildSpec's spec) stays `bytes` — it
// is arbitrary user JSON with no fixed schema. Exactly one of the *_req fields is
// set, matching `stage`.
type StageTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Identity + routing ──
	Stage       Stage  `protobuf:"varint,1,opt,name=stage,proto3,enum=converge.worker.v1.Stage" json:"stage,omitempty"`
	Kind        string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	KindVersion int32  `protobuf:"varint,3,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"` // the web-API version (v1, v2) this task was claimed for
	// (work_queue.kind_version; unset = 1). STRICT (kind, kind_version)
	// routing rides this: the broker only hands a task to a
	// worker/peer advertising the EXACT (kind, kind_version). The
	// dumb worker doesn't strictly need it (its handler is
	// (kind, reaction)-keyed), but the broker carries it for
	// routing + zero-worker-for-kind_version observability.
	ResourceId []byte `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // uuid (16 raw bytes), for logging/identity
	Generation int64  `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Reaction   string `protobuf:"bytes,6,opt,name=reaction,proto3" json:"reaction,omitempty"` // the reaction NAME (ReactionDecl.Name) the broker selected
	// ── Fence (self-contained, so ANY broker can write the Complete) ──
	LeaseToken string `protobuf:"bytes,7,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"` // unguessable per-claim handle; echoed on Complete and
	// re-verified against the durable row (anti-spray guard)
	ClaimEpoch int64 `protobuf:"varint,8,opt,name=claim_epoch,json=claimEpoch,proto3" json:"claim_epoch,omitempty"` // the strict monotonic fencing token stamped on this claim
	// (work_queue.claim_epoch). The worker echoes it on Complete;
	// the result write lands only if the row still bears this
	// exact epoch, so a stale/zombie/misrouted result (older
	// epoch) no-ops. Owner-independent: any broker holding this
	// token writes the fenced result.
	ManifestVersion int64 `protobuf:"varint,9,opt,name=manifest_version,json=manifestVersion,proto3" json:"manifest_version,omitempty"` // the kind_manifest content hash this task was enqueued
	// ── Per-task Env inputs + deadline ──
	ProviderConfig []byte `protobuf:"bytes,10,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"` // json.RawMessage — the per-task Env.ProviderConfig
	ProviderBundle []byte `protobuf:"bytes,11,opt,name=provider_bundle,json=providerBundle,proto3" json:"provider_bundle,omitempty"` // the per-task Env.ProviderBundle — the CUSTOM bundle
	// override (opaque artifact bytes); empty = use kind default.
	TaskDeadlineMs int64 `protobuf:"varint,12,opt,name=task_deadline_ms,json=taskDeadlineMs,proto3" json:"task_deadline_ms,omitempty"` // kind_config.task_deadline_secs as millis; 0 = none
	// ── Typed per-stage request (exactly one set, matching `stage`) ──
	ComposeReq    *ComposeRequest `protobuf:"bytes,13,opt,name=compose_req,json=composeReq,proto3" json:"compose_req,omitempty"`
	WorkReq       *WorkRequest    `protobuf:"bytes,14,opt,name=work_req,json=workReq,proto3" json:"work_req,omitempty"`
	RollupReq     *RollupRequest  `protobuf:"bytes,15,opt,name=rollup_req,json=rollupReq,proto3" json:"rollup_req,omitempty"`
	DeleteReq     *DeleteRequest  `protobuf:"bytes,16,opt,name=delete_req,json=deleteReq,proto3" json:"delete_req,omitempty"`
	OperateReq    *OperateRequest `protobuf:"bytes,17,opt,name=operate_req,json=operateReq,proto3" json:"operate_req,omitempty"`
	ReactReq      *ReactRequest   `protobuf:"bytes,18,opt,name=react_req,json=reactReq,proto3" json:"react_req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageTask) Reset() {
	*x = StageTask{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageTask) ProtoMessage() {}

func (x *StageTask) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageTask.ProtoReflect.Descriptor instead.
func (*StageTask) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StageTask) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *StageTask) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StageTask) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

func (x *StageTask) GetResourceId() []byte {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *StageTask) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *StageTask) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *StageTask) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *StageTask) GetClaimEpoch() int64 {
	if x != nil {
		return x.ClaimEpoch
	}
	return 0
}

func (x *StageTask) GetManifestVersion() int64 {
	if x != nil {
		return x.ManifestVersion
	}
	return 0
}

func (x *StageTask) GetProviderConfig() []byte {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *StageTask) GetProviderBundle() []byte {
	if x != nil {
		return x.ProviderBundle
	}
	return nil
}

func (x *StageTask) GetTaskDeadlineMs() int64 {
	if x != nil {
		return x.TaskDeadlineMs
	}
	return 0
}

func (x *StageTask) GetComposeReq() *ComposeRequest {
	if x != nil {
		return x.ComposeReq
	}
	return nil
}

func (x *StageTask) GetWorkReq() *WorkRequest {
	if x != nil {
		return x.WorkReq
	}
	return nil
}

func (x *StageTask) GetRollupReq() *RollupRequest {
	if x != nil {
		return x.RollupReq
	}
	return nil
}

func (x *StageTask) GetDeleteReq() *DeleteRequest {
	if x != nil {
		return x.DeleteReq
	}
	return nil
}

func (x *StageTask) GetOperateReq() *OperateRequest {
	if x != nil {
		return x.OperateReq
	}
	return nil
}

func (x *StageTask) GetReactReq() *ReactRequest {
	if x != nil {
		return x.ReactReq
	}
	return nil
}

// Resource mirrors converge.Resource. spec/status are opaque JSON (bytes); the
// optional pointer/time fields use the proto3 presence (optional) where the Go
// type is a pointer, and millis-since-epoch (0 = nil) for timestamps.
type Resource struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Kind                  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId               []byte                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // uuid; empty = nil
	RootId                []byte                 `protobuf:"bytes,5,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`    // uuid; empty = nil
	Spec                  []byte                 `protobuf:"bytes,6,opt,name=spec,proto3" json:"spec,omitempty"`                      // json.RawMessage (opaque)
	Status                []byte                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                  // json.RawMessage (opaque)
	Generation            int64                  `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	SyncedGen             int64                  `protobuf:"varint,9,opt,name=synced_gen,json=syncedGen,proto3" json:"synced_gen,omitempty"`
	IsReady               bool                   `protobuf:"varint,10,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	Finalizers            []string               `protobuf:"bytes,11,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	DeletionRequestedAtMs int64                  `protobuf:"varint,12,opt,name=deletion_requested_at_ms,json=deletionRequestedAtMs,proto3" json:"deletion_requested_at_ms,omitempty"` // 0 = nil
	FrozenUntilMs         int64                  `protobuf:"varint,13,opt,name=frozen_until_ms,json=frozenUntilMs,proto3" json:"frozen_until_ms,omitempty"`                           // 0 = nil
	Quarantined           bool                   `protobuf:"varint,14,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	Labels                map[string]string      `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Resource) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *Resource) GetRootId() []byte {
	if x != nil {
		return x.RootId
	}
	return nil
}

func (x *Resource) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Resource) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Resource) GetSyncedGen() int64 {
	if x != nil {
		return x.SyncedGen
	}
	return 0
}

func (x *Resource) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Resource) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *Resource) GetDeletionRequestedAtMs() int64 {
	if x != nil {
		return x.DeletionRequestedAtMs
	}
	return 0
}

func (x *Resource) GetFrozenUntilMs() int64 {
	if x != nil {
		return x.FrozenUntilMs
	}
	return 0
}

func (x *Resource) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

func (x *Resource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ResourceRef mirrors model.ResourceRef.
type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ValueFlow mirrors converge.ValueFlow.
type ValueFlow struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DependentField string                 `protobuf:"bytes,1,opt,name=dependent_field,json=dependentField,proto3" json:"dependent_field,omitempty"`
	SourceField    string                 `protobuf:"bytes,2,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValueFlow) Reset() {
	*x = ValueFlow{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueFlow) ProtoMessage() {}

func (x *ValueFlow) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueFlow.ProtoReflect.Descriptor instead.
func (*ValueFlow) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ValueFlow) GetDependentField() string {
	if x != nil {
		return x.DependentField
	}
	return ""
}

func (x *ValueFlow) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

// ChildSpec mirrors converge.ChildSpec. Spec is opaque (`any` in Go → bytes).
type ChildSpec struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec   []byte                 `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"` // JSON-encoded `any` (opaque)
	Labels map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// kind_version is the child's web-API version (v1, v2, …). REQUIRED and explicit
	// (>= 1) — a composer stamps it on every child; ApplyComposeResult rejects a 0. It
	// MUST ride the wire, else a composer's explicit version would be lost over the
	// Connect stagewire round-trip and arrive as a rejected 0.
	KindVersion   int32 `protobuf:"varint,5,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildSpec) Reset() {
	*x = ChildSpec{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildSpec) ProtoMessage() {}

func (x *ChildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildSpec.ProtoReflect.Descriptor instead.
func (*ChildSpec) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ChildSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChildSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChildSpec) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ChildSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ChildSpec) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

// DepEdge mirrors converge.DepEdge.
type DepEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *ResourceRef           `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // dependent
	To            *ResourceRef           `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // dependency
	Values        []*ValueFlow           `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepEdge) Reset() {
	*x = DepEdge{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepEdge) ProtoMessage() {}

func (x *DepEdge) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepEdge.ProtoReflect.Descriptor instead.
func (*DepEdge) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *DepEdge) GetFrom() *ResourceRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DepEdge) GetTo() *ResourceRef {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DepEdge) GetValues() []*ValueFlow {
	if x != nil {
		return x.Values
	}
	return nil
}

// ProviderConfigSpec mirrors converge.ProviderConfigSpec.
type ProviderConfigSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind      string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	IsDefault bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Spec      []byte                 `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"` // JSON-encoded `any` (opaque)
	// kind_version is the consumer kind's web-API version (v1, v2, …) this config is
	// for. REQUIRED and explicit (>= 1) — must ride the wire so a composer-emitted
	// config's version survives the Connect stagewire round-trip.
	KindVersion   int32 `protobuf:"varint,5,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfigSpec) Reset() {
	*x = ProviderConfigSpec{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfigSpec) ProtoMessage() {}

func (x *ProviderConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfigSpec.ProtoReflect.Descriptor instead.
func (*ProviderConfigSpec) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ProviderConfigSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderConfigSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderConfigSpec) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ProviderConfigSpec) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ProviderConfigSpec) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

// Operation mirrors converge.Operation. The resource is addressed by its public
// uuid (resource_id) + verb only — no internal DB row id reaches the worker.
type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    []byte                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // resource uuid (public transport identity)
	Verb          string                 `protobuf:"bytes,2,opt,name=verb,proto3" json:"verb,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // json.RawMessage (opaque)
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *Operation) GetResourceId() []byte {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *Operation) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *Operation) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Operation) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Operation) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ComposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Resource              `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Observed      []*Resource            `protobuf:"bytes,2,rep,name=observed,proto3" json:"observed,omitempty"`
	Desired       []*ChildSpec           `protobuf:"bytes,3,rep,name=desired,proto3" json:"desired,omitempty"`
	Edges         []*DepEdge             `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	Configs       []*ProviderConfigSpec  `protobuf:"bytes,5,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeRequest) Reset() {
	*x = ComposeRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeRequest) ProtoMessage() {}

func (x *ComposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeRequest.ProtoReflect.Descriptor instead.
func (*ComposeRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{14}
}

func (x *ComposeRequest) GetRoot() *Resource {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ComposeRequest) GetObserved() []*Resource {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *ComposeRequest) GetDesired() []*ChildSpec {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *ComposeRequest) GetEdges() []*DepEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ComposeRequest) GetConfigs() []*ProviderConfigSpec {
	if x != nil {
		return x.Configs
	}
	return nil
}

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Status        []byte                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // accumulated status (opaque)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{15}
}

func (x *WorkRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *WorkRequest) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type RollupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Resource              `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Descendants   []*Resource            `protobuf:"bytes,2,rep,name=descendants,proto3" json:"descendants,omitempty"` // the WHOLE subtree (typed, not JSON)
	Status        []byte                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`           // opaque
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollupRequest) Reset() {
	*x = RollupRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollupRequest) ProtoMessage() {}

func (x *RollupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollupRequest.ProtoReflect.Descriptor instead.
func (*RollupRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{16}
}

func (x *RollupRequest) GetRoot() *Resource {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *RollupRequest) GetDescendants() []*Resource {
	if x != nil {
		return x.Descendants
	}
	return nil
}

func (x *RollupRequest) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type OperateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateRequest) Reset() {
	*x = OperateRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRequest) ProtoMessage() {}

func (x *OperateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRequest.ProtoReflect.Descriptor instead.
func (*OperateRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{18}
}

func (x *OperateRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *OperateRequest) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// ReactRequest is one lifecycle-reactor invocation: a resource that just crossed
// `transition` (created|synced|degraded|failed|deleted), to run the kind's
// lifecycle reaction (a side effect — upload status, POST a hook, chain the next
// resource). It is the WORK stage's analogue for the lifecycle trigger: the
// result rides back as StageComplete.status + conditions. The reactor's sink
// config (the matched binding's providerconfig) rides as the StageTask's
// provider_config, identical to every other stage's Env.ProviderConfig.
//
// dedup_token is the stable (resource, transition, generation, binding) key the
// broker computes; the worker passes it to the handler so an idempotent reactor
// (keyed on it) makes the at-least-once redelivery a harmless no-op.
type ReactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Transition    Transition             `protobuf:"varint,2,opt,name=transition,proto3,enum=converge.worker.v1.Transition" json:"transition,omitempty"` // closed enum
	DedupToken    string                 `protobuf:"bytes,3,opt,name=dedup_token,json=dedupToken,proto3" json:"dedup_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactRequest) Reset() {
	*x = ReactRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactRequest) ProtoMessage() {}

func (x *ReactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactRequest.ProtoReflect.Descriptor instead.
func (*ReactRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{19}
}

func (x *ReactRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ReactRequest) GetTransition() Transition {
	if x != nil {
		return x.Transition
	}
	return Transition_TRANSITION_UNSPECIFIED
}

func (x *ReactRequest) GetDedupToken() string {
	if x != nil {
		return x.DedupToken
	}
	return ""
}

// Condition is the wire form of converge.Condition — one health/status axis a
// stage reported. Sent RAW (unfolded); the broker folds them into health_ok +
// the conditions JSONB, because folding depends on broker-side `advance` state.
type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // "Ready" | "Synced" | custom axis
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "True" | "False" | "Unknown"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{20}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StageComplete is the worker's result for one stage. On success the result
// fields are set per `stage` (see below); on failure error_message is non-empty
// (failed_stage labels which pipeline stage, terminal mirrors
// converge.Terminal()). The broker maps this back to the matching
// core result type (model.ComposePipelineResult / model.Outcome) and resumes the parked loop.
//
//	COMPOSE → compose (typed: desired/edges/configs/status/conditions)
//	WORK    → status + conditions
//	ROLLUP  → status + conditions
//	DELETE  → (no data; success = no error)
//	OPERATE → output
//	REACT   → status + conditions (side effect; the broker acks the outbox)
type StageComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseToken    string                 `protobuf:"bytes,1,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Stage         Stage                  `protobuf:"varint,2,opt,name=stage,proto3,enum=converge.worker.v1.Stage" json:"stage,omitempty"`
	Status        []byte                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`         // WORK/ROLLUP: final json.RawMessage status
	Conditions    []*Condition           `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"` // WORK/ROLLUP: raw, unfolded
	Compose       *ComposeResult         `protobuf:"bytes,5,opt,name=compose,proto3" json:"compose,omitempty"`       // COMPOSE: typed result
	Output        []byte                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`         // OPERATE: verb output json.RawMessage
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FailedStage   int32                  `protobuf:"varint,8,opt,name=failed_stage,json=failedStage,proto3" json:"failed_stage,omitempty"`
	Terminal      bool                   `protobuf:"varint,9,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ClaimEpoch    int64                  `protobuf:"varint,10,opt,name=claim_epoch,json=claimEpoch,proto3" json:"claim_epoch,omitempty"` // the epoch echoed from StageTask; the broker fences the
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageComplete) Reset() {
	*x = StageComplete{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageComplete) ProtoMessage() {}

func (x *StageComplete) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageComplete.ProtoReflect.Descriptor instead.
func (*StageComplete) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{21}
}

func (x *StageComplete) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *StageComplete) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *StageComplete) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StageComplete) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *StageComplete) GetCompose() *ComposeResult {
	if x != nil {
		return x.Compose
	}
	return nil
}

func (x *StageComplete) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *StageComplete) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StageComplete) GetFailedStage() int32 {
	if x != nil {
		return x.FailedStage
	}
	return 0
}

func (x *StageComplete) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *StageComplete) GetClaimEpoch() int64 {
	if x != nil {
		return x.ClaimEpoch
	}
	return 0
}

// ComposeResult is the typed COMPOSE output (mirrors converge.ComposePipelineResult
// minus the error, which travels in StageComplete.error_message).
type ComposeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desired       []*ChildSpec           `protobuf:"bytes,1,rep,name=desired,proto3" json:"desired,omitempty"`
	Edges         []*DepEdge             `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Configs       []*ProviderConfigSpec  `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	Status        []byte                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // opaque
	Conditions    []*Condition           `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeResult) Reset() {
	*x = ComposeResult{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeResult) ProtoMessage() {}

func (x *ComposeResult) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeResult.ProtoReflect.Descriptor instead.
func (*ComposeResult) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{22}
}

func (x *ComposeResult) GetDesired() []*ChildSpec {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *ComposeResult) GetEdges() []*DepEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ComposeResult) GetConfigs() []*ProviderConfigSpec {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ComposeResult) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ComposeResult) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// Interest is the NATS RS+/RS- analogue, sent on TWO streams for the SAME purpose —
// "here is who has a live, healthy worker for (kind, kind_version)":
//
//   - On the worker→broker WorkStream (WorkStreamClientMsg.interest): a worker flips
//     its own per-kind READINESS. credit is UNUSED here (0) — a worker advertises
//     PRESENCE, not slots (its slot budget is Subscribe.max_inflight, and the broker
//     never trusts a worker's self-reported credit for routing). has_worker=false =
//     RS- = "this provider is degraded, stop sending me (kind, kind_version) work";
//     has_worker=true = RS+ = "recovered, resume".
//   - On the broker↔broker mesh Route stream (converge.mesh.v1.RouteFrame.interest,
//     which imports THIS message): a broker advertises its CURRENT remaining worker
//     CREDIT for (kind, kind_version) to peers. credit = Σ over the broker's local
//     READY worker streams of (max_inflight − local_inflight), floored at 0.
//     has_worker = "any READY local worker for this pair". The broker maps a worker
//     RS- to a ready-subscriber decrement, which both closes its local claim gate for
//     the pair and, via the mesh advertisement, retracts the mesh Interest so peers
//     stop forwarding that pair here too.
//
// It is DEFINED here (with the worker contract) because a worker sends it on the
// WorkStream; the mesh reuses it by import. credit==0 with has_worker=false is RS-
// (stop claiming); has_worker=true is RS+. The value is ABSOLUTE (not a delta) so a
// dropped/reordered frame self-heals on the sender's next edge (idempotent); (kind,
// kind_version) cardinality is tiny so the absolute cost is negligible. Sent eagerly
// on every edge (worker connect/drop, task dispatched/completed, a worker readiness
// flip), COALESCED per (stream, kind, kind_version).
type Interest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Credit int32                  `protobuf:"varint,2,opt,name=credit,proto3" json:"credit,omitempty"` // Route: absolute remaining FREE slots for (kind, kind_version) now (0 = full).
	// WorkStream: UNUSED (0) — a worker advertises presence, not credit.
	HasWorker bool `protobuf:"varint,3,opt,name=has_worker,json=hasWorker,proto3" json:"has_worker,omitempty"` // RS+/RS-: Route = "any READY local worker for (kind, kind_version)?";
	// WorkStream = this worker's READINESS for (kind, kind_version).
	// Presence, distinct from credit: has_worker=true, credit=0 means
	// "a worker exists but is momentarily full" — peers still claim
	// their tile (the gate keys on presence) and buffer-push to it;
	// has_worker=false is the true RS- (no ready worker → stop claiming).
	KindVersion   int32 `protobuf:"varint,4,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"` // the web-API version (v1, v2) this interest is for; unset = 1. STRICT:
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interest) Reset() {
	*x = Interest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interest) ProtoMessage() {}

func (x *Interest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interest.ProtoReflect.Descriptor instead.
func (*Interest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{23}
}

func (x *Interest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Interest) GetCredit() int32 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *Interest) GetHasWorker() bool {
	if x != nil {
		return x.HasWorker
	}
	return false
}

func (x *Interest) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

type GetProviderConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kinds []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"` // kinds whose default config the worker wants
	// kind_versions is the PARALLEL per-kind web-API version array (mirrors Subscribe):
	// kinds[i]'s default is wanted at kind_version kind_versions[i]. Defaults are per
	// (kind, kind_version), so a worker serving vpc/v1 AND vpc/v2 asks kinds=["vpc","vpc"],
	// kind_versions=[1,2] and gets each kind_version's OWN default. A SHORTER kind_versions
	// defaults its missing entries to kind_version 1 (v1).
	KindVersions  []int32 `protobuf:"varint,2,rep,packed,name=kind_versions,json=kindVersions,proto3" json:"kind_versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderConfigRequest) Reset() {
	*x = GetProviderConfigRequest{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfigRequest) ProtoMessage() {}

func (x *GetProviderConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfigRequest.ProtoReflect.Descriptor instead.
func (*GetProviderConfigRequest) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{24}
}

func (x *GetProviderConfigRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *GetProviderConfigRequest) GetKindVersions() []int32 {
	if x != nil {
		return x.KindVersions
	}
	return nil
}

type GetProviderConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries carries one (kind, kind_version)'s current default config + bundle. Keyed by
	// (kind, kind_version), NOT kind — defaults are per-kind_version, so a worker asking for both
	// vpc/v1 and vpc/v2 gets two entries with distinct docs. A (kind, kind_version) with no
	// default config AND no bundle is omitted (the worker treats it as nil for that
	// pair). Repeated messages (not two parallel maps keyed by kind) so the (kind,
	// kind_version) key rides cleanly — a proto map can't key on a composite.
	Entries       []*ProviderConfigEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderConfigResponse) Reset() {
	*x = GetProviderConfigResponse{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfigResponse) ProtoMessage() {}

func (x *GetProviderConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfigResponse.ProtoReflect.Descriptor instead.
func (*GetProviderConfigResponse) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{25}
}

func (x *GetProviderConfigResponse) GetEntries() []*ProviderConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ProviderConfigEntry is one (kind, kind_version)'s DEFAULT providerconfig as served by
// GetProviderConfig: the config document (spec) and the opaque bundle (data). A
// present-but-empty field means that half is absent for the pair (e.g. a config
// with no bundle sends config, leaves bundle empty).
type ProviderConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	KindVersion   int32                  `protobuf:"varint,2,opt,name=kind_version,json=kindVersion,proto3" json:"kind_version,omitempty"` // web-API kind_version (v1, v2); unset = 1
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`                               // json.RawMessage default config document; empty = none
	Bundle        []byte                 `protobuf:"bytes,4,opt,name=bundle,proto3" json:"bundle,omitempty"`                               // providerconfigs.data default bundle; empty = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfigEntry) Reset() {
	*x = ProviderConfigEntry{}
	mi := &file_converge_worker_v1_worker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfigEntry) ProtoMessage() {}

func (x *ProviderConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_converge_worker_v1_worker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfigEntry.ProtoReflect.Descriptor instead.
func (*ProviderConfigEntry) Descriptor() ([]byte, []int) {
	return file_converge_worker_v1_worker_proto_rawDescGZIP(), []int{26}
}

func (x *ProviderConfigEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderConfigEntry) GetKindVersion() int32 {
	if x != nil {
		return x.KindVersion
	}
	return 0
}

func (x *ProviderConfigEntry) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProviderConfigEntry) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

var File_converge_worker_v1_worker_proto protoreflect.FileDescriptor

const file_converge_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1fconverge/worker/v1/worker.proto\x12\x12converge.worker.v1\"\x9c\x02\n" +
	"\x13WorkStreamClientMsg\x12=\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1d.converge.worker.v1.SubscribeH\x00R\tsubscribe\x12?\n" +
	"\bcomplete\x18\x02 \x01(\v2!.converge.worker.v1.StageCompleteH\x00R\bcomplete\x12:\n" +
	"\binterest\x18\x03 \x01(\v2\x1c.converge.worker.v1.InterestH\x00R\binterest\x12A\n" +
	"\theartbeat\x18\x04 \x01(\v2!.converge.worker.v1.WorkHeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04body\"\xa4\x01\n" +
	"\tSubscribe\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12!\n" +
	"\fmax_inflight\x18\x02 \x01(\rR\vmaxInflight\x12#\n" +
	"\rkind_versions\x18\x03 \x03(\x05R\fkindVersions\x129\n" +
	"\aresumed\x18\x04 \x03(\v2\x1f.converge.worker.v1.ResumedTaskR\aresumed\"O\n" +
	"\vResumedTask\x12\x1f\n" +
	"\vlease_token\x18\x01 \x01(\tR\n" +
	"leaseToken\x12\x1f\n" +
	"\vclaim_epoch\x18\x02 \x01(\x03R\n" +
	"claimEpoch\"\x96\x01\n" +
	"\x13WorkStreamServerMsg\x123\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.converge.worker.v1.StageTaskH\x00R\x04task\x12B\n" +
	"\x06config\x18\x02 \x01(\v2(.converge.worker.v1.ProviderConfigUpdateH\x00R\x06configB\x06\n" +
	"\x04body\"Q\n" +
	"\rWorkHeartbeat\x12\x1f\n" +
	"\vlease_token\x18\x01 \x03(\tR\n" +
	"leaseToken\x12\x1f\n" +
	"\vclaim_epoch\x18\x02 \x03(\x03R\n" +
	"claimEpoch\"}\n" +
	"\x14ProviderConfigUpdate\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\fkind_version\x18\x02 \x01(\x05R\vkindVersion\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12\x16\n" +
	"\x06bundle\x18\x04 \x01(\fR\x06bundle\"\xc2\x06\n" +
	"\tStageTask\x12/\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x19.converge.worker.v1.StageR\x05stage\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12!\n" +
	"\fkind_version\x18\x03 \x01(\x05R\vkindVersion\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\fR\n" +
	"resourceId\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03R\n" +
	"generation\x12\x1a\n" +
	"\breaction\x18\x06 \x01(\tR\breaction\x12\x1f\n" +
	"\vlease_token\x18\a \x01(\tR\n" +
	"leaseToken\x12\x1f\n" +
	"\vclaim_epoch\x18\b \x01(\x03R\n" +
	"claimEpoch\x12)\n" +
	"\x10manifest_version\x18\t \x01(\x03R\x0fmanifestVersion\x12'\n" +
	"\x0fprovider_config\x18\n" +
	" \x01(\fR\x0eproviderConfig\x12'\n" +
	"\x0fprovider_bundle\x18\v \x01(\fR\x0eproviderBundle\x12(\n" +
	"\x10task_deadline_ms\x18\f \x01(\x03R\x0etaskDeadlineMs\x12C\n" +
	"\vcompose_req\x18\r \x01(\v2\".converge.worker.v1.ComposeRequestR\n" +
	"composeReq\x12:\n" +
	"\bwork_req\x18\x0e \x01(\v2\x1f.converge.worker.v1.WorkRequestR\aworkReq\x12@\n" +
	"\n" +
	"rollup_req\x18\x0f \x01(\v2!.converge.worker.v1.RollupRequestR\trollupReq\x12@\n" +
	"\n" +
	"delete_req\x18\x10 \x01(\v2!.converge.worker.v1.DeleteRequestR\tdeleteReq\x12C\n" +
	"\voperate_req\x18\x11 \x01(\v2\".converge.worker.v1.OperateRequestR\n" +
	"operateReq\x12=\n" +
	"\treact_req\x18\x12 \x01(\v2 .converge.worker.v1.ReactRequestR\breactReq\"\x9c\x04\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\fR\aownerId\x12\x17\n" +
	"\aroot_id\x18\x05 \x01(\fR\x06rootId\x12\x12\n" +
	"\x04spec\x18\x06 \x01(\fR\x04spec\x12\x16\n" +
	"\x06status\x18\a \x01(\fR\x06status\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\x03R\n" +
	"generation\x12\x1d\n" +
	"\n" +
	"synced_gen\x18\t \x01(\x03R\tsyncedGen\x12\x19\n" +
	"\bis_ready\x18\n" +
	" \x01(\bR\aisReady\x12\x1e\n" +
	"\n" +
	"finalizers\x18\v \x03(\tR\n" +
	"finalizers\x127\n" +
	"\x18deletion_requested_at_ms\x18\f \x01(\x03R\x15deletionRequestedAtMs\x12&\n" +
	"\x0ffrozen_until_ms\x18\r \x01(\x03R\rfrozenUntilMs\x12 \n" +
	"\vquarantined\x18\x0e \x01(\bR\vquarantined\x12@\n" +
	"\x06labels\x18\x0f \x03(\v2(.converge.worker.v1.Resource.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\vResourceRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"W\n" +
	"\tValueFlow\x12'\n" +
	"\x0fdependent_field\x18\x01 \x01(\tR\x0edependentField\x12!\n" +
	"\fsource_field\x18\x02 \x01(\tR\vsourceField\"\xe8\x01\n" +
	"\tChildSpec\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).converge.worker.v1.ChildSpec.LabelsEntryR\x06labels\x12!\n" +
	"\fkind_version\x18\x05 \x01(\x05R\vkindVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\aDepEdge\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1f.converge.worker.v1.ResourceRefR\x04from\x12/\n" +
	"\x02to\x18\x02 \x01(\v2\x1f.converge.worker.v1.ResourceRefR\x02to\x125\n" +
	"\x06values\x18\x03 \x03(\v2\x1d.converge.worker.v1.ValueFlowR\x06values\"\x92\x01\n" +
	"\x12ProviderConfigSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x12\n" +
	"\x04spec\x18\x04 \x01(\fR\x04spec\x12!\n" +
	"\fkind_version\x18\x05 \x01(\x05R\vkindVersion\"\x95\x01\n" +
	"\tOperation\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\fR\n" +
	"resourceId\x12\x12\n" +
	"\x04verb\x18\x02 \x01(\tR\x04verb\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\"\xaa\x02\n" +
	"\x0eComposeRequest\x120\n" +
	"\x04root\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\x04root\x128\n" +
	"\bobserved\x18\x02 \x03(\v2\x1c.converge.worker.v1.ResourceR\bobserved\x127\n" +
	"\adesired\x18\x03 \x03(\v2\x1d.converge.worker.v1.ChildSpecR\adesired\x121\n" +
	"\x05edges\x18\x04 \x03(\v2\x1b.converge.worker.v1.DepEdgeR\x05edges\x12@\n" +
	"\aconfigs\x18\x05 \x03(\v2&.converge.worker.v1.ProviderConfigSpecR\aconfigs\"_\n" +
	"\vWorkRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\bresource\x12\x16\n" +
	"\x06status\x18\x02 \x01(\fR\x06status\"\x99\x01\n" +
	"\rRollupRequest\x120\n" +
	"\x04root\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\x04root\x12>\n" +
	"\vdescendants\x18\x02 \x03(\v2\x1c.converge.worker.v1.ResourceR\vdescendants\x12\x16\n" +
	"\x06status\x18\x03 \x01(\fR\x06status\"I\n" +
	"\rDeleteRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\bresource\"\x87\x01\n" +
	"\x0eOperateRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\bresource\x12;\n" +
	"\toperation\x18\x02 \x01(\v2\x1d.converge.worker.v1.OperationR\toperation\"\xa9\x01\n" +
	"\fReactRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.converge.worker.v1.ResourceR\bresource\x12>\n" +
	"\n" +
	"transition\x18\x02 \x01(\x0e2\x1e.converge.worker.v1.TransitionR\n" +
	"transition\x12\x1f\n" +
	"\vdedup_token\x18\x03 \x01(\tR\n" +
	"dedupToken\"i\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x92\x03\n" +
	"\rStageComplete\x12\x1f\n" +
	"\vlease_token\x18\x01 \x01(\tR\n" +
	"leaseToken\x12/\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x19.converge.worker.v1.StageR\x05stage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\fR\x06status\x12=\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x1d.converge.worker.v1.ConditionR\n" +
	"conditions\x12;\n" +
	"\acompose\x18\x05 \x01(\v2!.converge.worker.v1.ComposeResultR\acompose\x12\x16\n" +
	"\x06output\x18\x06 \x01(\fR\x06output\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12!\n" +
	"\ffailed_stage\x18\b \x01(\x05R\vfailedStage\x12\x1a\n" +
	"\bterminal\x18\t \x01(\bR\bterminal\x12\x1f\n" +
	"\vclaim_epoch\x18\n" +
	" \x01(\x03R\n" +
	"claimEpoch\"\x94\x02\n" +
	"\rComposeResult\x127\n" +
	"\adesired\x18\x01 \x03(\v2\x1d.converge.worker.v1.ChildSpecR\adesired\x121\n" +
	"\x05edges\x18\x02 \x03(\v2\x1b.converge.worker.v1.DepEdgeR\x05edges\x12@\n" +
	"\aconfigs\x18\x03 \x03(\v2&.converge.worker.v1.ProviderConfigSpecR\aconfigs\x12\x16\n" +
	"\x06status\x18\x04 \x01(\fR\x06status\x12=\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x1d.converge.worker.v1.ConditionR\n" +
	"conditions\"x\n" +
	"\bInterest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06credit\x18\x02 \x01(\x05R\x06credit\x12\x1d\n" +
	"\n" +
	"has_worker\x18\x03 \x01(\bR\thasWorker\x12!\n" +
	"\fkind_version\x18\x04 \x01(\x05R\vkindVersion\"U\n" +
	"\x18GetProviderConfigRequest\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12#\n" +
	"\rkind_versions\x18\x02 \x03(\x05R\fkindVersions\"^\n" +
	"\x19GetProviderConfigResponse\x12A\n" +
	"\aentries\x18\x01 \x03(\v2'.converge.worker.v1.ProviderConfigEntryR\aentries\"|\n" +
	"\x13ProviderConfigEntry\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\fkind_version\x18\x02 \x01(\x05R\vkindVersion\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12\x16\n" +
	"\x06bundle\x18\x04 \x01(\fR\x06bundle*\x89\x01\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTAGE_COMPOSE\x10\x01\x12\x0e\n" +
	"\n" +
	"STAGE_WORK\x10\x02\x12\x10\n" +
	"\fSTAGE_ROLLUP\x10\x03\x12\x10\n" +
	"\fSTAGE_DELETE\x10\x04\x12\x11\n" +
	"\rSTAGE_OPERATE\x10\x05\x12\x0f\n" +
	"\vSTAGE_REACT\x10\x06*\x9f\x01\n" +
	"\n" +
	"Transition\x12\x1a\n" +
	"\x16TRANSITION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSITION_CREATED\x10\x01\x12\x15\n" +
	"\x11TRANSITION_SYNCED\x10\x02\x12\x17\n" +
	"\x13TRANSITION_DEGRADED\x10\x03\x12\x15\n" +
	"\x11TRANSITION_FAILED\x10\x04\x12\x16\n" +
	"\x12TRANSITION_DELETED\x10\x052\xe5\x01\n" +
	"\rWorkerService\x12b\n" +
	"\n" +
	"WorkStream\x12'.converge.worker.v1.WorkStreamClientMsg\x1a'.converge.worker.v1.WorkStreamServerMsg(\x010\x01\x12p\n" +
	"\x11GetProviderConfig\x12,.converge.worker.v1.GetProviderConfigRequest\x1a-.converge.worker.v1.GetProviderConfigResponseB9Z7github.com/salesforce/converge/sdk-go/workerpb;workerpbb\x06proto3"

var (
	file_converge_worker_v1_worker_proto_rawDescOnce sync.Once
	file_converge_worker_v1_worker_proto_rawDescData []byte
)

func file_converge_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_converge_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_converge_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_converge_worker_v1_worker_proto_rawDesc), len(file_converge_worker_v1_worker_proto_rawDesc)))
	})
	return file_converge_worker_v1_worker_proto_rawDescData
}

var file_converge_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_converge_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_converge_worker_v1_worker_proto_goTypes = []any{
	(Stage)(0),                        // 0: converge.worker.v1.Stage
	(Transition)(0),                   // 1: converge.worker.v1.Transition
	(*WorkStreamClientMsg)(nil),       // 2: converge.worker.v1.WorkStreamClientMsg
	(*Subscribe)(nil),                 // 3: converge.worker.v1.Subscribe
	(*ResumedTask)(nil),               // 4: converge.worker.v1.ResumedTask
	(*WorkStreamServerMsg)(nil),       // 5: converge.worker.v1.WorkStreamServerMsg
	(*WorkHeartbeat)(nil),             // 6: converge.worker.v1.WorkHeartbeat
	(*ProviderConfigUpdate)(nil),      // 7: converge.worker.v1.ProviderConfigUpdate
	(*StageTask)(nil),                 // 8: converge.worker.v1.StageTask
	(*Resource)(nil),                  // 9: converge.worker.v1.Resource
	(*ResourceRef)(nil),               // 10: converge.worker.v1.ResourceRef
	(*ValueFlow)(nil),                 // 11: converge.worker.v1.ValueFlow
	(*ChildSpec)(nil),                 // 12: converge.worker.v1.ChildSpec
	(*DepEdge)(nil),                   // 13: converge.worker.v1.DepEdge
	(*ProviderConfigSpec)(nil),        // 14: converge.worker.v1.ProviderConfigSpec
	(*Operation)(nil),                 // 15: converge.worker.v1.Operation
	(*ComposeRequest)(nil),            // 16: converge.worker.v1.ComposeRequest
	(*WorkRequest)(nil),               // 17: converge.worker.v1.WorkRequest
	(*RollupRequest)(nil),             // 18: converge.worker.v1.RollupRequest
	(*DeleteRequest)(nil),             // 19: converge.worker.v1.DeleteRequest
	(*OperateRequest)(nil),            // 20: converge.worker.v1.OperateRequest
	(*ReactRequest)(nil),              // 21: converge.worker.v1.ReactRequest
	(*Condition)(nil),                 // 22: converge.worker.v1.Condition
	(*StageComplete)(nil),             // 23: converge.worker.v1.StageComplete
	(*ComposeResult)(nil),             // 24: converge.worker.v1.ComposeResult
	(*Interest)(nil),                  // 25: converge.worker.v1.Interest
	(*GetProviderConfigRequest)(nil),  // 26: converge.worker.v1.GetProviderConfigRequest
	(*GetProviderConfigResponse)(nil), // 27: converge.worker.v1.GetProviderConfigResponse
	(*ProviderConfigEntry)(nil),       // 28: converge.worker.v1.ProviderConfigEntry
	nil,                               // 29: converge.worker.v1.Resource.LabelsEntry
	nil,                               // 30: converge.worker.v1.ChildSpec.LabelsEntry
}
var file_converge_worker_v1_worker_proto_depIdxs = []int32{
	3,  // 0: converge.worker.v1.WorkStreamClientMsg.subscribe:type_name -> converge.worker.v1.Subscribe
	23, // 1: converge.worker.v1.WorkStreamClientMsg.complete:type_name -> converge.worker.v1.StageComplete
	25, // 2: converge.worker.v1.WorkStreamClientMsg.interest:type_name -> converge.worker.v1.Interest
	6,  // 3: converge.worker.v1.WorkStreamClientMsg.heartbeat:type_name -> converge.worker.v1.WorkHeartbeat
	4,  // 4: converge.worker.v1.Subscribe.resumed:type_name -> converge.worker.v1.ResumedTask
	8,  // 5: converge.worker.v1.WorkStreamServerMsg.task:type_name -> converge.worker.v1.StageTask
	7,  // 6: converge.worker.v1.WorkStreamServerMsg.config:type_name -> converge.worker.v1.ProviderConfigUpdate
	0,  // 7: converge.worker.v1.StageTask.stage:type_name -> converge.worker.v1.Stage
	16, // 8: converge.worker.v1.StageTask.compose_req:type_name -> converge.worker.v1.ComposeRequest
	17, // 9: converge.worker.v1.StageTask.work_req:type_name -> converge.worker.v1.WorkRequest
	18, // 10: converge.worker.v1.StageTask.rollup_req:type_name -> converge.worker.v1.RollupRequest
	19, // 11: converge.worker.v1.StageTask.delete_req:type_name -> converge.worker.v1.DeleteRequest
	20, // 12: converge.worker.v1.StageTask.operate_req:type_name -> converge.worker.v1.OperateRequest
	21, // 13: converge.worker.v1.StageTask.react_req:type_name -> converge.worker.v1.ReactRequest
	29, // 14: converge.worker.v1.Resource.labels:type_name -> converge.worker.v1.Resource.LabelsEntry
	30, // 15: converge.worker.v1.ChildSpec.labels:type_name -> converge.worker.v1.ChildSpec.LabelsEntry
	10, // 16: converge.worker.v1.DepEdge.from:type_name -> converge.worker.v1.ResourceRef
	10, // 17: converge.worker.v1.DepEdge.to:type_name -> converge.worker.v1.ResourceRef
	11, // 18: converge.worker.v1.DepEdge.values:type_name -> converge.worker.v1.ValueFlow
	9,  // 19: converge.worker.v1.ComposeRequest.root:type_name -> converge.worker.v1.Resource
	9,  // 20: converge.worker.v1.ComposeRequest.observed:type_name -> converge.worker.v1.Resource
	12, // 21: converge.worker.v1.ComposeRequest.desired:type_name -> converge.worker.v1.ChildSpec
	13, // 22: converge.worker.v1.ComposeRequest.edges:type_name -> converge.worker.v1.DepEdge
	14, // 23: converge.worker.v1.ComposeRequest.configs:type_name -> converge.worker.v1.ProviderConfigSpec
	9,  // 24: converge.worker.v1.WorkRequest.resource:type_name -> converge.worker.v1.Resource
	9,  // 25: converge.worker.v1.RollupRequest.root:type_name -> converge.worker.v1.Resource
	9,  // 26: converge.worker.v1.RollupRequest.descendants:type_name -> converge.worker.v1.Resource
	9,  // 27: converge.worker.v1.DeleteRequest.resource:type_name -> converge.worker.v1.Resource
	9,  // 28: converge.worker.v1.OperateRequest.resource:type_name -> converge.worker.v1.Resource
	15, // 29: converge.worker.v1.OperateRequest.operation:type_name -> converge.worker.v1.Operation
	9,  // 30: converge.worker.v1.ReactRequest.resource:type_name -> converge.worker.v1.Resource
	1,  // 31: converge.worker.v1.ReactRequest.transition:type_name -> converge.worker.v1.Transition
	0,  // 32: converge.worker.v1.StageComplete.stage:type_name -> converge.worker.v1.Stage
	22, // 33: converge.worker.v1.StageComplete.conditions:type_name -> converge.worker.v1.Condition
	24, // 34: converge.worker.v1.StageComplete.compose:type_name -> converge.worker.v1.ComposeResult
	12, // 35: converge.worker.v1.ComposeResult.desired:type_name -> converge.worker.v1.ChildSpec
	13, // 36: converge.worker.v1.ComposeResult.edges:type_name -> converge.worker.v1.DepEdge
	14, // 37: converge.worker.v1.ComposeResult.configs:type_name -> converge.worker.v1.ProviderConfigSpec
	22, // 38: converge.worker.v1.ComposeResult.conditions:type_name -> converge.worker.v1.Condition
	28, // 39: converge.worker.v1.GetProviderConfigResponse.entries:type_name -> converge.worker.v1.ProviderConfigEntry
	2,  // 40: converge.worker.v1.WorkerService.WorkStream:input_type -> converge.worker.v1.WorkStreamClientMsg
	26, // 41: converge.worker.v1.WorkerService.GetProviderConfig:input_type -> converge.worker.v1.GetProviderConfigRequest
	5,  // 42: converge.worker.v1.WorkerService.WorkStream:output_type -> converge.worker.v1.WorkStreamServerMsg
	27, // 43: converge.worker.v1.WorkerService.GetProviderConfig:output_type -> converge.worker.v1.GetProviderConfigResponse
	42, // [42:44] is the sub-list for method output_type
	40, // [40:42] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_converge_worker_v1_worker_proto_init() }
func file_converge_worker_v1_worker_proto_init() {
	if File_converge_worker_v1_worker_proto != nil {
		return
	}
	file_converge_worker_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkStreamClientMsg_Subscribe)(nil),
		(*WorkStreamClientMsg_Complete)(nil),
		(*WorkStreamClientMsg_Interest)(nil),
		(*WorkStreamClientMsg_Heartbeat)(nil),
	}
	file_converge_worker_v1_worker_proto_msgTypes[3].OneofWrappers = []any{
		(*WorkStreamServerMsg_Task)(nil),
		(*WorkStreamServerMsg_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_converge_worker_v1_worker_proto_rawDesc), len(file_converge_worker_v1_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_converge_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_converge_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_converge_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_converge_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_converge_worker_v1_worker_proto = out.File
	file_converge_worker_v1_worker_proto_goTypes = nil
	file_converge_worker_v1_worker_proto_depIdxs = nil
}
