// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: converge/mesh/v1/mesh.proto

// Package converge.mesh.v1 is the INTERNAL broker↔broker mesh API — NOT part of any
// worker SDK's contract. It is generated into internal/meshpb, so a worker SDK (in
// any language) structurally cannot reach it: the only tissue between a worker and a
// broker is converge.worker.v1 (sdk-go/workerpb). This separation is deliberate — the
// mesh may evolve freely (new frames, new routing RPCs, a different transport)
// WITHOUT touching or regenerating the public worker contract that N language SDKs
// depend on.
//
// The dependency is one-way: this proto IMPORTS converge.worker.v1 to REUSE its
// task/result/interest messages byte-for-byte (a mesh-forwarded task IS a
// worker.v1.StageTask; a returned result IS a worker.v1.StageComplete), so the
// forwarded path never re-marshals or re-defines them and the two surfaces can never
// drift. converge.worker.v1 never references this proto.
package meshpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	meshpb "github.com/salesforce/converge/internal/meshpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MeshServiceName is the fully-qualified name of the MeshService service.
	MeshServiceName = "converge.mesh.v1.MeshService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MeshServiceRouteProcedure is the fully-qualified name of the MeshService's Route RPC.
	MeshServiceRouteProcedure = "/converge.mesh.v1.MeshService/Route"
)

// MeshServiceClient is a client for the converge.mesh.v1.MeshService service.
type MeshServiceClient interface {
	// Route is the persistent broker↔broker mesh link (a NATS route). Every broker
	// holds ONE long-lived bidi Route stream to every peer (the lower member_id
	// dials, the higher accepts → exactly one stream per pair). Over it each broker
	// eagerly PUSHES a coarse per-kind worker PRESENCE hint (Interest frames: "I have a
	// ready worker for (kind, kind_version)") so a claimer knows which peer can run a
	// kind it lacks a local worker for; and the instant a broker CLAIMS a task it has
	// no local worker for, it PUSHES the StageTask — a SELF-CONTAINED, durable work
	// reference carrying its (claim_epoch, generation, manifest_version) fence — down
	// the route to such a peer. The peer runs it on its local worker and returns the
	// worker's StageComplete back over the SAME route (the `complete` frame); the
	// owning broker — which holds the parked stage + the durable write path — does the
	// fenced result write. The fence is owner-independent (claim_epoch, not identity),
	// so a stale/late/duplicate return no-ops. The presence hint is best-effort — a
	// wrong/stale hint just falls back to the claimer re-claiming and re-dispatching;
	// nothing is lost. A peer/worker/route failure strands nothing: the row's heartbeat
	// lapses and the reaper reclaims it (bumping the epoch), the unified backstop.
	Route(context.Context) *connect.BidiStreamForClient[meshpb.RouteFrame, meshpb.RouteFrame]
}

// NewMeshServiceClient constructs a client for the converge.mesh.v1.MeshService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMeshServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MeshServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	meshServiceMethods := meshpb.File_converge_mesh_v1_mesh_proto.Services().ByName("MeshService").Methods()
	return &meshServiceClient{
		route: connect.NewClient[meshpb.RouteFrame, meshpb.RouteFrame](
			httpClient,
			baseURL+MeshServiceRouteProcedure,
			connect.WithSchema(meshServiceMethods.ByName("Route")),
			connect.WithClientOptions(opts...),
		),
	}
}

// meshServiceClient implements MeshServiceClient.
type meshServiceClient struct {
	route *connect.Client[meshpb.RouteFrame, meshpb.RouteFrame]
}

// Route calls converge.mesh.v1.MeshService.Route.
func (c *meshServiceClient) Route(ctx context.Context) *connect.BidiStreamForClient[meshpb.RouteFrame, meshpb.RouteFrame] {
	return c.route.CallBidiStream(ctx)
}

// MeshServiceHandler is an implementation of the converge.mesh.v1.MeshService service.
type MeshServiceHandler interface {
	// Route is the persistent broker↔broker mesh link (a NATS route). Every broker
	// holds ONE long-lived bidi Route stream to every peer (the lower member_id
	// dials, the higher accepts → exactly one stream per pair). Over it each broker
	// eagerly PUSHES a coarse per-kind worker PRESENCE hint (Interest frames: "I have a
	// ready worker for (kind, kind_version)") so a claimer knows which peer can run a
	// kind it lacks a local worker for; and the instant a broker CLAIMS a task it has
	// no local worker for, it PUSHES the StageTask — a SELF-CONTAINED, durable work
	// reference carrying its (claim_epoch, generation, manifest_version) fence — down
	// the route to such a peer. The peer runs it on its local worker and returns the
	// worker's StageComplete back over the SAME route (the `complete` frame); the
	// owning broker — which holds the parked stage + the durable write path — does the
	// fenced result write. The fence is owner-independent (claim_epoch, not identity),
	// so a stale/late/duplicate return no-ops. The presence hint is best-effort — a
	// wrong/stale hint just falls back to the claimer re-claiming and re-dispatching;
	// nothing is lost. A peer/worker/route failure strands nothing: the row's heartbeat
	// lapses and the reaper reclaims it (bumping the epoch), the unified backstop.
	Route(context.Context, *connect.BidiStream[meshpb.RouteFrame, meshpb.RouteFrame]) error
}

// NewMeshServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMeshServiceHandler(svc MeshServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	meshServiceMethods := meshpb.File_converge_mesh_v1_mesh_proto.Services().ByName("MeshService").Methods()
	meshServiceRouteHandler := connect.NewBidiStreamHandler(
		MeshServiceRouteProcedure,
		svc.Route,
		connect.WithSchema(meshServiceMethods.ByName("Route")),
		connect.WithHandlerOptions(opts...),
	)
	return "/converge.mesh.v1.MeshService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MeshServiceRouteProcedure:
			meshServiceRouteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMeshServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMeshServiceHandler struct{}

func (UnimplementedMeshServiceHandler) Route(context.Context, *connect.BidiStream[meshpb.RouteFrame, meshpb.RouteFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("converge.mesh.v1.MeshService.Route is not implemented"))
}
