// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: converge/mesh/v1/mesh.proto

// Package converge.mesh.v1 is the INTERNAL broker↔broker mesh API — NOT part of any
// worker SDK's contract. It is generated into internal/meshpb, so a worker SDK (in
// any language) structurally cannot reach it: the only tissue between a worker and a
// broker is converge.worker.v1 (sdk-go/workerpb). This separation is deliberate — the
// mesh may evolve freely (new frames, new routing RPCs, a different transport)
// WITHOUT touching or regenerating the public worker contract that N language SDKs
// depend on.
//
// The dependency is one-way: this proto IMPORTS converge.worker.v1 to REUSE its
// task/result/interest messages byte-for-byte (a mesh-forwarded task IS a
// worker.v1.StageTask; a returned result IS a worker.v1.StageComplete), so the
// forwarded path never re-marshals or re-defines them and the two surfaces can never
// drift. converge.worker.v1 never references this proto.

package meshpb

import (
	workerpb "github.com/salesforce/converge/sdk-go/workerpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteFrame is one message on the persistent broker↔broker Route bidi stream.
// The stream is SYMMETRIC — both directions carry RouteFrames — because each broker
// is both a producer (pushes its claimed tasks) and a consumer (advertises its
// worker presence) toward the same peer. Exactly one body field is set. The
// task/interest payloads are the PUBLIC worker.v1 messages, reused by import so a
// forwarded task is byte-identical to a locally-dispatched one.
type RouteFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*RouteFrame_Hello
	//	*RouteFrame_Interest
	//	*RouteFrame_Task
	//	*RouteFrame_Complete
	Body          isRouteFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteFrame) Reset() {
	*x = RouteFrame{}
	mi := &file_converge_mesh_v1_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteFrame) ProtoMessage() {}

func (x *RouteFrame) ProtoReflect() protoreflect.Message {
	mi := &file_converge_mesh_v1_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteFrame.ProtoReflect.Descriptor instead.
func (*RouteFrame) Descriptor() ([]byte, []int) {
	return file_converge_mesh_v1_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *RouteFrame) GetBody() isRouteFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RouteFrame) GetHello() *RouteHello {
	if x != nil {
		if x, ok := x.Body.(*RouteFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *RouteFrame) GetInterest() *workerpb.Interest {
	if x != nil {
		if x, ok := x.Body.(*RouteFrame_Interest); ok {
			return x.Interest
		}
	}
	return nil
}

func (x *RouteFrame) GetTask() *workerpb.StageTask {
	if x != nil {
		if x, ok := x.Body.(*RouteFrame_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *RouteFrame) GetComplete() *workerpb.StageComplete {
	if x != nil {
		if x, ok := x.Body.(*RouteFrame_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isRouteFrame_Body interface {
	isRouteFrame_Body()
}

type RouteFrame_Hello struct {
	Hello *RouteHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // once on open: the sender's member_id (identity)
}

type RouteFrame_Interest struct {
	Interest *workerpb.Interest `protobuf:"bytes,2,opt,name=interest,proto3,oneof"` // coarse per-kind worker PRESENCE hint (eager, coalesced)
}

type RouteFrame_Task struct {
	Task *workerpb.StageTask `protobuf:"bytes,3,opt,name=task,proto3,oneof"` // a claimed task PUSHED to a peer with a ready worker
}

type RouteFrame_Complete struct {
	Complete *workerpb.StageComplete `protobuf:"bytes,4,opt,name=complete,proto3,oneof"` // the peer's worker RESULT for a pushed task, returned to the owner
}

func (*RouteFrame_Hello) isRouteFrame_Body() {}

func (*RouteFrame_Interest) isRouteFrame_Body() {}

func (*RouteFrame_Task) isRouteFrame_Body() {}

func (*RouteFrame_Complete) isRouteFrame_Body() {}

// RouteHello is the first frame on a Route stream: the dialer/acceptor exchange
// their member_id so each side attaches the stream to the right peer record (for
// presence routing). Sent exactly once per stream open.
type RouteHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteHello) Reset() {
	*x = RouteHello{}
	mi := &file_converge_mesh_v1_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteHello) ProtoMessage() {}

func (x *RouteHello) ProtoReflect() protoreflect.Message {
	mi := &file_converge_mesh_v1_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteHello.ProtoReflect.Descriptor instead.
func (*RouteHello) Descriptor() ([]byte, []int) {
	return file_converge_mesh_v1_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *RouteHello) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_converge_mesh_v1_mesh_proto protoreflect.FileDescriptor

const file_converge_mesh_v1_mesh_proto_rawDesc = "" +
	"\n" +
	"\x1bconverge/mesh/v1/mesh.proto\x12\x10converge.mesh.v1\x1a\x1fconverge/worker/v1/worker.proto\"\xfc\x01\n" +
	"\n" +
	"RouteFrame\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.converge.mesh.v1.RouteHelloH\x00R\x05hello\x12:\n" +
	"\binterest\x18\x02 \x01(\v2\x1c.converge.worker.v1.InterestH\x00R\binterest\x123\n" +
	"\x04task\x18\x03 \x01(\v2\x1d.converge.worker.v1.StageTaskH\x00R\x04task\x12?\n" +
	"\bcomplete\x18\x04 \x01(\v2!.converge.worker.v1.StageCompleteH\x00R\bcompleteB\x06\n" +
	"\x04body\")\n" +
	"\n" +
	"RouteHello\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId2V\n" +
	"\vMeshService\x12G\n" +
	"\x05Route\x12\x1c.converge.mesh.v1.RouteFrame\x1a\x1c.converge.mesh.v1.RouteFrame(\x010\x01B7Z5github.com/salesforce/converge/internal/meshpb;meshpbb\x06proto3"

var (
	file_converge_mesh_v1_mesh_proto_rawDescOnce sync.Once
	file_converge_mesh_v1_mesh_proto_rawDescData []byte
)

func file_converge_mesh_v1_mesh_proto_rawDescGZIP() []byte {
	file_converge_mesh_v1_mesh_proto_rawDescOnce.Do(func() {
		file_converge_mesh_v1_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_converge_mesh_v1_mesh_proto_rawDesc), len(file_converge_mesh_v1_mesh_proto_rawDesc)))
	})
	return file_converge_mesh_v1_mesh_proto_rawDescData
}

var file_converge_mesh_v1_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_converge_mesh_v1_mesh_proto_goTypes = []any{
	(*RouteFrame)(nil),             // 0: converge.mesh.v1.RouteFrame
	(*RouteHello)(nil),             // 1: converge.mesh.v1.RouteHello
	(*workerpb.Interest)(nil),      // 2: converge.worker.v1.Interest
	(*workerpb.StageTask)(nil),     // 3: converge.worker.v1.StageTask
	(*workerpb.StageComplete)(nil), // 4: converge.worker.v1.StageComplete
}
var file_converge_mesh_v1_mesh_proto_depIdxs = []int32{
	1, // 0: converge.mesh.v1.RouteFrame.hello:type_name -> converge.mesh.v1.RouteHello
	2, // 1: converge.mesh.v1.RouteFrame.interest:type_name -> converge.worker.v1.Interest
	3, // 2: converge.mesh.v1.RouteFrame.task:type_name -> converge.worker.v1.StageTask
	4, // 3: converge.mesh.v1.RouteFrame.complete:type_name -> converge.worker.v1.StageComplete
	0, // 4: converge.mesh.v1.MeshService.Route:input_type -> converge.mesh.v1.RouteFrame
	0, // 5: converge.mesh.v1.MeshService.Route:output_type -> converge.mesh.v1.RouteFrame
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_converge_mesh_v1_mesh_proto_init() }
func file_converge_mesh_v1_mesh_proto_init() {
	if File_converge_mesh_v1_mesh_proto != nil {
		return
	}
	file_converge_mesh_v1_mesh_proto_msgTypes[0].OneofWrappers = []any{
		(*RouteFrame_Hello)(nil),
		(*RouteFrame_Interest)(nil),
		(*RouteFrame_Task)(nil),
		(*RouteFrame_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_converge_mesh_v1_mesh_proto_rawDesc), len(file_converge_mesh_v1_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_converge_mesh_v1_mesh_proto_goTypes,
		DependencyIndexes: file_converge_mesh_v1_mesh_proto_depIdxs,
		MessageInfos:      file_converge_mesh_v1_mesh_proto_msgTypes,
	}.Build()
	File_converge_mesh_v1_mesh_proto = out.File
	file_converge_mesh_v1_mesh_proto_goTypes = nil
	file_converge_mesh_v1_mesh_proto_depIdxs = nil
}
