import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// The canonical public deploy is github.com/salesforce/converge, whose GitHub
// Pages serves under the org user-pages domain at the /converge/ project path:
//   https://salesforce.github.io/converge/
// url is the origin, baseUrl is the sub-path — both MUST match the deploy target
// or every asset/link resolves to the wrong path and the site renders blank
// (they resolve fine locally regardless).
//
// A DIFFERENT target (e.g. a throwaway test repo on a random *.pages.github.io
// subdomain, which serves at the ROOT with no project sub-path) needs a different
// url + baseUrl. Rather than hand-edit this file per deploy, both are overridable
// via env so one config serves every target:
//   DOCS_URL      the origin           (default https://salesforce.github.io)
//   DOCS_BASE_URL the sub-path         (default /converge/ ; use / for a root site)
// e.g. a root test deploy:
//   DOCS_URL=https://turbo-engine-8gqpr34.pages.github.io DOCS_BASE_URL=/ npm run build
const organizationName = 'salesforce';
const projectName = 'converge';

// Docusaurus requires baseUrl to END WITH a slash, so normalize the env override
// (the CI workflow passes configure-pages' base_path, and a hand-run override is
// easy to write without the trailing slash) — "" -> "/", "/converge" -> "/converge/".
const rawBaseUrl = process.env.DOCS_BASE_URL ?? `/${projectName}/`;
const baseUrl = rawBaseUrl.endsWith('/') ? rawBaseUrl : `${rawBaseUrl}/`;

const config: Config = {
  title: 'Converge',
  tagline:
    'A declarative orchestration engine for platform teams — describe resources as specs; the engine reconciles the world to match.',
  favicon: 'img/favicon.svg',

  url: process.env.DOCS_URL ?? `https://${organizationName}.github.io`,
  baseUrl,

  organizationName,
  projectName,

  // Fail the build on a broken internal link rather than shipping a dead one —
  // the docs cross-reference heavily, so this is the guardrail that catches a
  // stale relative link at CI time instead of in production.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  markdown: {
    // The broken-markdown-link hook moved here from the top-level
    // onBrokenMarkdownLinks option in Docusaurus v3.x (removed in v4). 'warn'
    // rather than 'throw' so a link INTO source code we render as a GitHub URL
    // (not an on-site page) can't fail the build.
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // No preset editUrl: the site's docs/ is a GENERATED, gitignored copy,
          // so a prefix here would point "Edit this page" at a nonexistent path.
          // Instead sync-docs.mjs emits a per-doc `custom_edit_url` pointing at
          // the canonical committed source on the public repo.
          routeBasePath: 'docs',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
    // Redoc-rendered API reference at /api, from the generated OpenAPI 3.1 spec.
    // sync-docs.mjs copies internal/api/openapi.golden.yaml → static/openapi.yaml
    // (the golden is the source of truth, regenerated by `just golden-openapi`),
    // so the reference always matches the shipped API. Redoc is read-only (no
    // "try it" console) — a clean three-panel reference.
    [
      'redocusaurus',
      {
        specs: [
          {
            id: 'converge-api',
            spec: 'static/openapi.yaml',
            route: '/api/',
          },
        ],
        // Tie Redoc's accent to the site's primary color for visual continuity.
        theme: { primaryColor: '#2563eb' },
      },
    ],
  ],

  themeConfig: {
    // Social-card (OpenGraph/Twitter) image shown when a page is shared.
    image: 'img/logo.png',
    docs: {
      sidebar: {
        // Keep every category expanded. Docusaurus defaults
        // autoCollapseSidebarCategories to true, which re-collapses the sibling
        // categories that don't contain the active page on each navigation — so a
        // reader clicking into Guides would see Components/Demos snap shut. We
        // author the sidebar as a flat, always-open outline (every category also
        // sets collapsed:false), so disable the auto-collapse to honor that.
        autoCollapseCategories: false,
      },
    },
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Converge',
      logo: {
        alt: 'Converge',
        src: 'img/favicon.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/docs/concepts',
          label: 'Concepts',
          position: 'left',
        },
        {
          to: '/docs/install',
          label: 'Install',
          position: 'left',
        },
        {
          to: '/docs/demos/classic',
          label: 'Demos',
          position: 'left',
        },
        {
          to: '/api/',
          label: 'API',
          position: 'left',
        },
        {
          href: `https://github.com/${organizationName}/${projectName}`,
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Introduction', to: '/docs/intro' },
            { label: 'Concepts', to: '/docs/concepts' },
            { label: 'Install & run', to: '/docs/install' },
            { label: 'Architecture', to: '/docs/architecture' },
            { label: 'Implement a provider', to: '/docs/implementing-a-provider' },
          ],
        },
        {
          title: 'Reference',
          items: [
            { label: 'API reference', to: '/api/' },
            { label: 'How Converge compares', to: '/docs/how-converge-compares' },
            { label: 'HA & DR', to: '/docs/ha-dr' },
            { label: 'TLS, mTLS & SPIFFE', to: '/docs/tls' },
            { label: 'Worker SDK spec', to: '/docs/spec/sdk-spec' },
          ],
        },
        {
          title: 'Project',
          items: [
            {
              label: 'GitHub',
              href: `https://github.com/${organizationName}/${projectName}`,
            },
            {
              label: 'Contributing',
              href: `https://github.com/${organizationName}/${projectName}/blob/main/CONTRIBUTING.md`,
            },
            {
              label: 'Security policy',
              href: `https://github.com/${organizationName}/${projectName}/blob/main/SECURITY.md`,
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Salesforce, Inc. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // Languages Converge's docs actually use in fenced code blocks.
      additionalLanguages: ['go', 'bash', 'json', 'yaml', 'protobuf', 'sql', 'toml'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
