import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The docs sidebar is authored by hand (not autogenerated) so the reading order
// is deliberate: an operator lands on Introduction → Install, a provider author
// follows Guides, and Reference/Components/Demos are lookups. Each `id` is the
// doc's path under website/docs/ (minus the .md extension).
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['intro', 'features', 'install'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['why-code-not-yaml', 'implementing-a-provider', 'tls', 'ha-dr'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['architecture', 'how-converge-compares', 'spec/sdk-spec'],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        'components/converge',
        'components/conctl',
        'components/stdworker',
        'components/sdk-go',
        'components/sdk-ts',
        'components/helm',
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      collapsed: false,
      items: [
        'demos/classic',
        'demos/datadriven',
        'demos/gitops',
        'demos/stdio',
        'demos/stdshell',
        'demos/stdterraform',
        'demos/typescript',
      ],
    },
  ],
};

export default sidebars;
