// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cluster_members.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClusterMember = `-- name: DeleteClusterMember :exec
DELETE FROM cluster_members WHERE member_id = $1
`

// Deregister: delete this member's row on a clean shutdown so the cluster
// view drops it immediately (instead of waiting for the GC TTL). Called as the
// LAST shutdown step under a bounded context so a DB/network blip can't hang
// the process — the GC then reclaims the row as the crash/timeout fallback.
func (q *Queries) DeleteClusterMember(ctx context.Context, memberID string) error {
	_, err := q.db.Exec(ctx, deleteClusterMember, memberID)
	return err
}

const gCStaleClusterMembers = `-- name: GCStaleClusterMembers :one
SELECT gc_stale_cluster_members($1::int)::int AS deleted
`

// Hard-delete members whose heartbeat is older than ttl_seconds; returns the
// number reclaimed. Driven by the ControlPlane ClusterMemberGC sweeper.
func (q *Queries) GCStaleClusterMembers(ctx context.Context, dollar_1 int32) (int32, error) {
	row := q.db.QueryRow(ctx, gCStaleClusterMembers, dollar_1)
	var deleted int32
	err := row.Scan(&deleted)
	return deleted, err
}

const upsertClusterMember = `-- name: UpsertClusterMember :exec

INSERT INTO cluster_members (
    member_id, role, shards, config, in_flight, workers,
    version, hostname, pid, started_at, last_heartbeat
) VALUES (
    $1, $2, $3::int4range, $4, $5, $6::jsonb,
    $7, $8, $9, $10, now()
)
ON CONFLICT (member_id) DO UPDATE SET
    role           = EXCLUDED.role,
    shards         = EXCLUDED.shards,
    config         = EXCLUDED.config,
    in_flight      = EXCLUDED.in_flight,
    workers        = EXCLUDED.workers,
    version        = EXCLUDED.version,
    hostname       = EXCLUDED.hostname,
    pid            = EXCLUDED.pid,
    last_heartbeat = now()
`

type UpsertClusterMemberParams struct {
	MemberID  string                    `json:"member_id"`
	Role      string                    `json:"role"`
	Column3   pgtype.Range[pgtype.Int4] `json:"column_3"`
	Config    json.RawMessage           `json:"config"`
	InFlight  int32                     `json:"in_flight"`
	Column6   json.RawMessage           `json:"column_6"`
	Version   string                    `json:"version"`
	Hostname  string                    `json:"hostname"`
	Pid       int32                     `json:"pid"`
	StartedAt pgtype.Timestamptz        `json:"started_at"`
}

// Go-side wrappers for the cluster_members running-fleet registry.
//
// The shards column is an int4range; sqlc has no Go mapping for it, so we
// cast it to/from text at the query boundary (`$N::int4range` on write,
// `shards::text` on read) and the store wrapper owns the [lo,hi] <-> [lo,hi+1)
// conversion — the same "store does the typed conversion" pattern as
// shardBounds. That keeps internal/dbq free of any int4range type.
// One cheap PK UPSERT per ~30s beat. last_heartbeat is stamped now() in SQL
// (DB clock, never an app timestamp) so liveness is skew-free; started_at is
// written on INSERT only — the DO UPDATE deliberately omits it so uptime is
// stable across beats. Every other field is refreshed: in_flight + workers are
// the LIVE per-beat state (a broker's claimed-task count + its connected-worker
// snapshot); config/version/identity are static-but-cheap to re-set.
func (q *Queries) UpsertClusterMember(ctx context.Context, arg UpsertClusterMemberParams) error {
	_, err := q.db.Exec(ctx, upsertClusterMember,
		arg.MemberID,
		arg.Role,
		arg.Column3,
		arg.Config,
		arg.InFlight,
		arg.Column6,
		arg.Version,
		arg.Hostname,
		arg.Pid,
		arg.StartedAt,
	)
	return err
}
