// Hand-written queries that sqlc 1.31 can't parse. NOT regenerated by
// `just sqlc` — edit this file directly.
//
// Postgres' multi-arg unnest($1::text[], $2::text[], …) form is the
// natural way to bulk-insert N parallel arrays in one statement; sqlc's
// parser stumbles on it and reports `function unnest(unknown, …) does
// not exist`, even though Postgres accepts it without complaint. The
// store package wraps these constants with typed Go helpers.

package dbq

// name/labels live in resource_meta, the resources row holds spec inline +
// status/etc., so a child write is TWO inserts (resources row + meta row).
// The caller resolves new-vs-existing in Go (the composer diff already holds
// existing ids), so each side is a clean id-keyed bulk statement. Composed
// children carry spec INLINE and are NOT versioned (no spec_versions write):
// children are re-derived every compose and have no rollback history.

// InsertChildrenHotSQL: bulk-insert the hot resources rows for NEW
// children. ids are generated by the caller (so the matching meta rows
// reference them) and passed in. owner_id/root_id are constant per
// compose. kind stays on the hot row (work-queue claim + hot queries
// filter by it).
//
// manifest_version is stamped here from each child's kind_config (write-cold:
// once per child at compose, inside the one bulk-insert tx) so the repeated
// schedule/cascade path later reads it off the resources row with NO join.
// LEFT JOIN + COALESCE 0 keeps a child of a not-yet-applied kind inert.
const InsertChildrenHotSQL = `
INSERT INTO resources (id, owner_id, root_id, kind, kind_version, spec, manifest_version)
SELECT t.i, $2, $3, t.k, t.mj, t.s, COALESCE(kc.manifest_version, 0)
FROM unnest($1::uuid[], $4::text[], $5::jsonb[], $6::int[]) AS t(i, k, s, mj)
LEFT JOIN kind_config kc ON kc.kind = t.k AND kc.kind_version = t.mj`

// InsertChildrenMetaSQL: bulk-insert the matching resource_meta rows for
// NEW children. (kind,name) uniqueness is enforced here; a cross-owner name
// collision (which a well-behaved composer avoids by prefixing child names with
// something root-unique) would raise a unique violation, surfacing loudly rather
// than silently reparenting.
const InsertChildrenMetaSQL = `
INSERT INTO resource_meta (id, kind, name, labels)
SELECT i, k, n, l
FROM unnest($1::uuid[], $2::text[], $3::text[], $4::jsonb[]) AS t(i, k, n, l)`

// UpdateChildrenHotSQL: bulk-update spec + kind_version INLINE for EXISTING children by
// id — including the composer-driven KIND-VERSION FLIP (a versioned composer
// upgrading a v1 child to v2 on the SAME uuid). Bumps generation explicitly; the
// gate fires when spec OR kind_version changed, so a v1→v2 conversion with an
// identical spec still flips + bumps + re-reconciles. On a kind_version change the
// manifest_version is RE-STAMPED from the NEW (kind, kind_version) kind_config so the
// fence tracks the new manifest; a same-kind_version spec-only change keeps the
// existing manifest_version untouched (COALESCE to r.manifest_version).
//
// Orphan-grace re-adoption is handled path-independently in the composer, not here:
// ApplyComposeResult collects every re-emitted child that is currently orphaned and
// clears its marks via ClearOrphanMarksSQL, regardless of whether spec/labels/nothing
// changed (a spec-DISTINCT-FROM gate would miss a labels-only re-emit and leave such
// a child stuck Orphaned). So this UPDATE only touches spec/kind_version/generation.
//
// TEARDOWN GUARD: `deletion_requested_at IS NULL` — never rewrite the spec of (or
// flip the kind_version of) a child that is mid-teardown (soft-delete requested, a
// finalizer running). A recompose that re-emits a draining child must not silently
// resurrect it by mutating its spec underneath the running Deleter; the child rides
// its deletion lifecycle to completion (and is re-created fresh if still produced).
// A frozen_until (orphan-grace) child is deliberately NOT excluded here: the
// composer's ClearOrphanMarks re-adopts it in the same tx, and a re-emitted orphan
// that also changed spec/version must still take that change — so orphan re-adoption
// stays path-independent, while an actively-draining child is left alone.
const UpdateChildrenHotSQL = `
UPDATE resources r
SET spec = t.s,
    kind_version = t.mj,
    manifest_version = CASE
        WHEN r.kind_version IS DISTINCT FROM t.mj
        THEN COALESCE((SELECT kc.manifest_version FROM kind_config kc
                        WHERE kc.kind = r.kind AND kc.kind_version = t.mj), 0)
        ELSE r.manifest_version
    END,
    generation = r.generation + 1,
    updated_at = now()
FROM unnest($1::uuid[], $2::jsonb[], $3::int[]) AS t(i, s, mj)
WHERE r.id = t.i AND r.deletion_requested_at IS NULL
  AND (r.spec IS DISTINCT FROM t.s OR r.kind_version IS DISTINCT FROM t.mj)`

// UpdateChildrenMetaSQL: bulk-update labels for EXISTING children by id,
// gated so unchanged labels don't churn the meta row.
const UpdateChildrenMetaSQL = `
UPDATE resource_meta m
SET labels = t.l
FROM unnest($1::uuid[], $2::jsonb[]) AS t(i, l)
WHERE m.id = t.i AND m.labels IS DISTINCT FROM t.l`

// BatchUpsertResourceDepsSQL: bulk-upsert dep edges with their
// value_flows. ON CONFLICT DO UPDATE so a recompose that CHANGES an edge's
// flows (added/removed/retargeted a value flow) takes effect, gated by
// IS DISTINCT FROM so an unchanged edge is a no-op write (no churn).
// value_flows is the only mutable column; the (dependent, dependency)
// pair is the identity. There is no per-flow substituted flag: the
// dep-gate (`p.synced_gen < p.generation`) closes the bootstrap window,
// and the substitute pass inside drain_outbox_batch re-fills flows on
// demand.
const BatchUpsertResourceDepsSQL = `
INSERT INTO resource_deps (dependent_id, dependency_id, value_flows)
SELECT dep, dcy, COALESCE(flows, '[]'::jsonb)
FROM unnest($1::uuid[], $2::uuid[], $3::jsonb[]) AS d(dep, dcy, flows)
ON CONFLICT (dependent_id, dependency_id) DO UPDATE
    SET value_flows = EXCLUDED.value_flows
    WHERE resource_deps.value_flows IS DISTINCT FROM EXCLUDED.value_flows`

// ListExistingDepsByOwnerSQL: every edge whose DEPENDENT is a child of
// this parent, with its current value_flows — the set the composer diffs
// against. The composer only ever emits edges between this parent's
// children, so scoping on the dependent's owner_id captures exactly the
// produced set's universe (and lets us prune edges the compose no longer
// emits).
const ListExistingDepsByOwnerSQL = `
SELECT d.dependent_id, d.dependency_id, d.value_flows
FROM resource_deps d
JOIN resources r ON r.id = d.dependent_id
WHERE r.owner_id = $1`

// DeleteResourceDepsSQL: bulk-delete edges by (dependent, dependency)
// pair. Used by the composer to prune edges the latest compose no longer
// emits (the edge analogue of DeleteChildrenSQL). Paired arrays so one
// statement removes the whole stale set.
const DeleteResourceDepsSQL = `
DELETE FROM resource_deps d
USING unnest($1::uuid[], $2::uuid[]) AS s(dep, dcy)
WHERE d.dependent_id = s.dep AND d.dependency_id = s.dcy`

// DeleteChildrenSQL: bulk-delete child rows by id. Used by composer to
// remove children that vanished from the latest compose output —
// vanished children are hard-deleted, and ON DELETE CASCADE on
// owner_id propagates to any downstream rows the child itself owned.
const DeleteChildrenSQL = `
DELETE FROM resources WHERE id = ANY($1::uuid[])`

// MarkChildrenOrphanedSQL: stamp the orphan-grace mark on children the latest
// compose no longer produces, for kinds with orphan_grace_secs > 0 — instead of
// deleting them. frozen_until = now() + the kind's grace baked in-DB (g seconds
// per row, since kinds may differ) is BOTH the phase='Orphaned' signal and the
// reaper's sweep_expired_orphans absolute teardown deadline — the same column
// that holds the 'infinity' quarantine sentinel. Guarded `deletion_requested_at
// IS NULL AND frozen_until IS NULL` (the single live-row freeze predicate used
// everywhere): so a child already draining is never pulled back into grace, a
// QUARANTINED child ('infinity') the composer also drops is NOT silently
// un-quarantined, AND an already-ORPHANED child (finite) is NOT re-stamped — its
// original absolute deadline is preserved (re-stamping would slide the teardown
// forward every recompose). Paired arrays (id, grace_secs); the composer pre-sorts
// ids ascending to keep the project's ascending-id lock discipline (avoids
// deadlock with the cascade trigger).
const MarkChildrenOrphanedSQL = `
UPDATE resources r
SET frozen_until = now() + make_interval(secs => t.g),
    updated_at = now()
FROM unnest($1::uuid[], $2::int[]) AS t(i, g)
WHERE r.id = t.i AND r.deletion_requested_at IS NULL
  AND r.frozen_until IS NULL`

// ClearOrphanMarksSQL: cancel the orphan-grace mark on re-adopted children —
// a compose that re-emits a previously-dropped child re-adopts it. Gated
// `frozen_until IS NOT NULL AND frozen_until <> 'infinity'` so it (a) is a cheap
// no-op for the overwhelmingly common never-orphaned child, and (b) clears ONLY a
// FINITE orphan-grace mark — a re-emit must NOT un-quarantine a child the operator
// set aside ('infinity'); only an explicit un-quarantine lifts that. Handles the
// UNCHANGED-spec re-adopt that UpdateChildrenHotSQL's IS-DISTINCT-FROM gate skips;
// deliberately does NOT bump generation (re-adopting an unchanged child must not
// churn it). Returns the count via the store wrapper's CommandTag.
const ClearOrphanMarksSQL = `
UPDATE resources
SET frozen_until = NULL, updated_at = now()
WHERE id = ANY($1::uuid[]) AND frozen_until IS NOT NULL AND frozen_until <> 'infinity'`

// BatchUpsertProviderConfigsSQL: bulk-upsert the provider configs ONE
// composer emits, all owned by $1 (the composing root). The Go diff only
// ships the delta (new + changed), so this is small. ON CONFLICT (name)
// is OWNER-GUARDED — `providerconfigs.owner_id IS NOT DISTINCT FROM
// EXCLUDED.owner_id` — so a composer can never steal/clobber a config
// owned by a DIFFERENT root or a user/API config (owner_id NULL); such a
// name collision silently no-ops (the composer is expected to name its
// configs uniquely, e.g. prefixed by the root, exactly like children).
// owner_id is not in the UPDATE SET: the guard already pins it equal.
const BatchUpsertProviderConfigsSQL = `
INSERT INTO providerconfigs (owner_id, name, kind, is_default, spec, kind_version)
SELECT $1, n, k, d, s, mj
FROM unnest($2::text[], $3::text[], $4::bool[], $5::jsonb[], $6::int[]) AS t(n, k, d, s, mj)
ON CONFLICT (name) DO UPDATE
    SET kind       = EXCLUDED.kind,
        kind_version      = EXCLUDED.kind_version,
        is_default = EXCLUDED.is_default,
        spec       = EXCLUDED.spec,
        updated_at = now()
    WHERE providerconfigs.owner_id IS NOT DISTINCT FROM EXCLUDED.owner_id`

// DeleteProviderConfigsSQL: bulk-delete provider-config rows by id — the
// config analogue of DeleteChildrenSQL. Used by the composer to prune
// configs the latest compose no longer emits. ON DELETE SET NULL on
// resources.provider_config_id demotes any consumers back to the kind
// default.
const DeleteProviderConfigsSQL = `
DELETE FROM providerconfigs WHERE id = ANY($1::uuid[])`

// ArmScheduleRecheckSQL: bulk-insert composed children into schedule_recheck so
// the drainer schedules them (deferred, paced with drains) instead of a single
// deadlock-prone post-commit ScheduleEligible. Committed in the compose tx →
// atomic with the children, so the schedule wake can never be lost. shard_id is
// computed per-row via shard_of so the drainer's BETWEEN-band claim prunes it.
// ON CONFLICT DO NOTHING keeps a re-arm (recompose) idempotent.
const ArmScheduleRecheckSQL = `
INSERT INTO schedule_recheck (resource_id, shard_id)
SELECT id, shard_of(id) FROM unnest($1::uuid[]) AS t(id)
ON CONFLICT (resource_id) DO NOTHING`
