// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendResourceEvent = `-- name: AppendResourceEvent :exec

INSERT INTO resource_events (resource_id, type, actor, reason, message, detail, created_at)
VALUES ($1, $2, $3, $4, $5, $6, clock_timestamp())
`

type AppendResourceEventParams struct {
	ResourceID uuid.UUID       `json:"resource_id"`
	Type       string          `json:"type"`
	Actor      *string         `json:"actor"`
	Reason     *string         `json:"reason"`
	Message    *string         `json:"message"`
	Detail     json.RawMessage `json:"detail"`
}

// Resource event queries. The K8s "Events" API analogue: append-only
// audit log, queried by resource id (newest first) for the UI's
// Events tab.
// created_at uses clock_timestamp() (REAL wall-clock at INSERT), not the column's
// DEFAULT now() (= TRANSACTION-START time). An event emitted inside a long tx —
// e.g. compose-succeeded, written mid-way through a 1M-child compose tx that runs
// ~1 min before it commits — would otherwise be stamped at the tx's start and only
// become visible on commit: it appears ~1 min late AND with a timestamp ~1 min
// behind wall-clock (the UI's "spec-composed shows up a minute later with the wrong
// time" bug). clock_timestamp() records when the row was actually written.
func (q *Queries) AppendResourceEvent(ctx context.Context, arg AppendResourceEventParams) error {
	_, err := q.db.Exec(ctx, appendResourceEvent,
		arg.ResourceID,
		arg.Type,
		arg.Actor,
		arg.Reason,
		arg.Message,
		arg.Detail,
	)
	return err
}

const listResourceEvents = `-- name: ListResourceEvents :many
SELECT id, resource_id, type, actor, reason, message, detail, created_at
FROM resource_events
WHERE resource_id = $1
  AND (
        $2::timestamptz = '0001-01-01 00:00:00+00'::timestamptz
     OR (created_at, id) < ($2::timestamptz, $3::bigint)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListResourceEventsParams struct {
	ResourceID uuid.UUID          `json:"resource_id"`
	CursorAt   pgtype.Timestamptz `json:"cursor_at"`
	CursorID   int64              `json:"cursor_id"`
	Lim        int32              `json:"lim"`
}

// Newest events first, paginated via (created_at, id) cursor.
// Empty cursor (zero time / zero id) means "from the top."
func (q *Queries) ListResourceEvents(ctx context.Context, arg ListResourceEventsParams) ([]ResourceEvent, error) {
	rows, err := q.db.Query(ctx, listResourceEvents,
		arg.ResourceID,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceEvent
	for rows.Next() {
		var i ResourceEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Type,
			&i.Actor,
			&i.Reason,
			&i.Message,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
