// Hand-written kind_version-flip query. NOT regenerated by `just sqlc` — edit directly.
//
// The uuid-stable kind_version flip: a breaking web-API kind_version bump is a spec
// REWRITE by the author, applied IN PLACE on the same uuid so value-flows
// (resource_deps, uuid-keyed) survive and the composer's refKey{kind,name} is
// unchanged — no orphan-teardown of live infra. Kept out of the sqlc query set
// because the multi-guard idempotent UPDATE + the (kind, kind_version)
// manifest_version re-stamp read is clearer hand-written, and it pairs with the
// reject-on-schema-fail gate enforced app-side before this runs.

package dbq

// FlipResourceKindVersionSQL flips ONE resource to a new kind_version with a rewritten spec,
// idempotently. The `kind_version = @old_kind_version` guard makes a redelivered flip a no-op
// (an already-flipped row matches nothing), and bumps generation so the row
// re-reconciles under the new kind_version's reactions/schema. manifest_version is
// re-stamped from the TARGET (kind, kind_version) kind_config so the in-flight fence
// tracks the new manifest; COALESCE 0 keeps it inert if the new kind_version has no
// manifest yet. Returns the row id when the flip applied (0 rows = already
// flipped / wrong old kind_version / gone).
//
// Args: $1 = resource id (uuid), $2 = old kind_version (int), $3 = new kind_version (int),
//
//	$4 = new spec (jsonb).
//
// $2/$3 are cast EXPLICITLY per use site: resources.kind_version is SMALLINT (the churn
// table narrows it), kind_config.kind_version is INT. Without the casts Postgres tries to
// deduce ONE type for a param used against both and errors 42P08 ("inconsistent
// types deduced for parameter"). $2::smallint / $3::smallint match the resources
// column; the kind_config subquery compares $3::int.
const FlipResourceKindVersionSQL = `
UPDATE resources r
   SET kind_version = $3::smallint,
       spec = $4,
       manifest_version = COALESCE(
           (SELECT kc.manifest_version FROM kind_config kc
             WHERE kc.kind = r.kind AND kc.kind_version = $3::int), 0),
       generation = r.generation + 1,
       updated_at = now()
 WHERE r.id = $1
   AND r.kind_version = $2::smallint
   AND r.deletion_requested_at IS NULL   -- never flip a resource mid-teardown
   AND r.frozen_until IS NULL            -- never flip a quarantined/orphaned row
RETURNING r.id`

// FlipSkewEdgesSQL lists value-flow edges whose UPSTREAM is the just-flipped
// resource but whose recorded src_kind_version no longer matches the resource's new
// kind_version — the skew signal. Each such edge's src_field pointer was validated
// against the upstream's prior kind_version; after a rename/relocate across the
// kind_version it may silently resolve NULL. The caller WARNs (operator-visible)
// per returned edge so a stale value-flow surfaces instead of a silent stale value.
// src_kind_version = 0 (never validated) is treated as "no known skew" and excluded.
//
// Args: $1 = the flipped (upstream) resource id, $2 = its new kind_version.
const FlipSkewEdgesSQL = `
SELECT d.dependent_id, d.dependency_id, d.src_kind_version
  FROM resource_deps d
 WHERE d.dependency_id = $1
   AND d.src_kind_version <> 0
   AND d.src_kind_version <> $2`

// RecordEdgeSrcKindVersionSQL stamps src_kind_version on every value-flow edge whose upstream
// is the given resource, so subsequent flips can detect skew against a known
// baseline. It is called ONLY from FlipResourceKindVersion — at flip time, with the
// NEW kind_version — never on a plain apply/compose settle. Freshly-created edges keep
// the src_kind_version = 0 sentinel ("no recorded baseline") until the upstream is
// first flipped; consequently the FIRST flip of an upstream records the baseline but
// cannot itself detect skew (FlipSkewEdgesSQL excludes src_kind_version = 0), and skew
// detection kicks in only from the SECOND flip onward. This is the sentinel design:
// 0 means "no known skew", not "version 0".
//
// Args: $1 = the upstream resource id, $2 = its current (post-flip) kind_version.
const RecordEdgeSrcKindVersionSQL = `
UPDATE resource_deps d
   SET src_kind_version = $2
 WHERE d.dependency_id = $1
   AND d.src_kind_version IS DISTINCT FROM $2`
