// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manifest.sql

package dbq

import (
	"context"
	"encoding/json"

	model "github.com/salesforce/converge/internal/model"
)

const batchKindPolicy = `-- name: BatchKindPolicy :many
SELECT kc.kind, kc.kind_version, kc.orphan_grace_secs, kc.finalizer_name
FROM kind_config kc
WHERE kc.kind = ANY($1::text[])
`

type BatchKindPolicyRow struct {
	Kind            string  `json:"kind"`
	KindVersion     int32   `json:"kind_version"`
	OrphanGraceSecs int32   `json:"orphan_grace_secs"`
	FinalizerName   *string `json:"finalizer_name"`
}

// Batch-reads (kind, kind_version, orphan_grace_secs, finalizer_name) for a set of kinds
// in ONE query — the composer's orphan-prune loop uses this to build an in-memory
// (kind, kind_version) → policy map BEFORE the per-child loop, so the grace/finalizer
// lookup never becomes N per-child DB round-trips at 1M children. Returns EVERY
// kind_version of each requested kind (a handful of rows per kind); the composer indexes
// the map by the child's concrete (kind, kind_version). Reads kind_config (the policy
// table the manifest derives into).
func (q *Queries) BatchKindPolicy(ctx context.Context, dollar_1 []string) ([]BatchKindPolicyRow, error) {
	rows, err := q.db.Query(ctx, batchKindPolicy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchKindPolicyRow
	for rows.Next() {
		var i BatchKindPolicyRow
		if err := rows.Scan(
			&i.Kind,
			&i.KindVersion,
			&i.OrphanGraceSecs,
			&i.FinalizerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteKindConfig = `-- name: DeleteKindConfig :execrows
DELETE FROM kind_config
WHERE kind = $1 AND kind_version = $2::smallint
`

type DeleteKindConfigParams struct {
	Kind        string `json:"kind"`
	KindVersion int16  `json:"kind_version"`
}

// Deletes the (kind, kind_version) operational-config row alongside the manifest
// (kind_config is derived from the manifest and joined by value, not FK, so it is
// removed explicitly). Returns the row count (0 if none — idempotent).
func (q *Queries) DeleteKindConfig(ctx context.Context, arg DeleteKindConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKindConfig, arg.Kind, arg.KindVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteKindManifest = `-- name: DeleteKindManifest :execrows
DELETE FROM kind_manifest
WHERE kind = $1 AND kind_version = $2::smallint
`

type DeleteKindManifestParams struct {
	Kind        string `json:"kind"`
	KindVersion int16  `json:"kind_version"`
}

// Deletes the (kind, kind_version) manifest row. The AFTER DELETE trigger fires the
// kind_manifest_changed NOTIFY so caches drop the pair. Returns the row count (0 =
// nothing there → the API maps it to 404, idempotent). Blocking checks + the paired
// kind_config/providerconfigs deletes are enforced by store.DeleteKindManifest in one
// transaction; this is the final statement.
func (q *Queries) DeleteKindManifest(ctx context.Context, arg DeleteKindManifestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKindManifest, arg.Kind, arg.KindVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProviderConfigsAtKindVersion = `-- name: DeleteProviderConfigsAtKindVersion :execrows
DELETE FROM providerconfigs
WHERE kind = $1 AND kind_version = $2::smallint
`

type DeleteProviderConfigsAtKindVersionParams struct {
	Kind        string `json:"kind"`
	KindVersion int16  `json:"kind_version"`
}

// Cascade-deletes every provider config at a (kind, kind_version) as part of the
// manifest delete — once no resource references the version, its configs (which only
// ever serve resources of their own (kind, kind_version)) are dead. Runs in the same
// transaction as the manifest/config delete. Returns the row count deleted.
func (q *Queries) DeleteProviderConfigsAtKindVersion(ctx context.Context, arg DeleteProviderConfigsAtKindVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderConfigsAtKindVersion, arg.Kind, arg.KindVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKindManifest = `-- name: GetKindManifest :one
SELECT kind, kind_version, description, spec_schema, status_schema, config_schema,
       reactions, finalizer_name, max_inflight, task_deadline_secs, resync_interval_secs,
       resync_recomposes, orphan_grace_secs, max_transient_attempts, retired, schema_hash, manifest_version, created_at, updated_at
FROM kind_manifest WHERE kind = $1 AND kind_version = $2::int
`

type GetKindManifestParams struct {
	Kind        string `json:"kind"`
	KindVersion int32  `json:"kind_version"`
}

// Reads one (kind, kind_version) manifest (API/UI, KindManifestCache miss-fill). OFF the hot
// path. PK probe on (kind, kind_version).
func (q *Queries) GetKindManifest(ctx context.Context, arg GetKindManifestParams) (KindManifest, error) {
	row := q.db.QueryRow(ctx, getKindManifest, arg.Kind, arg.KindVersion)
	var i KindManifest
	err := row.Scan(
		&i.Kind,
		&i.KindVersion,
		&i.Description,
		&i.SpecSchema,
		&i.StatusSchema,
		&i.ConfigSchema,
		&i.Reactions,
		&i.FinalizerName,
		&i.MaxInflight,
		&i.TaskDeadlineSecs,
		&i.ResyncIntervalSecs,
		&i.ResyncRecomposes,
		&i.OrphanGraceSecs,
		&i.MaxTransientAttempts,
		&i.Retired,
		&i.SchemaHash,
		&i.ManifestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKindSchemaHash = `-- name: GetKindSchemaHash :one
SELECT schema_hash, manifest_version FROM kind_manifest WHERE kind = $1 AND kind_version = $2::int
`

type GetKindSchemaHashParams struct {
	Kind        string `json:"kind"`
	KindVersion int32  `json:"kind_version"`
}

type GetKindSchemaHashRow struct {
	SchemaHash      *string `json:"schema_hash"`
	ManifestVersion int64   `json:"manifest_version"`
}

// Reads the stored schema hash + content-hash for a (kind, kind_version) — the
// publish-time (kind, kind_version)→content-hash invariant gate compares an incoming
// manifest against these before allowing an in-place same-kind_version overwrite. Cheap
// PK probe.
func (q *Queries) GetKindSchemaHash(ctx context.Context, arg GetKindSchemaHashParams) (GetKindSchemaHashRow, error) {
	row := q.db.QueryRow(ctx, getKindSchemaHash, arg.Kind, arg.KindVersion)
	var i GetKindSchemaHashRow
	err := row.Scan(&i.SchemaHash, &i.ManifestVersion)
	return i, err
}

const kindVersionHasResources = `-- name: KindVersionHasResources :one
SELECT EXISTS (
    SELECT 1 FROM resources
    WHERE kind = $1 AND kind_version = $2::smallint
)
`

type KindVersionHasResourcesParams struct {
	Kind        model.Kind `json:"kind"`
	KindVersion int16      `json:"kind_version"`
}

// Existence check (NOT a count): is ANY resource pinned to this (kind, kind_version)?
// The FIRST delete-guard for DeleteKindManifest. EXISTS short-circuits at the first
// matching row (the kind-leading index locates it) instead of scanning + counting
// every match — we only need >0-or-0, never the tally. INCLUDES soft-deleting/draining
// rows (deletion_requested_at set): a version still tearing anything down is NOT
// deletable. Off every hot path (operator delete only).
func (q *Queries) KindVersionHasResources(ctx context.Context, arg KindVersionHasResourcesParams) (bool, error) {
	row := q.db.QueryRow(ctx, kindVersionHasResources, arg.Kind, arg.KindVersion)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const kindVersionPinnedByBinding = `-- name: KindVersionPinnedByBinding :one
SELECT EXISTS (
    SELECT 1 FROM reactor_bindings
    WHERE (watch_kind = $1 AND watch_kind_version = $2::smallint)
       OR (reactor    = $1 AND reactor_version    = $2::smallint)
)
`

type KindVersionPinnedByBindingParams struct {
	WatchKind   string `json:"watch_kind"`
	KindVersion int16  `json:"kind_version"`
}

// Existence check (NOT a count): is this (kind, kind_version) EXACTLY pinned by any
// reactor binding — either as the WATCHED kind (watch_kind_version = V) or as the
// REACTOR that runs (reactor_version = V)? The SECOND delete-guard. EXISTS
// short-circuits at the first match. An UNPINNED binding (NULL watch/reactor version)
// is deliberately NOT matched: it resolves to the remaining versions, so dropping one
// version never strands it. Off the hot path.
func (q *Queries) KindVersionPinnedByBinding(ctx context.Context, arg KindVersionPinnedByBindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, kindVersionPinnedByBinding, arg.WatchKind, arg.KindVersion)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listKindManifests = `-- name: ListKindManifests :many
SELECT kind, kind_version, description, spec_schema, status_schema, config_schema,
       reactions, finalizer_name, max_inflight, task_deadline_secs, resync_interval_secs,
       resync_recomposes, orphan_grace_secs, max_transient_attempts, retired, schema_hash, manifest_version, created_at, updated_at
FROM kind_manifest ORDER BY kind, kind_version
`

// Reads every manifest across all (kind, kind_version) (KindManifestCache full load at boot +
// failsafe re-read, API list, schema-validator rebuild). OFF the hot path.
func (q *Queries) ListKindManifests(ctx context.Context) ([]KindManifest, error) {
	rows, err := q.db.Query(ctx, listKindManifests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KindManifest
	for rows.Next() {
		var i KindManifest
		if err := rows.Scan(
			&i.Kind,
			&i.KindVersion,
			&i.Description,
			&i.SpecSchema,
			&i.StatusSchema,
			&i.ConfigSchema,
			&i.Reactions,
			&i.FinalizerName,
			&i.MaxInflight,
			&i.TaskDeadlineSecs,
			&i.ResyncIntervalSecs,
			&i.ResyncRecomposes,
			&i.OrphanGraceSecs,
			&i.MaxTransientAttempts,
			&i.Retired,
			&i.SchemaHash,
			&i.ManifestVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKindManifest = `-- name: UpsertKindManifest :exec
INSERT INTO kind_manifest (
    kind, kind_version, description, spec_schema, status_schema, config_schema,
    reactions, finalizer_name, max_inflight, task_deadline_secs, resync_interval_secs,
    resync_recomposes, orphan_grace_secs, max_transient_attempts, retired, schema_hash, manifest_version, updated_at
) VALUES (
    $1, $3::int, $2,
    $4::jsonb, $5::jsonb, $6::jsonb,
    $7::jsonb, $8::text,
    $9::int, $10::int, $11::int,
    $12::boolean, $13::int, $14::int,
    $15::boolean, $16::text, $17::bigint, now()
)
ON CONFLICT (kind, kind_version) DO UPDATE SET
    description          = EXCLUDED.description,
    spec_schema          = EXCLUDED.spec_schema,
    status_schema        = EXCLUDED.status_schema,
    config_schema        = EXCLUDED.config_schema,
    reactions            = EXCLUDED.reactions,
    finalizer_name       = EXCLUDED.finalizer_name,
    max_inflight         = EXCLUDED.max_inflight,
    task_deadline_secs   = EXCLUDED.task_deadline_secs,
    resync_interval_secs = EXCLUDED.resync_interval_secs,
    resync_recomposes    = EXCLUDED.resync_recomposes,
    orphan_grace_secs    = EXCLUDED.orphan_grace_secs,
    max_transient_attempts = EXCLUDED.max_transient_attempts,
    retired              = EXCLUDED.retired,
    schema_hash          = EXCLUDED.schema_hash,
    manifest_version     = EXCLUDED.manifest_version,
    updated_at           = now()
`

type UpsertKindManifestParams struct {
	Kind                 string          `json:"kind"`
	Description          *string         `json:"description"`
	KindVersion          int32           `json:"kind_version"`
	SpecSchema           []byte          `json:"spec_schema"`
	StatusSchema         []byte          `json:"status_schema"`
	ConfigSchema         []byte          `json:"config_schema"`
	Reactions            json.RawMessage `json:"reactions"`
	FinalizerName        *string         `json:"finalizer_name"`
	MaxInflight          int32           `json:"max_inflight"`
	TaskDeadlineSecs     int32           `json:"task_deadline_secs"`
	ResyncIntervalSecs   int32           `json:"resync_interval_secs"`
	ResyncRecomposes     bool            `json:"resync_recomposes"`
	OrphanGraceSecs      int32           `json:"orphan_grace_secs"`
	MaxTransientAttempts int32           `json:"max_transient_attempts"`
	Retired              bool            `json:"retired"`
	SchemaHash           *string         `json:"schema_hash"`
	ManifestVersion      int64           `json:"manifest_version"`
}

// Operator-applied (CRD-style) kind definition, per (kind, kind_version). Inserts or
// replaces the manifest row for THIS kind_version; the AFTER trigger
// sync_kind_config_from_manifest derives the (kind, kind_version) kind_config policy row
// and scopes its resource restamp to kind_version. Publishing a NEW kind_version inserts a new
// row and touches no existing-kind_version resource. (Reactor wiring is NOT projected
// from the manifest — it's a separate editable reactor_bindings subscription.)
// validate_kind_manifest() runs in the config trigger and RAISEs on an illegal
// reaction set, rolling back the apply. manifest_version is the caller-computed
// content hash (reactions+schemas); the publish-time (kind, kind_version)→content-hash
// invariant is enforced app-side (handlers_kind_manifest) BEFORE this upsert.
func (q *Queries) UpsertKindManifest(ctx context.Context, arg UpsertKindManifestParams) error {
	_, err := q.db.Exec(ctx, upsertKindManifest,
		arg.Kind,
		arg.Description,
		arg.KindVersion,
		arg.SpecSchema,
		arg.StatusSchema,
		arg.ConfigSchema,
		arg.Reactions,
		arg.FinalizerName,
		arg.MaxInflight,
		arg.TaskDeadlineSecs,
		arg.ResyncIntervalSecs,
		arg.ResyncRecomposes,
		arg.OrphanGraceSecs,
		arg.MaxTransientAttempts,
		arg.Retired,
		arg.SchemaHash,
		arg.ManifestVersion,
	)
	return err
}
