// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/salesforce/converge/internal/model"
)

type TaskType string

const (
	TaskTypeReconcile TaskType = "reconcile"
	TaskTypeDelete    TaskType = "delete"
	TaskTypeOperate   TaskType = "operate"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType `json:"task_type"`
	Valid    bool     `json:"valid"` // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type ClusterMember struct {
	MemberID      string                    `json:"member_id"`
	Role          string                    `json:"role"`
	Shards        pgtype.Range[pgtype.Int4] `json:"shards"`
	Config        json.RawMessage           `json:"config"`
	InFlight      int32                     `json:"in_flight"`
	Workers       json.RawMessage           `json:"workers"`
	Version       string                    `json:"version"`
	Hostname      string                    `json:"hostname"`
	Pid           int32                     `json:"pid"`
	StartedAt     pgtype.Timestamptz        `json:"started_at"`
	LastHeartbeat pgtype.Timestamptz        `json:"last_heartbeat"`
}

type KindConfig struct {
	Kind                 string  `json:"kind"`
	KindVersion          int32   `json:"kind_version"`
	MaxInflight          int32   `json:"max_inflight"`
	TaskDeadlineSecs     int32   `json:"task_deadline_secs"`
	ResyncIntervalSecs   int32   `json:"resync_interval_secs"`
	ResyncRecomposes     bool    `json:"resync_recomposes"`
	OrphanGraceSecs      int32   `json:"orphan_grace_secs"`
	FinalizerName        *string `json:"finalizer_name"`
	MaxTransientAttempts int32   `json:"max_transient_attempts"`
	Retired              bool    `json:"retired"`
	ManifestVersion      int64   `json:"manifest_version"`
}

type KindInflight struct {
	Kind        string             `json:"kind"`
	KindVersion int32              `json:"kind_version"`
	RangeLo     int16              `json:"range_lo"`
	InFlight    int32              `json:"in_flight"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
}

type KindManifest struct {
	Kind                 string             `json:"kind"`
	KindVersion          int32              `json:"kind_version"`
	Description          *string            `json:"description"`
	SpecSchema           []byte             `json:"spec_schema"`
	StatusSchema         []byte             `json:"status_schema"`
	ConfigSchema         []byte             `json:"config_schema"`
	Reactions            json.RawMessage    `json:"reactions"`
	FinalizerName        *string            `json:"finalizer_name"`
	MaxInflight          int32              `json:"max_inflight"`
	TaskDeadlineSecs     int32              `json:"task_deadline_secs"`
	ResyncIntervalSecs   int32              `json:"resync_interval_secs"`
	ResyncRecomposes     bool               `json:"resync_recomposes"`
	OrphanGraceSecs      int32              `json:"orphan_grace_secs"`
	MaxTransientAttempts int32              `json:"max_transient_attempts"`
	Retired              bool               `json:"retired"`
	SchemaHash           *string            `json:"schema_hash"`
	ManifestVersion      int64              `json:"manifest_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type LifecycleOutbox struct {
	ResourceID  uuid.UUID          `json:"resource_id"`
	Kind        string             `json:"kind"`
	Transition  string             `json:"transition"`
	Generation  int64              `json:"generation"`
	BindingName string             `json:"binding_name"`
	BrokerID    *string            `json:"broker_id"`
	HeartbeatAt pgtype.Timestamptz `json:"heartbeat_at"`
	ClaimEpoch  int64              `json:"claim_epoch"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ShardID     int16              `json:"shard_id"`
}

type Providerconfig struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	KindVersion int16              `json:"kind_version"`
	IsDefault   bool               `json:"is_default"`
	Spec        json.RawMessage    `json:"spec"`
	Data        []byte             `json:"data"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ReactorBinding struct {
	Name             string             `json:"name"`
	WatchKind        string             `json:"watch_kind"`
	WatchKindVersion *int16             `json:"watch_kind_version"`
	Transition       string             `json:"transition"`
	LabelMatch       json.RawMessage    `json:"label_match"`
	Reactor          string             `json:"reactor"`
	ReactorVersion   *int16             `json:"reactor_version"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Resource struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	KindVersion         int16              `json:"kind_version"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	RootID              pgtype.UUID        `json:"root_id"`
	Spec                json.RawMessage    `json:"spec"`
	Status              []byte             `json:"status"`
	ProviderConfigID    pgtype.UUID        `json:"provider_config_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	HealthOk            bool               `json:"health_ok"`
	ComposedGen         int64              `json:"composed_gen"`
	ManifestVersion     int64              `json:"manifest_version"`
	FailureGen          int64              `json:"failure_gen"`
	FailureTerminal     bool               `json:"failure_terminal"`
	FailureAttempts     int32              `json:"failure_attempts"`
	IsReady             bool               `json:"is_ready"`
	Phase               string             `json:"phase"`
	Finalizers          []string           `json:"finalizers"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	FrozenUntil         pgtype.Timestamptz `json:"frozen_until"`
	LastReconciledAt    pgtype.Timestamptz `json:"last_reconciled_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ShardID             int16              `json:"shard_id"`
}

type ResourceCondition struct {
	ResourceID         uuid.UUID          `json:"resource_id"`
	Type               string             `json:"type"`
	Status             string             `json:"status"`
	Reason             string             `json:"reason"`
	Message            string             `json:"message"`
	ObservedGeneration int64              `json:"observed_generation"`
	LastTransitionAt   pgtype.Timestamptz `json:"last_transition_at"`
}

type ResourceDep struct {
	DependentID    uuid.UUID       `json:"dependent_id"`
	DependencyID   uuid.UUID       `json:"dependency_id"`
	ValueFlows     json.RawMessage `json:"value_flows"`
	SrcKindVersion int32           `json:"src_kind_version"`
}

type ResourceEvent struct {
	ID         int64              `json:"id"`
	ResourceID uuid.UUID          `json:"resource_id"`
	Type       string             `json:"type"`
	Actor      *string            `json:"actor"`
	Reason     *string            `json:"reason"`
	Message    *string            `json:"message"`
	Detail     json.RawMessage    `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ResourceMetum struct {
	ID     uuid.UUID       `json:"id"`
	Kind   string          `json:"kind"`
	Name   string          `json:"name"`
	Labels json.RawMessage `json:"labels"`
}

type ResourceOperation struct {
	ID           uuid.UUID          `json:"id"`
	ResourceID   uuid.UUID          `json:"resource_id"`
	Verb         string             `json:"verb"`
	Input        json.RawMessage    `json:"input"`
	Output       []byte             `json:"output"`
	State        string             `json:"state"`
	ErrorMessage *string            `json:"error_message"`
	Attempts     int32              `json:"attempts"`
	RequestedBy  *string            `json:"requested_by"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type RollupRecheck struct {
	ResourceID uuid.UUID `json:"resource_id"`
	ShardID    int16     `json:"shard_id"`
}

type ScheduleRecheck struct {
	ResourceID uuid.UUID `json:"resource_id"`
	ShardID    int16     `json:"shard_id"`
}

type SpecVersion struct {
	ResourceID uuid.UUID          `json:"resource_id"`
	Generation int64              `json:"generation"`
	Spec       json.RawMessage    `json:"spec"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WakeState struct {
	Channel      string             `json:"channel"`
	LastNotifyAt pgtype.Timestamptz `json:"last_notify_at"`
}

type WorkOutbox struct {
	WorkID             uuid.UUID   `json:"work_id"`
	ResourceID         uuid.UUID   `json:"resource_id"`
	OpID               pgtype.UUID `json:"op_id"`
	TaskType           TaskType    `json:"task_type"`
	Succeeded          bool        `json:"succeeded"`
	Payload            []byte      `json:"payload"`
	ErrorMessage       *string     `json:"error_message"`
	ObservedGeneration int64       `json:"observed_generation"`
	AdvanceSyncedGen   bool        `json:"advance_synced_gen"`
	HealthOk           *bool       `json:"health_ok"`
	Conditions         []byte      `json:"conditions"`
	Failed             bool        `json:"failed"`
	Terminal           bool        `json:"terminal"`
	FinalizerName      *string     `json:"finalizer_name"`
	ManifestVersion    int64       `json:"manifest_version"`
	ShardID            int16       `json:"shard_id"`
}

type WorkQueue struct {
	ID              uuid.UUID          `json:"id"`
	ResourceID      uuid.UUID          `json:"resource_id"`
	TaskType        TaskType           `json:"task_type"`
	OpID            pgtype.UUID        `json:"op_id"`
	Kind            string             `json:"kind"`
	Generation      int64              `json:"generation"`
	Spec            []byte             `json:"spec"`
	ProviderConfig  []byte             `json:"provider_config"`
	ProviderBundle  []byte             `json:"provider_bundle"`
	Attempts        int32              `json:"attempts"`
	BrokerID        *string            `json:"broker_id"`
	WorkerID        *string            `json:"worker_id"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ManifestVersion int64              `json:"manifest_version"`
	KindVersion     int16              `json:"kind_version"`
	ClaimEpoch      int64              `json:"claim_epoch"`
	ShardID         int16              `json:"shard_id"`
}
