// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOperation = `-- name: CreateOperation :one

INSERT INTO resource_operations (resource_id, verb, input, requested_by)
VALUES ($1, $2, $3, $4)
RETURNING id, resource_id, verb, input, output, state, error_message, attempts, requested_by, requested_at, completed_at
`

type CreateOperationParams struct {
	ResourceID  uuid.UUID       `json:"resource_id"`
	Verb        string          `json:"verb"`
	Input       json.RawMessage `json:"input"`
	RequestedBy *string         `json:"requested_by"`
}

// Subresource operation queries: durable record of verb invocations
// (e.g. a kind-specific imperative verb). The verb runs through work_queue
// with task_type='operate' and op_id pointing at a row here.
// Inserts a pending operation row. The API handler then enqueues a
// work_queue row (task_type='operate', op_id pointing here) so the
// next loop tick dispatches the verb.
func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (ResourceOperation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ResourceID,
		arg.Verb,
		arg.Input,
		arg.RequestedBy,
	)
	var i ResourceOperation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Verb,
		&i.Input,
		&i.Output,
		&i.State,
		&i.ErrorMessage,
		&i.Attempts,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const enqueueOperationWork = `-- name: EnqueueOperationWork :execrows
INSERT INTO work_queue (resource_id, task_type, op_id, kind, kind_version, generation, spec, provider_config, provider_bundle, manifest_version, shard_id)
SELECT r.id, 'operate'::task_type, $1, r.kind, r.kind_version, r.generation, r.spec,
       (SELECT pc.spec FROM providerconfigs pc WHERE pc.id = r.provider_config_id),  -- clone custom config spec
       (SELECT pc.data FROM providerconfigs pc WHERE pc.id = r.provider_config_id),  -- clone custom config bundle
       r.manifest_version,  -- fence the result write on the manifest the verb was enqueued under (like every other path)
       shard_of(r.id)
FROM resources r WHERE r.id = $2
  -- FROZEN states bar operate (subresource-verb) work too: an operator who set a
  -- resource aside (quarantined) or a child pending teardown (orphaned) must not
  -- have a verb run against the live provider. The freeze is enqueue-side (the
  -- claim path doesn't see resource state), so guard here exactly like the 7
  -- reconcile schedulers. A frozen resource selects 0 rows → no operate enqueued;
  -- the API rejects up front (handlers_ops) so the operation row isn't left
  -- stuck pending. delete tasks are deliberately NOT gated (teardown must proceed).
  AND r.frozen_until IS NULL          -- orphaned OR quarantined = frozen
ON CONFLICT (resource_id, task_type, shard_id) DO NOTHING
`

type EnqueueOperationWorkParams struct {
	OpID       pgtype.UUID `json:"op_id"`
	ResourceID uuid.UUID   `json:"resource_id"`
}

// Inserts the work_queue row that runs the operation. Spec is the
// resource spec snapshot (inline) at request time; the operator sees
// stable input even if reconciliation work updates the spec mid-flight.
// ON CONFLICT no-ops if an operate task is already pending for this resource.
// Returns the affected-row count so the caller can distinguish a real enqueue
// (1) from a no-op — a frozen resource (0 selected rows) or a duplicate operate
// task already queued (0 by ON CONFLICT) — and fail closed instead of recording
// an operation with no backing task.
func (q *Queries) EnqueueOperationWork(ctx context.Context, arg EnqueueOperationWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueOperationWork, arg.OpID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOperation = `-- name: GetOperation :one
SELECT id, resource_id, verb, input, output, state, error_message, attempts, requested_by, requested_at, completed_at FROM resource_operations WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id uuid.UUID) (ResourceOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i ResourceOperation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Verb,
		&i.Input,
		&i.Output,
		&i.State,
		&i.ErrorMessage,
		&i.Attempts,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listOperationsByResource = `-- name: ListOperationsByResource :many
SELECT id, resource_id, verb, input, output, state, error_message, attempts, requested_by, requested_at, completed_at FROM resource_operations
WHERE resource_id = $1
  AND ($2::text[] IS NULL OR state = ANY($2::text[]))
ORDER BY requested_at DESC, id DESC
LIMIT $3::int
`

type ListOperationsByResourceParams struct {
	ResourceID uuid.UUID `json:"resource_id"`
	States     []string  `json:"states"`
	Lim        int32     `json:"lim"`
}

// Newest-first listing, optionally filtered by state. Used by the UI
// Operations tab.
func (q *Queries) ListOperationsByResource(ctx context.Context, arg ListOperationsByResourceParams) ([]ResourceOperation, error) {
	rows, err := q.db.Query(ctx, listOperationsByResource, arg.ResourceID, arg.States, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceOperation
	for rows.Next() {
		var i ResourceOperation
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Verb,
			&i.Input,
			&i.Output,
			&i.State,
			&i.ErrorMessage,
			&i.Attempts,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOperationRunning = `-- name: SetOperationRunning :exec
UPDATE resource_operations
SET state = 'running',
    attempts = attempts + 1
WHERE id = $1 AND state IN ('pending', 'running')
`

// The dispatcher calls this when it claims an operate task. Best-effort; the
// drainer-side state writes (succeeded/failed) are authoritative.
func (q *Queries) SetOperationRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setOperationRunning, id)
	return err
}
