// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providerconfigs.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProviderConfigs = `-- name: CountProviderConfigs :one
SELECT count(*)
FROM providerconfigs pc
WHERE ($1::text = '' OR pc.kind = $1::text)
  AND ($2::int = 0 OR pc.kind_version = $2::int)
  AND ($3::text = '' OR pc.name ILIKE '%' || $3::text || '%')
  AND ($4::bool IS NULL OR pc.is_default = $4::bool)
`

type CountProviderConfigsParams struct {
	KindFilter        string `json:"kind_filter"`
	KindVersionFilter int32  `json:"kind_version_filter"`
	NameFilter        string `json:"name_filter"`
	DefaultFilter     *bool  `json:"default_filter"`
}

// Total rows matching the same filter set as ListProviderConfigs. Kept in lockstep.
func (q *Queries) CountProviderConfigs(ctx context.Context, arg CountProviderConfigsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderConfigs,
		arg.KindFilter,
		arg.KindVersionFilter,
		arg.NameFilter,
		arg.DefaultFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :one
DELETE FROM providerconfigs WHERE name = $1
RETURNING id
`

// Remove a config by name. ON DELETE SET NULL on resources.provider_config_id
// demotes any consumers back to the kind default. Returns whether a row went.
func (q *Queries) DeleteProviderConfig(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProviderConfig, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDefaultProviderConfig = `-- name: GetDefaultProviderConfig :one

SELECT id, spec, data
FROM providerconfigs
WHERE kind = $1 AND kind_version = $2::int AND is_default
`

type GetDefaultProviderConfigParams struct {
	Kind        string `json:"kind"`
	KindVersion int32  `json:"kind_version"`
}

type GetDefaultProviderConfigRow struct {
	ID   uuid.UUID       `json:"id"`
	Spec json.RawMessage `json:"spec"`
	Data []byte          `json:"data"`
}

// Queries for the providerconfigs table: the runtime-editable per-kind config
// store. Defaults (is_default=TRUE, one per kind) are captured by workers at
// boot and live-reconfigured; customs (is_default=FALSE) are referenced by
// resources.provider_config_id and cloned into the work queue at schedule.
// The (kind, kind_version)'s DEFAULT config document + bundle, loaded at boot and on every
// reconfigure by the config plane. Per-kind_version: a vpc/v2 resource merges over vpc/v2's
// default, not v1's. spec is the operational config (merged with a per-resource
// override downstream); data is the opaque provider bundle. At most one row matches
// (uq_providerconfigs_default_per_kind on (kind, kind_version)), an index probe.
func (q *Queries) GetDefaultProviderConfig(ctx context.Context, arg GetDefaultProviderConfigParams) (GetDefaultProviderConfigRow, error) {
	row := q.db.QueryRow(ctx, getDefaultProviderConfig, arg.Kind, arg.KindVersion)
	var i GetDefaultProviderConfigRow
	err := row.Scan(&i.ID, &i.Spec, &i.Data)
	return i, err
}

const getDefaultProviderConfigName = `-- name: GetDefaultProviderConfigName :one
SELECT name
FROM providerconfigs
WHERE kind = $1 AND kind_version = $2::int AND is_default
`

type GetDefaultProviderConfigNameParams struct {
	Kind        string `json:"kind"`
	KindVersion int32  `json:"kind_version"`
}

// The NAME of a (kind, kind_version)'s current DEFAULT config (if any). The composer config
// diff uses it to detect a default collision and demote a conflicting emitted
// default to a custom override BEFORE the upsert, so a second default never trips
// uq_providerconfigs_default_per_kind mid-compose. Index probe.
func (q *Queries) GetDefaultProviderConfigName(ctx context.Context, arg GetDefaultProviderConfigNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getDefaultProviderConfigName, arg.Kind, arg.KindVersion)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT pc.id, pc.name, pc.kind, pc.kind_version, pc.is_default, pc.spec, pc.data, pc.owner_id,
       om.kind AS owner_kind, om.name AS owner_name,
       pc.created_at, pc.updated_at
FROM providerconfigs pc
LEFT JOIN resource_meta om ON om.id = pc.owner_id
WHERE pc.name = $1
`

type GetProviderConfigRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	KindVersion int16              `json:"kind_version"`
	IsDefault   bool               `json:"is_default"`
	Spec        json.RawMessage    `json:"spec"`
	Data        []byte             `json:"data"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	OwnerKind   *string            `json:"owner_kind"`
	OwnerName   *string            `json:"owner_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// One config by name for the read/detail API, with its owner's kind+name (if a
// composer owns it) resolved via resource_meta. owner_* are NULL for unowned configs.
func (q *Queries) GetProviderConfig(ctx context.Context, name string) (GetProviderConfigRow, error) {
	row := q.db.QueryRow(ctx, getProviderConfig, name)
	var i GetProviderConfigRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.KindVersion,
		&i.IsDefault,
		&i.Spec,
		&i.Data,
		&i.OwnerID,
		&i.OwnerKind,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConfigByName = `-- name: GetProviderConfigByName :one
SELECT id, kind, kind_version
FROM providerconfigs
WHERE name = $1
`

type GetProviderConfigByNameRow struct {
	ID          uuid.UUID `json:"id"`
	Kind        string    `json:"kind"`
	KindVersion int16     `json:"kind_version"`
}

// Resolve a custom config NAME (a manifest's provider_config_ref) to its id, kind
// AND kind_version, so Apply can persist resources.provider_config_id and reject a config
// whose (kind, kind_version) doesn't match the resource. Indexed point read on UNIQUE name.
func (q *Queries) GetProviderConfigByName(ctx context.Context, name string) (GetProviderConfigByNameRow, error) {
	row := q.db.QueryRow(ctx, getProviderConfigByName, name)
	var i GetProviderConfigByNameRow
	err := row.Scan(&i.ID, &i.Kind, &i.KindVersion)
	return i, err
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT pc.id, pc.name, pc.kind, pc.kind_version, pc.is_default, pc.owner_id,
       om.kind AS owner_kind, om.name AS owner_name,
       pc.created_at, pc.updated_at
FROM providerconfigs pc
LEFT JOIN resource_meta om ON om.id = pc.owner_id
WHERE ($1::text = '' OR pc.kind = $1::text)
  AND ($2::int = 0 OR pc.kind_version = $2::int)
  AND ($3::text = '' OR pc.name ILIKE '%' || $3::text || '%')
  AND ($4::bool IS NULL OR pc.is_default = $4::bool)
ORDER BY pc.kind, pc.kind_version, pc.name
LIMIT $6::int OFFSET $5::int
`

type ListProviderConfigsParams struct {
	KindFilter        string `json:"kind_filter"`
	KindVersionFilter int32  `json:"kind_version_filter"`
	NameFilter        string `json:"name_filter"`
	DefaultFilter     *bool  `json:"default_filter"`
	Off               int32  `json:"off"`
	Lim               int32  `json:"lim"`
}

type ListProviderConfigsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	KindVersion int16              `json:"kind_version"`
	IsDefault   bool               `json:"is_default"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	OwnerKind   *string            `json:"owner_kind"`
	OwnerName   *string            `json:"owner_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// PAGINATED admin list. Filters (all optional, AND-combined):
//
//	kind_filter    : exact kind ('' = any)
//	kind_version_filter   : exact kind_version (0 = any)
//	name_filter    : substring match on name ('' = any), trigram-indexed ILIKE
//	default_filter : tri-state is_default (NULL = any, true/false = that role)
//
// Owner kind+name joined for the "owner, if any" column. Ordered (kind, kind_version, name)
// for a stable page. SLIM row: spec + the opaque data bundle are NOT selected (the
// list renders identity/role/owner only); the full manifest comes from GetProviderConfig.
func (q *Queries) ListProviderConfigs(ctx context.Context, arg ListProviderConfigsParams) ([]ListProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listProviderConfigs,
		arg.KindFilter,
		arg.KindVersionFilter,
		arg.NameFilter,
		arg.DefaultFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderConfigsRow
	for rows.Next() {
		var i ListProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.KindVersion,
			&i.IsDefault,
			&i.OwnerID,
			&i.OwnerKind,
			&i.OwnerName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConfigsByOwner = `-- name: ListProviderConfigsByOwner :many
SELECT id, name, kind, kind_version, is_default, spec
FROM providerconfigs
WHERE owner_id = $1
`

type ListProviderConfigsByOwnerRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Kind        string          `json:"kind"`
	KindVersion int16           `json:"kind_version"`
	IsDefault   bool            `json:"is_default"`
	Spec        json.RawMessage `json:"spec"`
}

// Every config a given composer root owns — the set ApplyComposeResult diffs a
// fresh compose's emitted configs against. Index probe on idx_providerconfigs_owner.
func (q *Queries) ListProviderConfigsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListProviderConfigsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProviderConfigsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderConfigsByOwnerRow
	for rows.Next() {
		var i ListProviderConfigsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.KindVersion,
			&i.IsDefault,
			&i.Spec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderConfig = `-- name: UpsertProviderConfig :one
INSERT INTO providerconfigs (name, kind, kind_version, is_default, spec, data)
VALUES ($1, $2, $6::int, $3, $4, $5)
ON CONFLICT (name) DO UPDATE
    SET kind       = EXCLUDED.kind,
        kind_version      = EXCLUDED.kind_version,
        is_default = EXCLUDED.is_default,
        spec       = EXCLUDED.spec,
        data       = EXCLUDED.data,
        updated_at = now()
RETURNING id, name, kind, kind_version, is_default, spec, data, owner_id, created_at, updated_at, (xmax = 0) AS created
`

type UpsertProviderConfigParams struct {
	Name        string          `json:"name"`
	Kind        string          `json:"kind"`
	IsDefault   bool            `json:"is_default"`
	Spec        json.RawMessage `json:"spec"`
	Data        []byte          `json:"data"`
	KindVersion int32           `json:"kind_version"`
}

type UpsertProviderConfigRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	KindVersion int16              `json:"kind_version"`
	IsDefault   bool               `json:"is_default"`
	Spec        json.RawMessage    `json:"spec"`
	Data        []byte             `json:"data"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Created     bool               `json:"created"`
}

// Create-or-update a config by NAME (the global handle). kind + kind_version + is_default
// + spec + data are overwritten on update. A second default for a (kind, kind_version) is
// rejected by uq_providerconfigs_default_per_kind (surfaced as a conflict). name
// stays globally unique, so a config is pinned to one kind_version — a v2 config uses a
// distinct name. created distinguishes insert (xmax=0) from update.
func (q *Queries) UpsertProviderConfig(ctx context.Context, arg UpsertProviderConfigParams) (UpsertProviderConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertProviderConfig,
		arg.Name,
		arg.Kind,
		arg.IsDefault,
		arg.Spec,
		arg.Data,
		arg.KindVersion,
	)
	var i UpsertProviderConfigRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.KindVersion,
		&i.IsDefault,
		&i.Spec,
		&i.Data,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
