// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reaper.sql

package dbq

import (
	"context"
)

const deleteUnclaimedWork = `-- name: DeleteUnclaimedWork :one
SELECT delete_unclaimed_work($1::int, $2::int, $3::smallint, $4::smallint)::int AS deleted
`

type DeleteUnclaimedWorkParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int16 `json:"column_3"`
	Column4 int16 `json:"column_4"`
}

// Hard-deletes work_queue rows that have been UNCLAIMED for longer than
// delete_seconds — abandoned tasks no worker ever picked up (kind has no
// worker / decommissioned). Garbage collection, not recovery: if a worker
// for the kind returns, requeue_failed_and_pending re-enqueues a fresh row.
// shard_lo/shard_hi bound the reaper's contiguous range (partition pruning).
func (q *Queries) DeleteUnclaimedWork(ctx context.Context, arg DeleteUnclaimedWorkParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUnclaimedWork,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var deleted int32
	err := row.Scan(&deleted)
	return deleted, err
}

const reapStaleWork = `-- name: ReapStaleWork :one

SELECT reap_stale_work($1::int, $2::int, $3::smallint, $4::smallint)::int AS reaped
`

type ReapStaleWorkParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int16 `json:"column_3"`
	Column4 int16 `json:"column_4"`
}

// Go-side wrappers for the SQL functions called by the reaper.
// Frees task rows whose worker stopped heartbeating so the next claim
// picks them up. No condition writes — failures surface via
// resource_events + work_outbox.error_message. shard_lo/shard_hi bound
// the reaper's contiguous shard range (range → partition pruning on the
// RANGE-partitioned work_queue).
func (q *Queries) ReapStaleWork(ctx context.Context, arg ReapStaleWorkParams) (int32, error) {
	row := q.db.QueryRow(ctx, reapStaleWork,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var reaped int32
	err := row.Scan(&reaped)
	return reaped, err
}

const recountInflight = `-- name: RecountInflight :exec
SELECT recount_inflight($1::smallint, $2::smallint)
`

type RecountInflightParams struct {
	Column1 int16 `json:"column_1"`
	Column2 int16 `json:"column_2"`
}

// Self-healing per-kind in-flight recount over this reaper's contiguous
// shard range. Reclaims worker hint partials in [lo,hi] and writes one
// authoritative per-range count. Range-pruned, off the hot claim path.
func (q *Queries) RecountInflight(ctx context.Context, arg RecountInflightParams) error {
	_, err := q.db.Exec(ctx, recountInflight, arg.Column1, arg.Column2)
	return err
}

const requeueFailedAndPending = `-- name: RequeueFailedAndPending :one
SELECT requeue_failed_and_pending($1::int, $2::int, $3::smallint[])::int AS rescheduled
`

type RequeueFailedAndPendingParams struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 []int16 `json:"column_3"`
}

// Re-schedules pending/failed/working-orphan rows whose dependencies
// are now ready and that have aged past retry_seconds.
func (q *Queries) RequeueFailedAndPending(ctx context.Context, arg RequeueFailedAndPendingParams) (int32, error) {
	row := q.db.QueryRow(ctx, requeueFailedAndPending, arg.Column1, arg.Column2, arg.Column3)
	var rescheduled int32
	err := row.Scan(&rescheduled)
	return rescheduled, err
}

const sweepDeletable = `-- name: SweepDeletable :one
SELECT sweep_deletable($1::int, $2::smallint, $3::smallint)::int AS removed
`

type SweepDeletableParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int16 `json:"column_2"`
	Column3 int16 `json:"column_3"`
}

// Level-triggered backstop for reverse-dependency cascade delete: hard-deletes any
// deletion_requested row whose finalizers are empty (teardown done, or none) AND
// that has no remaining OWNED child AND no remaining DEPENDENT (resource_deps). The
// marked teardown tree collapses inward one layer per reaper tick — removing a leaf
// unblocks its parent for the next tick. STRICT: a node still holding a finalizer
// keeps blocking its parent (no unblock). shard_lo/shard_hi bound the reaper range;
// the scan rides idx_resources_deleting and the function carries its own idle gate.
func (q *Queries) SweepDeletable(ctx context.Context, arg SweepDeletableParams) (int32, error) {
	row := q.db.QueryRow(ctx, sweepDeletable, arg.Column1, arg.Column2, arg.Column3)
	var removed int32
	err := row.Scan(&removed)
	return removed, err
}

const sweepExpiredOrphans = `-- name: SweepExpiredOrphans :one
SELECT sweep_expired_orphans($1::int, $2::smallint, $3::smallint)::int AS swept
`

type SweepExpiredOrphansParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int16 `json:"column_2"`
	Column3 int16 `json:"column_3"`
}

// Tears down composer-dropped children whose orphan-grace window has elapsed
// without a re-emit (frozen_until < now(), not yet draining): finalizer kinds →
// soft-delete (request_resource_deletion semantics, set-based), leaf kinds →
// hard delete. Per-kind finalizer read from kind_config in-DB (the reaper has no
// Go registry). Grace is baked into frozen_until by the composer, so no grace
// arg. A quarantined row (frozen_until = 'infinity') is never < now(), so it is
// never swept. shard_lo/shard_hi bound the reaper's range (partition pruning on
// the delete-task work_queue inserts; the resources scan rides idx_resources_frozen_sweep).
func (q *Queries) SweepExpiredOrphans(ctx context.Context, arg SweepExpiredOrphansParams) (int32, error) {
	row := q.db.QueryRow(ctx, sweepExpiredOrphans, arg.Column1, arg.Column2, arg.Column3)
	var swept int32
	err := row.Scan(&swept)
	return swept, err
}
