// Hand-written queries that sqlc 1.31 can't type. NOT regenerated by
// `just sqlc` — edit this file directly. The store package wraps each constant
// with a typed Go helper (internal/store) that scans the columns sqlc couldn't
// map.
//
// Two type features defeat sqlc here:
//   - int4range columns/returns (cluster_members.shards, assign_member_shards()):
//     sqlc has no Go mapping, so the store casts via lower()/upper() and scans the
//     bounds itself — the same "store does the typed conversion" pattern as the
//     shards write path in cluster_members.sql.
//   - a RETURNS TABLE set-returning function (claim_reactor_deliveries): sqlc
//     can't infer the result columns' types from the function signature.
//
// Kept here (not inline in the store package) so ALL hand-written SQL lives in
// internal/dbq alongside the generated queries — the single home for the query
// layer, per the project's SQL convention.

package dbq

// ClaimReactorDeliveriesSQL calls the plpgsql claim function, which does the FOR
// UPDATE SKIP LOCKED + binding JOIN + resource/config resolution in-DB; the store
// stamps broker_id via the function so other pods skip the claimed rows. Manual
// because sqlc cannot infer the column types of a RETURNS TABLE function.
const ClaimReactorDeliveriesSQL = `
SELECT resource_id, kind, name, transition, generation, status,
       binding_name, reactor, reaction, reactor_kind_version, claim_epoch
FROM claim_reactor_deliveries($1::text, $2::int, $3::smallint, $4::smallint)`

// ListClusterMembersSQL returns the full running-fleet registry, newest heartbeat
// first. Manual because sqlc can't type the int4range `shards` column — the store
// scans lower(shards)/upper(shards) (NULL when the member owns no slice) into
// pgtype.Int4 itself. The raw last_heartbeat is returned; the API derives
// Ready/NotReady from its age.
const ListClusterMembersSQL = `
SELECT member_id, role, lower(shards), upper(shards), config,
       in_flight, workers, version, hostname, pid,
       started_at, last_heartbeat
FROM cluster_members
ORDER BY last_heartbeat DESC, member_id`

// ListLiveClusterMembersSQL is ListClusterMembersSQL narrowed to members whose
// heartbeat is within the liveness window ($1 seconds) — the ROUTING view of the
// registry, as opposed to ListClusterMembersSQL's full UI/history view. It uses the
// SAME `last_heartbeat >= now() - make_interval(...)` predicate as assign_member_shards
// (see AssignMemberShardsSQL / the assign_member_shards function), so shard ownership
// and mesh peer routing share ONE definition of "alive": the TopologyWatcher reads this
// so a crashed peer (heartbeat lapsed, row not yet GC'd) drops out of the mesh peer set
// within one liveness window instead of lingering to the ClusterMemberGC TTL.
const ListLiveClusterMembersSQL = `
SELECT member_id, role, lower(shards), upper(shards), config,
       in_flight, workers, version, hostname, pid,
       started_at, last_heartbeat
FROM cluster_members
WHERE last_heartbeat >= now() - make_interval(secs => $1::int)
ORDER BY last_heartbeat DESC, member_id`

// AssignMemberShardsSQL calls assign_member_shards() ONCE and unwraps the returned
// int4range into its lower/upper bounds. Manual for the same int4range reason as
// ListClusterMembersSQL. The CTE binds the single call so lower()/upper() don't
// evaluate it twice; a NULL range (member owns nothing) → NULL bounds → ok=false.
const AssignMemberShardsSQL = `
WITH a AS (
    SELECT assign_member_shards($1::text, $2::int, $3::int) AS r
)
SELECT lower(a.r), upper(a.r) FROM a`
