// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/salesforce/converge/internal/model"
)

const countChildrenByReadiness = `-- name: CountChildrenByReadiness :many
SELECT kind,
       count(*) FILTER (WHERE phase = 'Ready')::bigint       AS ready,
       count(*) FILTER (WHERE phase = 'Reconciling')::bigint AS reconciling,
       count(*) FILTER (WHERE phase = 'Degraded')::bigint    AS degraded,
       count(*) FILTER (WHERE phase = 'Failed')::bigint      AS failed,
       count(*) FILTER (WHERE phase = 'Deleting')::bigint    AS deleting,
       count(*) FILTER (WHERE phase = 'Orphaned')::bigint    AS orphaned,
       count(*) FILTER (WHERE phase = 'Quarantined')::bigint AS quarantined
FROM resources WHERE owner_id = $1
GROUP BY kind
`

type CountChildrenByReadinessRow struct {
	Kind        model.Kind `json:"kind"`
	Ready       int64      `json:"ready"`
	Reconciling int64      `json:"reconciling"`
	Degraded    int64      `json:"degraded"`
	Failed      int64      `json:"failed"`
	Deleting    int64      `json:"deleting"`
	Orphaned    int64      `json:"orphaned"`
	Quarantined int64      `json:"quarantined"`
}

// Per-kind phase breakdown. Six FILTER buckets over the generated `phase`
// scalar — one GROUP BY scan, no join.
func (q *Queries) CountChildrenByReadiness(ctx context.Context, ownerID pgtype.UUID) ([]CountChildrenByReadinessRow, error) {
	rows, err := q.db.Query(ctx, countChildrenByReadiness, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChildrenByReadinessRow
	for rows.Next() {
		var i CountChildrenByReadinessRow
		if err := rows.Scan(
			&i.Kind,
			&i.Ready,
			&i.Reconciling,
			&i.Degraded,
			&i.Failed,
			&i.Deleting,
			&i.Orphaned,
			&i.Quarantined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResourcesByReadinessScoped = `-- name: CountResourcesByReadinessScoped :many
SELECT kind,
       count(*) FILTER (WHERE phase = 'Ready')::bigint       AS ready,
       count(*) FILTER (WHERE phase = 'Reconciling')::bigint AS reconciling,
       count(*) FILTER (WHERE phase = 'Degraded')::bigint    AS degraded,
       count(*) FILTER (WHERE phase = 'Failed')::bigint      AS failed,
       count(*) FILTER (WHERE phase = 'Deleting')::bigint    AS deleting,
       count(*) FILTER (WHERE phase = 'Orphaned')::bigint    AS orphaned,
       count(*) FILTER (WHERE phase = 'Quarantined')::bigint AS quarantined
FROM resources
WHERE ($1::uuid[] IS NULL
       OR owner_id = ANY($1::uuid[]))
GROUP BY kind
`

type CountResourcesByReadinessScopedRow struct {
	Kind        model.Kind `json:"kind"`
	Ready       int64      `json:"ready"`
	Reconciling int64      `json:"reconciling"`
	Degraded    int64      `json:"degraded"`
	Failed      int64      `json:"failed"`
	Deleting    int64      `json:"deleting"`
	Orphaned    int64      `json:"orphaned"`
	Quarantined int64      `json:"quarantined"`
}

func (q *Queries) CountResourcesByReadinessScoped(ctx context.Context, ownerIds []uuid.UUID) ([]CountResourcesByReadinessScopedRow, error) {
	rows, err := q.db.Query(ctx, countResourcesByReadinessScoped, ownerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountResourcesByReadinessScopedRow
	for rows.Next() {
		var i CountResourcesByReadinessScopedRow
		if err := rows.Scan(
			&i.Kind,
			&i.Ready,
			&i.Reconciling,
			&i.Degraded,
			&i.Failed,
			&i.Deleting,
			&i.Orphaned,
			&i.Quarantined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResourcesFiltered = `-- name: CountResourcesFiltered :one
SELECT count(*) FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE
      ($1::uuid[] IS NULL
       OR r.owner_id = ANY($1::uuid[]))
  AND ($2::text[]    IS NULL OR r.kind = ANY($2::text[]))
  -- (kind, kind_version) PAIR filter — mirrors ListResourcesPage so the count matches.
  AND ($3::text[] IS NULL
       OR (r.kind = ANY($3::text[])
           AND (r.kind || ':' || r.kind_version::text) = ANY($4::text[])))
  AND ($5::text[] IS NULL OR r.phase = ANY($5::text[]))
  AND ($6::text  IS NULL OR m.name ILIKE '%' || $6::text || '%')
  AND ($7::jsonb IS NULL OR m.labels @> $7::jsonb)
`

type CountResourcesFilteredParams struct {
	OwnerIds   []uuid.UUID `json:"owner_ids"`
	Kinds      []string    `json:"kinds"`
	KvKinds    []string    `json:"kv_kinds"`
	KvPairs    []string    `json:"kv_pairs"`
	Phases     []string    `json:"phases"`
	NameLike   *string     `json:"name_like"`
	LabelMatch []byte      `json:"label_match"`
}

func (q *Queries) CountResourcesFiltered(ctx context.Context, arg CountResourcesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesFiltered,
		arg.OwnerIds,
		arg.Kinds,
		arg.KvKinds,
		arg.KvPairs,
		arg.Phases,
		arg.NameLike,
		arg.LabelMatch,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootResourcesFiltered = `-- name: CountRootResourcesFiltered :one
SELECT count(*) FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id IS NULL
  AND ($1::text[]      IS NULL OR r.kind = ANY($1::text[]))
  -- (kind, kind_version) PAIR filter — mirrors ListRootResourcesPage so the count
  -- matches the page. SARGABLE (kind-prune then composite equality); NULL = none.
  AND ($2::text[] IS NULL
       OR (r.kind = ANY($2::text[])
           AND (r.kind || ':' || r.kind_version::text) = ANY($3::text[])))
  AND ($4::text    IS NULL OR m.name ILIKE '%' || $4::text || '%')
  AND ($5::timestamptz  IS NULL OR r.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR r.created_at <= $6::timestamptz)
  AND ($7::timestamptz  IS NULL OR r.updated_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR r.updated_at <= $8::timestamptz)
  AND ($9::bigint IS NULL OR r.generation >= $9::bigint)
  AND ($10::bigint IS NULL OR r.generation <= $10::bigint)
  AND ($11::bigint IS NULL
       OR (SELECT count(*) FROM resources c WHERE c.owner_id = r.id) >= $11::bigint)
  AND ($12::bigint IS NULL
       OR (SELECT count(*) FROM resources c WHERE c.owner_id = r.id) <= $12::bigint)
  AND ($13::text IS NULL OR r.phase = $13::text)
`

type CountRootResourcesFilteredParams struct {
	Kinds         []string           `json:"kinds"`
	KvKinds       []string           `json:"kv_kinds"`
	KvPairs       []string           `json:"kv_pairs"`
	NameLike      *string            `json:"name_like"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	UpdatedAfter  pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
	GenMin        *int64             `json:"gen_min"`
	GenMax        *int64             `json:"gen_max"`
	CountMin      *int64             `json:"count_min"`
	CountMax      *int64             `json:"count_max"`
	Phase         *string            `json:"phase"`
}

func (q *Queries) CountRootResourcesFiltered(ctx context.Context, arg CountRootResourcesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRootResourcesFiltered,
		arg.Kinds,
		arg.KvKinds,
		arg.KvPairs,
		arg.NameLike,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.GenMin,
		arg.GenMax,
		arg.CountMin,
		arg.CountMax,
		arg.Phase,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const descendantsSettled = `-- name: DescendantsSettled :one
SELECT NOT EXISTS (
    SELECT 1 FROM resources d
    WHERE d.root_id = $1
      AND d.synced_gen < d.generation
      AND d.failure_gen <> d.generation     -- failed children are settled
      AND d.deletion_requested_at IS NULL
      AND d.frozen_until IS NULL            -- frozen (orphaned grace / quarantined) children are settled
) AS settled
`

// The dispatcher's rollup-readiness gate: true when NO live descendant of root
// is still lagging. Its predicates MUST match schedule_eligible / the cascade +
// resync paths EXACTLY, or the worker's rollup-stage gate and the scheduler
// disagree and a frozen (orphaned/quarantined) child would wedge the root's
// rollup. A settled child is one that is synced, or terminally failed at this
// generation, or delete-requested, or frozen (orphan grace / quarantine set-
// aside). Uses idx_resources_root_lagging.
func (q *Queries) DescendantsSettled(ctx context.Context, rootID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, descendantsSettled, rootID)
	var settled bool
	err := row.Scan(&settled)
	return settled, err
}

const gCSpecHistory = `-- name: GCSpecHistory :one
SELECT gc_spec_history($1::int, $2::int, $3::smallint[])::int AS collected
`

type GCSpecHistoryParams struct {
	Column1 int32   `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 []int16 `json:"column_3"`
}

// Trim the spec_versions root history to keep_n newest per root, for one
// pod's shards. See gc_spec_history in 00001_schema.sql.
func (q *Queries) GCSpecHistory(ctx context.Context, arg GCSpecHistoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, gCSpecHistory, arg.Column1, arg.Column2, arg.Column3)
	var collected int32
	err := row.Scan(&collected)
	return collected, err
}

const getChildrenByOwner = `-- name: GetChildrenByOwner :many
SELECT
    r.id, r.kind, m.name, r.owner_id,
    r.generation, r.synced_gen,
    r.is_ready, r.phase,
    r.deletion_requested_at,
    m.labels,
    r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id WHERE r.owner_id = $1
ORDER BY r.created_at, r.id
LIMIT $2
`

type GetChildrenByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

type GetChildrenByOwnerRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Non-paginated children read for the flat /children + /graph views. LIMIT-capped
// ($2) so an owner with millions of children (a composer root) can never stream an
// unbounded response / blow up the API's memory. Walk large sets via the keyset-
// paginated ListResourcesPage (/children/page) instead.
func (q *Queries) GetChildrenByOwner(ctx context.Context, arg GetChildrenByOwnerParams) ([]GetChildrenByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getChildrenByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildrenByOwnerRow
	for rows.Next() {
		var i GetChildrenByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.OwnerID,
			&i.Generation,
			&i.SyncedGen,
			&i.IsReady,
			&i.Phase,
			&i.DeletionRequestedAt,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepsByOwner = `-- name: GetDepsByOwner :many
SELECT
    dent.kind AS dependent_kind, dent.name AS dependent_name,
    dep.kind  AS dependency_kind, dep.name AS dependency_name
FROM resource_deps d
JOIN resources r ON r.id = d.dependent_id
JOIN resource_meta dent ON dent.id = d.dependent_id
JOIN resource_meta dep  ON dep.id  = d.dependency_id
WHERE r.owner_id = $1
LIMIT $2
`

type GetDepsByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

type GetDepsByOwnerRow struct {
	DependentKind  string `json:"dependent_kind"`
	DependentName  string `json:"dependent_name"`
	DependencyKind string `json:"dependency_kind"`
	DependencyName string `json:"dependency_name"`
}

// Dependency edges under one owner, addressed by the PUBLIC (kind, name) of
// each endpoint (not the internal id) so the graph joins nodes by ref. Both
// endpoints live under the same owner, so the meta joins are PK probes.
// LIMIT-capped ($2) for the same reason as GetChildrenByOwner: the graph view
// must not stream an unbounded edge set for a huge owner.
func (q *Queries) GetDepsByOwner(ctx context.Context, arg GetDepsByOwnerParams) ([]GetDepsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getDepsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepsByOwnerRow
	for rows.Next() {
		var i GetDepsByOwnerRow
		if err := rows.Scan(
			&i.DependentKind,
			&i.DependentName,
			&i.DependencyKind,
			&i.DependencyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT
    r.id, r.kind, r.kind_version, m.name, r.owner_id, r.root_id,
    om.kind AS owner_kind, om.name AS owner_name,
    rm.kind AS root_kind,  rm.name AS root_name,
    CASE WHEN pg_column_size(r.spec)   > 102400 THEN NULL::jsonb ELSE r.spec   END AS spec,
    CASE WHEN pg_column_size(r.status) > 102400 THEN NULL::jsonb ELSE r.status END AS status,
    COALESCE(pg_column_size(r.spec), 0)::bigint   AS spec_size,
    COALESCE(pg_column_size(r.status), 0)::bigint AS status_size,
    r.generation, r.synced_gen,
    r.is_ready, r.health_ok, r.phase,
    r.finalizers, r.deletion_requested_at,
    m.labels,
    r.created_at, r.updated_at,
    r.shard_id,
    -- Failure classification for the detail page: failure_terminal = the current-gen
    -- failure won't auto-retry (provider-terminal OR the poison-pill escalated a
    -- persistently-transient failure at the cap → DEAD-LETTERED); failure_attempts =
    -- the durable consecutive-transient-failure count climbing toward the kind's
    -- max_transient_attempts (also returned, from kc) so the UI can show "attempt N of
    -- CAP" and distinguish approaching-dead-letter from already-dead-lettered.
    r.failure_terminal, r.failure_attempts,
    kc.max_transient_attempts AS max_transient_attempts,
    -- manifest_version drift: the version this resource is PINNED to (stamped at
    -- create/compose, carried onto its work) vs the kind's CURRENT applied
    -- version (kind_config). When they differ, a CRD was re-applied after this
    -- resource last scheduled — the detail page surfaces it as a drift signal.
    -- current is NULL when the kind has no manifest yet.
    r.manifest_version AS manifest_version,
    kc.manifest_version AS kind_manifest_version,
    -- Attached CUSTOM provider config (if any), so the detail page can render a
    -- link to it. NULL for the common no-custom-config case (LEFT JOIN). name is
    -- the global handle the provider-configs page resolves by; kind == r.kind.
    pc.name AS provider_config_name,
    pc.kind AS provider_config_kind
FROM resources r
JOIN resource_meta m ON m.id = r.id
LEFT JOIN resource_meta om ON om.id = r.owner_id
LEFT JOIN resource_meta rm ON rm.id = r.root_id
LEFT JOIN providerconfigs pc ON pc.id = r.provider_config_id
LEFT JOIN kind_config kc ON kc.kind = r.kind AND kc.kind_version = r.kind_version
WHERE m.kind = $1 AND m.name = $2
`

type GetResourceParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type GetResourceRow struct {
	ID                   uuid.UUID          `json:"id"`
	Kind                 model.Kind         `json:"kind"`
	KindVersion          int16              `json:"kind_version"`
	Name                 string             `json:"name"`
	OwnerID              pgtype.UUID        `json:"owner_id"`
	RootID               pgtype.UUID        `json:"root_id"`
	OwnerKind            *string            `json:"owner_kind"`
	OwnerName            *string            `json:"owner_name"`
	RootKind             *string            `json:"root_kind"`
	RootName             *string            `json:"root_name"`
	Spec                 interface{}        `json:"spec"`
	Status               interface{}        `json:"status"`
	SpecSize             int64              `json:"spec_size"`
	StatusSize           int64              `json:"status_size"`
	Generation           int64              `json:"generation"`
	SyncedGen            int64              `json:"synced_gen"`
	IsReady              bool               `json:"is_ready"`
	HealthOk             bool               `json:"health_ok"`
	Phase                string             `json:"phase"`
	Finalizers           []string           `json:"finalizers"`
	DeletionRequestedAt  pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels               json.RawMessage    `json:"labels"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ShardID              int16              `json:"shard_id"`
	FailureTerminal      bool               `json:"failure_terminal"`
	FailureAttempts      int32              `json:"failure_attempts"`
	MaxTransientAttempts *int32             `json:"max_transient_attempts"`
	ManifestVersion      int64              `json:"manifest_version"`
	KindManifestVersion  *int64             `json:"kind_manifest_version"`
	ProviderConfigName   *string            `json:"provider_config_name"`
	ProviderConfigKind   *string            `json:"provider_config_kind"`
}

// Per-row read addressed by the PUBLIC (kind, name) — NO separate id-resolve
// probe: the resource_meta join that already materializes name is also the
// lookup key (uniq_resource_meta = one index seek). r.id is returned for the
// detail handler's own follow-ups (conditions, work_queue) so those reuse it
// rather than re-resolving. spec/status are elided server-side when they exceed
// the inline limit (100 KB). owner_id/root_id stay INTERNAL (cache keys); the
// API surfaces owner/root only as (kind, name) refs, resolved here by the two
// LEFT JOINs on resource_meta so the detail read needs no extra round-trip.
func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, arg.Kind, arg.Name)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindVersion,
		&i.Name,
		&i.OwnerID,
		&i.RootID,
		&i.OwnerKind,
		&i.OwnerName,
		&i.RootKind,
		&i.RootName,
		&i.Spec,
		&i.Status,
		&i.SpecSize,
		&i.StatusSize,
		&i.Generation,
		&i.SyncedGen,
		&i.IsReady,
		&i.HealthOk,
		&i.Phase,
		&i.Finalizers,
		&i.DeletionRequestedAt,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShardID,
		&i.FailureTerminal,
		&i.FailureAttempts,
		&i.MaxTransientAttempts,
		&i.ManifestVersion,
		&i.KindManifestVersion,
		&i.ProviderConfigName,
		&i.ProviderConfigKind,
	)
	return i, err
}

const getResourceDependencies = `-- name: GetResourceDependencies :many
SELECT
    u.id   AS upstream_id,
    u.kind AS upstream_kind,
    um.name AS upstream_name,
    u.is_ready AS upstream_ready,
    u.health_ok AS upstream_health_ok,
    u.updated_at AS upstream_updated_at,
    d.value_flows
FROM resource_deps d
JOIN resources u ON u.id = d.dependency_id
JOIN resource_meta um ON um.id = u.id
WHERE d.dependent_id = (SELECT sm.id FROM resource_meta sm WHERE sm.kind = $1 AND sm.name = $2)
ORDER BY u.kind, um.name
`

type GetResourceDependenciesParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type GetResourceDependenciesRow struct {
	UpstreamID        uuid.UUID          `json:"upstream_id"`
	UpstreamKind      model.Kind         `json:"upstream_kind"`
	UpstreamName      string             `json:"upstream_name"`
	UpstreamReady     bool               `json:"upstream_ready"`
	UpstreamHealthOk  bool               `json:"upstream_health_ok"`
	UpstreamUpdatedAt pgtype.Timestamptz `json:"upstream_updated_at"`
	ValueFlows        json.RawMessage    `json:"value_flows"`
}

// Lists every upstream this resource depends on, with the upstream's
// id/kind/name/is_ready/health_ok/updated_at and the value_flows array.
// Address the DEPENDENT by its public (kind, name) via one indexed subquery, so
// there's no separate id-resolve round-trip.
func (q *Queries) GetResourceDependencies(ctx context.Context, arg GetResourceDependenciesParams) ([]GetResourceDependenciesRow, error) {
	rows, err := q.db.Query(ctx, getResourceDependencies, arg.Kind, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceDependenciesRow
	for rows.Next() {
		var i GetResourceDependenciesRow
		if err := rows.Scan(
			&i.UpstreamID,
			&i.UpstreamKind,
			&i.UpstreamName,
			&i.UpstreamReady,
			&i.UpstreamHealthOk,
			&i.UpstreamUpdatedAt,
			&i.ValueFlows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceInfo = `-- name: GetResourceInfo :one
SELECT r.id, r.kind, r.kind_version, m.name, r.owner_id, r.generation, r.synced_gen,
       r.is_ready, r.health_ok, r.phase, r.deletion_requested_at,
       m.labels, r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id WHERE r.id = $1
`

type GetResourceInfoRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	KindVersion         int16              `json:"kind_version"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	HealthOk            bool               `json:"health_ok"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Lightweight metadata only — omits spec/status. By internal id (used by paths
// that already hold one: apply read-back, owner-cache batch fan-in).
func (q *Queries) GetResourceInfo(ctx context.Context, id uuid.UUID) (GetResourceInfoRow, error) {
	row := q.db.QueryRow(ctx, getResourceInfo, id)
	var i GetResourceInfoRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.KindVersion,
		&i.Name,
		&i.OwnerID,
		&i.Generation,
		&i.SyncedGen,
		&i.IsReady,
		&i.HealthOk,
		&i.Phase,
		&i.DeletionRequestedAt,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceInfoByName = `-- name: GetResourceInfoByName :one
SELECT r.id, r.kind, m.name, r.owner_id, r.generation, r.synced_gen,
       r.is_ready, r.health_ok, r.phase, r.deletion_requested_at,
       m.labels, r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE m.kind = $1 AND m.name = $2
`

type GetResourceInfoByNameParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type GetResourceInfoByNameRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	HealthOk            bool               `json:"health_ok"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Same lightweight metadata addressed by the PUBLIC (kind, name). Owner-scoped
// handlers use this for the owner envelope: it returns r.id, so the follow-up
// owner-scoped query reuses it — one indexed seek here, no separate resolve.
func (q *Queries) GetResourceInfoByName(ctx context.Context, arg GetResourceInfoByNameParams) (GetResourceInfoByNameRow, error) {
	row := q.db.QueryRow(ctx, getResourceInfoByName, arg.Kind, arg.Name)
	var i GetResourceInfoByNameRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.OwnerID,
		&i.Generation,
		&i.SyncedGen,
		&i.IsReady,
		&i.HealthOk,
		&i.Phase,
		&i.DeletionRequestedAt,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceManifest = `-- name: GetResourceManifest :one
SELECT
    (CASE WHEN pc.name IS NULL THEN
        jsonb_build_object(
            'kind',   r.kind,
            'kind_version',  r.kind_version,
            'name',   m.name,
            'labels', m.labels,
            'spec',   r.spec
        )
    ELSE
        jsonb_build_object(
            'kind',                r.kind,
            'kind_version',               r.kind_version,
            'name',                m.name,
            'labels',              m.labels,
            'spec',                r.spec,
            'provider_config_ref', pc.name
        )
    END)::jsonb AS manifest,
    r.kind,
    m.name
FROM resources r
JOIN resource_meta m ON m.id = r.id
LEFT JOIN providerconfigs pc ON pc.id = r.provider_config_id
WHERE m.kind = $1 AND m.name = $2
`

type GetResourceManifestParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type GetResourceManifestRow struct {
	Manifest json.RawMessage `json:"manifest"`
	Kind     model.Kind      `json:"kind"`
	Name     string          `json:"name"`
}

// Synthesize the downloadable ResourceManifest entirely in the DB:
// one jsonb_build_object packs identity (kind+name), labels, and the
// live spec into a single column so the bytes never get reassembled
// app-side. Pairs with the Apply body shape (model.ResourceManifest)
// — a downloaded file re-applies as-is. provider_config_ref is included
// ONLY when the resource has a custom config attached, so a download→reapply
// preserves the attachment without polluting the common no-config manifest
// (a CASE rather than jsonb_strip_nulls, which would recursively strip nested
// nulls inside spec). m.name is also returned so the download handler can name
// the attachment without re-parsing the blob.
func (q *Queries) GetResourceManifest(ctx context.Context, arg GetResourceManifestParams) (GetResourceManifestRow, error) {
	row := q.db.QueryRow(ctx, getResourceManifest, arg.Kind, arg.Name)
	var i GetResourceManifestRow
	err := row.Scan(&i.Manifest, &i.Kind, &i.Name)
	return i, err
}

const getResourceStatus = `-- name: GetResourceStatus :one
SELECT r.status, r.kind, m.name FROM resources r JOIN resource_meta m ON m.id = r.id WHERE m.kind = $1 AND m.name = $2
`

type GetResourceStatusParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type GetResourceStatusRow struct {
	Status []byte     `json:"status"`
	Kind   model.Kind `json:"kind"`
	Name   string     `json:"name"`
}

func (q *Queries) GetResourceStatus(ctx context.Context, arg GetResourceStatusParams) (GetResourceStatusRow, error) {
	row := q.db.QueryRow(ctx, getResourceStatus, arg.Kind, arg.Name)
	var i GetResourceStatusRow
	err := row.Scan(&i.Status, &i.Kind, &i.Name)
	return i, err
}

const getResourcesChangedSince = `-- name: GetResourcesChangedSince :many
SELECT
    r.id, r.kind, m.name, r.owner_id,
    r.generation, r.synced_gen,
    r.is_ready, r.phase,
    r.deletion_requested_at,
    m.labels,
    r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id = $1 AND r.updated_at > $2
ORDER BY r.updated_at
LIMIT 1000
`

type GetResourcesChangedSinceParams struct {
	OwnerID   pgtype.UUID        `json:"owner_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GetResourcesChangedSinceRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetResourcesChangedSince(ctx context.Context, arg GetResourcesChangedSinceParams) ([]GetResourcesChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, getResourcesChangedSince, arg.OwnerID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesChangedSinceRow
	for rows.Next() {
		var i GetResourcesChangedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.OwnerID,
			&i.Generation,
			&i.SyncedGen,
			&i.IsReady,
			&i.Phase,
			&i.DeletionRequestedAt,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesInfo = `-- name: GetResourcesInfo :many
SELECT r.id, r.kind, m.name, r.owner_id, r.generation, r.synced_gen,
       r.is_ready, r.health_ok, r.phase, r.deletion_requested_at,
       m.labels, r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id WHERE r.id = ANY($1::uuid[])
`

type GetResourcesInfoRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	HealthOk            bool               `json:"health_ok"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetResourcesInfo(ctx context.Context, dollar_1 []uuid.UUID) ([]GetResourcesInfoRow, error) {
	rows, err := q.db.Query(ctx, getResourcesInfo, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesInfoRow
	for rows.Next() {
		var i GetResourcesInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.OwnerID,
			&i.Generation,
			&i.SyncedGen,
			&i.IsReady,
			&i.HealthOk,
			&i.Phase,
			&i.DeletionRequestedAt,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecRevision = `-- name: GetSpecRevision :one
SELECT spec FROM spec_versions
WHERE resource_id = (SELECT sm.id FROM resource_meta sm WHERE sm.kind = $1 AND sm.name = $2)
  AND generation = $3
`

type GetSpecRevisionParams struct {
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Generation int64  `json:"generation"`
}

// One historic spec body by (kind, name, generation) — the raw revision
// download + the rollback prefill. Name-scoped so another resource's version
// can't be fetched through this resource's identity.
func (q *Queries) GetSpecRevision(ctx context.Context, arg GetSpecRevisionParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSpecRevision, arg.Kind, arg.Name, arg.Generation)
	var spec json.RawMessage
	err := row.Scan(&spec)
	return spec, err
}

const listDescendants = `-- name: ListDescendants :many
SELECT r.id, r.kind, r.kind_version, r.owner_id, r.root_id, r.spec, r.status, r.provider_config_id, r.generation, r.synced_gen, r.health_ok, r.composed_gen, r.manifest_version, r.failure_gen, r.failure_terminal, r.failure_attempts, r.is_ready, r.phase, r.finalizers, r.deletion_requested_at, r.frozen_until, r.last_reconciled_at, r.created_at, r.updated_at, r.shard_id, m.name, m.labels
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.root_id = $1
ORDER BY r.created_at, r.id
`

type ListDescendantsRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	KindVersion         int16              `json:"kind_version"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	RootID              pgtype.UUID        `json:"root_id"`
	Spec                json.RawMessage    `json:"spec"`
	Status              []byte             `json:"status"`
	ProviderConfigID    pgtype.UUID        `json:"provider_config_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	HealthOk            bool               `json:"health_ok"`
	ComposedGen         int64              `json:"composed_gen"`
	ManifestVersion     int64              `json:"manifest_version"`
	FailureGen          int64              `json:"failure_gen"`
	FailureTerminal     bool               `json:"failure_terminal"`
	FailureAttempts     int32              `json:"failure_attempts"`
	IsReady             bool               `json:"is_ready"`
	Phase               string             `json:"phase"`
	Finalizers          []string           `json:"finalizers"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	FrozenUntil         pgtype.Timestamptz `json:"frozen_until"`
	LastReconciledAt    pgtype.Timestamptz `json:"last_reconciled_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ShardID             int16              `json:"shard_id"`
	Name                string             `json:"name"`
	Labels              json.RawMessage    `json:"labels"`
}

// The rollup reaction reads each descendant's labels (fd/team) + name, so
// join meta. The meta join is a PK probe; root_id drives the scan via
// idx_resources_root_descendants.
func (q *Queries) ListDescendants(ctx context.Context, rootID pgtype.UUID) ([]ListDescendantsRow, error) {
	rows, err := q.db.Query(ctx, listDescendants, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDescendantsRow
	for rows.Next() {
		var i ListDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.KindVersion,
			&i.OwnerID,
			&i.RootID,
			&i.Spec,
			&i.Status,
			&i.ProviderConfigID,
			&i.Generation,
			&i.SyncedGen,
			&i.HealthOk,
			&i.ComposedGen,
			&i.ManifestVersion,
			&i.FailureGen,
			&i.FailureTerminal,
			&i.FailureAttempts,
			&i.IsReady,
			&i.Phase,
			&i.Finalizers,
			&i.DeletionRequestedAt,
			&i.FrozenUntil,
			&i.LastReconciledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShardID,
			&i.Name,
			&i.Labels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceConditions = `-- name: ListResourceConditions :many
SELECT resource_id, type, status, reason, message,
       observed_generation, last_transition_at
FROM resource_conditions
WHERE resource_id = $1
ORDER BY (type = 'Ready') DESC, type
`

// Every stored condition row for one resource (the Ready/custom axes the
// provider actually reported). The Synced condition and happy-path
// Ready=True are NOT stored here — the API synthesizes them from the
// resource's scalar axes. Ordered Ready-first then by type for stable UI.
func (q *Queries) ListResourceConditions(ctx context.Context, resourceID uuid.UUID) ([]ResourceCondition, error) {
	rows, err := q.db.Query(ctx, listResourceConditions, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceCondition
	for rows.Next() {
		var i ResourceCondition
		if err := rows.Scan(
			&i.ResourceID,
			&i.Type,
			&i.Status,
			&i.Reason,
			&i.Message,
			&i.ObservedGeneration,
			&i.LastTransitionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesPage = `-- name: ListResourcesPage :many
SELECT
    r.id, r.kind, r.kind_version, m.name, r.owner_id,
    r.generation, r.synced_gen,
    r.is_ready, r.phase,
    r.deletion_requested_at,
    m.labels,
    r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE
      ($2::uuid[] IS NULL
       OR r.owner_id = ANY($2::uuid[]))
  AND ($3::text[]    IS NULL OR r.kind = ANY($3::text[]))
  -- (kind, kind_version) PAIR filter — the kind/version chips (vpc/v1, account/v2).
  -- SARGABLE: ` + "`" + `r.kind = ANY(kv_kinds)` + "`" + ` prunes per kind via idx_resources_kind_pagination,
  -- then the composite ` + "`" + `kind:version` + "`" + ` equality is the exact per-pair match within
  -- that slice (no whole-table scan, no new hot-path index). NULL = no pair filter.
  AND ($4::text[] IS NULL
       OR (r.kind = ANY($4::text[])
           AND (r.kind || ':' || r.kind_version::text) = ANY($5::text[])))
  -- Phase filter — a SET (union of selected phases), not a single value.
  -- The UI lets the operator multi-select phases; we match any of them so
  -- the page is the union, computed and paginated server-side (never a
  -- client-side sliver of the first page). 'Failed' is served by
  -- idx_resources_failed; the others by the generated scalar — no
  -- condition join, ever.
  AND ($6::text[] IS NULL OR r.phase = ANY($6::text[]))
  AND ($7::text  IS NULL OR m.name ILIKE '%' || $7::text || '%')
  AND ($8::jsonb IS NULL OR m.labels @> $8::jsonb)
  AND (
      $9::timestamptz IS NULL
      OR (r.created_at, r.id) < ($9::timestamptz, $10::uuid)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $1
`

type ListResourcesPageParams struct {
	Limit         int32              `json:"limit"`
	OwnerIds      []uuid.UUID        `json:"owner_ids"`
	Kinds         []string           `json:"kinds"`
	KvKinds       []string           `json:"kv_kinds"`
	KvPairs       []string           `json:"kv_pairs"`
	Phases        []string           `json:"phases"`
	NameLike      *string            `json:"name_like"`
	LabelMatch    []byte             `json:"label_match"`
	CursorAfterAt pgtype.Timestamptz `json:"cursor_after_at"`
	CursorAfterID pgtype.UUID        `json:"cursor_after_id"`
}

type ListResourcesPageRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	KindVersion         int16              `json:"kind_version"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// The meta JOIN is a PK probe per row; it only materializes name/labels for
// the LIMIT'd page (and for the name_like/label_match filters when present).
func (q *Queries) ListResourcesPage(ctx context.Context, arg ListResourcesPageParams) ([]ListResourcesPageRow, error) {
	rows, err := q.db.Query(ctx, listResourcesPage,
		arg.Limit,
		arg.OwnerIds,
		arg.Kinds,
		arg.KvKinds,
		arg.KvPairs,
		arg.Phases,
		arg.NameLike,
		arg.LabelMatch,
		arg.CursorAfterAt,
		arg.CursorAfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourcesPageRow
	for rows.Next() {
		var i ListResourcesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.KindVersion,
			&i.Name,
			&i.OwnerID,
			&i.Generation,
			&i.SyncedGen,
			&i.IsReady,
			&i.Phase,
			&i.DeletionRequestedAt,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootResourcesPage = `-- name: ListRootResourcesPage :many
SELECT
    r.id, r.kind, r.kind_version, m.name, r.generation, r.synced_gen,
    r.is_ready, r.health_ok, r.phase, r.deletion_requested_at,
    m.labels, r.created_at, r.updated_at,
    (SELECT count(*) FROM resources c WHERE c.owner_id = r.id)::bigint AS child_count
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id IS NULL
  AND ($2::text[]      IS NULL OR r.kind = ANY($2::text[]))
  -- (kind, kind_version) PAIR filter — the Resources-page kind/version chips
  -- (vpc/v1, account/v2, …). SARGABLE: ` + "`" + `r.kind = ANY(kv_kinds)` + "`" + ` prunes to the
  -- selected kinds' slices via the leading ` + "`" + `kind` + "`" + ` column of
  -- idx_resources_kind_pagination FIRST, then the composite ` + "`" + `kind:version` + "`" + ` equality
  -- is an EXACT per-pair match WITHIN that pruned slice — no whole-table scan, no
  -- new hot-path index. kv_kinds is the distinct kind list (for pruning) and
  -- kv_pairs the "kind:version" strings (for the exact match); the app builds both
  -- from the same chip set. NULL = no pair filter. AND-composed with the plain
  -- ` + "`" + `kinds` + "`" + ` filter (kinds = any version of these kinds; pairs = these exact versions).
  AND ($3::text[] IS NULL
       OR (r.kind = ANY($3::text[])
           AND (r.kind || ':' || r.kind_version::text) = ANY($4::text[])))
  AND ($5::text    IS NULL OR m.name ILIKE '%' || $5::text || '%')
  AND ($6::timestamptz  IS NULL OR r.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR r.created_at <= $7::timestamptz)
  AND ($8::timestamptz  IS NULL OR r.updated_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR r.updated_at <= $9::timestamptz)
  AND ($10::bigint IS NULL OR r.generation >= $10::bigint)
  AND ($11::bigint IS NULL OR r.generation <= $11::bigint)
  AND ($12::bigint IS NULL
       OR (SELECT count(*) FROM resources c WHERE c.owner_id = r.id) >= $12::bigint)
  AND ($13::bigint IS NULL
       OR (SELECT count(*) FROM resources c WHERE c.owner_id = r.id) <= $13::bigint)
  -- phase filter: a single optional value matched against the generated
  -- ` + "`" + `phase` + "`" + ` scalar (one indexed predicate; 'Failed' hits idx_resources_failed).
  AND ($14::text IS NULL OR r.phase = $14::text)
  AND (
      $15::timestamptz IS NULL
      OR (r.created_at, r.id) < ($15::timestamptz, $16::uuid)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $1
`

type ListRootResourcesPageParams struct {
	Limit         int32              `json:"limit"`
	Kinds         []string           `json:"kinds"`
	KvKinds       []string           `json:"kv_kinds"`
	KvPairs       []string           `json:"kv_pairs"`
	NameLike      *string            `json:"name_like"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	UpdatedAfter  pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
	GenMin        *int64             `json:"gen_min"`
	GenMax        *int64             `json:"gen_max"`
	CountMin      *int64             `json:"count_min"`
	CountMax      *int64             `json:"count_max"`
	Phase         *string            `json:"phase"`
	CursorAfterAt pgtype.Timestamptz `json:"cursor_after_at"`
	CursorAfterID pgtype.UUID        `json:"cursor_after_id"`
}

type ListRootResourcesPageRow struct {
	ID                  uuid.UUID          `json:"id"`
	Kind                model.Kind         `json:"kind"`
	KindVersion         int16              `json:"kind_version"`
	Name                string             `json:"name"`
	Generation          int64              `json:"generation"`
	SyncedGen           int64              `json:"synced_gen"`
	IsReady             bool               `json:"is_ready"`
	HealthOk            bool               `json:"health_ok"`
	Phase               string             `json:"phase"`
	DeletionRequestedAt pgtype.Timestamptz `json:"deletion_requested_at"`
	Labels              json.RawMessage    `json:"labels"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ChildCount          int64              `json:"child_count"`
}

func (q *Queries) ListRootResourcesPage(ctx context.Context, arg ListRootResourcesPageParams) ([]ListRootResourcesPageRow, error) {
	rows, err := q.db.Query(ctx, listRootResourcesPage,
		arg.Limit,
		arg.Kinds,
		arg.KvKinds,
		arg.KvPairs,
		arg.NameLike,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.GenMin,
		arg.GenMax,
		arg.CountMin,
		arg.CountMax,
		arg.Phase,
		arg.CursorAfterAt,
		arg.CursorAfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootResourcesPageRow
	for rows.Next() {
		var i ListRootResourcesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.KindVersion,
			&i.Name,
			&i.Generation,
			&i.SyncedGen,
			&i.IsReady,
			&i.HealthOk,
			&i.Phase,
			&i.DeletionRequestedAt,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecHistory = `-- name: ListSpecHistory :many
SELECT s.generation, s.source, s.created_at,
       pg_column_size(s.spec)::bigint AS size_bytes,
       (s.spec IS NOT DISTINCT FROM r.spec) AS is_current
FROM spec_versions s
JOIN resources r ON r.id = s.resource_id
WHERE s.resource_id = (SELECT sm.id FROM resource_meta sm WHERE sm.kind = $1 AND sm.name = $2)
ORDER BY s.generation DESC
LIMIT $3
`

type ListSpecHistoryParams struct {
	Kind  string `json:"kind"`
	Name  string `json:"name"`
	Limit int32  `json:"limit"`
}

type ListSpecHistoryRow struct {
	Generation int64              `json:"generation"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	SizeBytes  int64              `json:"size_bytes"`
	IsCurrent  bool               `json:"is_current"`
}

// Spec revision history for a ROOT resource, newest-first, WITHOUT the
// bodies (the UI lazy-fetches a body via the raw endpoint). is_current
// flags the revision whose body matches the live inline resources.spec (the
// checked-out one — exactly one, found by a JSONB compare over the small
// ≤keep_n history). Served by idx_spec_versions_history. spec_versions holds
// only roots; the API gates the endpoint to roots.
// Address the root by its public (kind, name) via one indexed subquery — single
// round-trip, no separate id-resolve.
func (q *Queries) ListSpecHistory(ctx context.Context, arg ListSpecHistoryParams) ([]ListSpecHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSpecHistory, arg.Kind, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecHistoryRow
	for rows.Next() {
		var i ListSpecHistoryRow
		if err := rows.Scan(
			&i.Generation,
			&i.Source,
			&i.CreatedAt,
			&i.SizeBytes,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantineResource = `-- name: QuarantineResource :one
SELECT quarantine_resource($1, $2)::boolean AS quarantined
`

type QuarantineResourceParams struct {
	PID    uuid.UUID `json:"p_id"`
	PActor string    `json:"p_actor"`
}

// Operator sets a failed/stuck resource ASIDE: freezes it (no retry/resync/
// resurrection) and unblocks its root's rollup, without deleting it. Returns
// true if the row existed and was quarantinable. See quarantine_resource.
func (q *Queries) QuarantineResource(ctx context.Context, arg QuarantineResourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, quarantineResource, arg.PID, arg.PActor)
	var quarantined bool
	err := row.Scan(&quarantined)
	return quarantined, err
}

const requestResourceDeletion = `-- name: RequestResourceDeletion :one
SELECT request_resource_deletion($1, $2, $3)::boolean AS deleted
`

type RequestResourceDeletionParams struct {
	PID        uuid.UUID `json:"p_id"`
	PFinalizer string    `json:"p_finalizer"`
	PActor     string    `json:"p_actor"`
}

// Soft-delete by internal id. The rare operator mutations (delete/quarantine/
// reconcile/rollback) intentionally stay id-based: the API handler resolves
// (kind,name)→id once (an indexed point-read) and calls this. Folding the
// resolve into each function via a *ByName twin would double the SQL/store
// surface to save a microsecond on a manual click — not worth it. The READ
// paths (hot) are folded to a single query; these (cold) are not. Internal
// callers (composer teardown) also hold an id, so id-based is the natural form.
func (q *Queries) RequestResourceDeletion(ctx context.Context, arg RequestResourceDeletionParams) (bool, error) {
	row := q.db.QueryRow(ctx, requestResourceDeletion, arg.PID, arg.PFinalizer, arg.PActor)
	var deleted bool
	err := row.Scan(&deleted)
	return deleted, err
}

const requeueForResync = `-- name: RequeueForResync :one
SELECT requeue_for_resync($1::text, $2::int, $3::int, $4::smallint[], $5::boolean)::int AS requeued
`

type RequeueForResyncParams struct {
	Column1 string  `json:"column_1"`
	Column2 int32   `json:"column_2"`
	Column3 int32   `json:"column_3"`
	Column4 []int16 `json:"column_4"`
	Column5 bool    `json:"column_5"`
}

// Drift-detection sweep for one kind. See requeue_for_resync in
// 00001_schema.sql. Called by the control plane only for kinds whose
// ResyncInterval > 0. $5 (recompose) forces a composer re-run on the
// re-pend — opt-in per kind via the manifest's resync_recomposes setting.
func (q *Queries) RequeueForResync(ctx context.Context, arg RequeueForResyncParams) (int32, error) {
	row := q.db.QueryRow(ctx, requeueForResync,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var requeued int32
	err := row.Scan(&requeued)
	return requeued, err
}

const resolveResourceIDByKindName = `-- name: ResolveResourceIDByKindName :one

SELECT id FROM resource_meta WHERE kind = $1 AND name = $2
`

type ResolveResourceIDByKindNameParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

// Resource queries. Every entity lives in `resources`; root resources
// are rows with owner_id IS NULL, owned resources point at a parent.
//
// State is two orthogonal axes:
//
//	synced_gen vs generation -> the Synced axis (spec reconciled)
//	health_ok                -> the Ready/health axis (observed healthy)
//
// is_ready GENERATED = synced AND healthy AND not deleting. Rich K8s/
// Crossplane-style conditions (Ready/custom, with reason+message+
// lastTransitionTime) live in resource_conditions; the Synced condition
// + happy-path Ready=True are synthesized API-side from the two scalars.
// Resolve the internal resource id (uuid) from the PUBLIC (kind, name)
// identity. This is the single translation the name-keyed API handlers do at
// their top before delegating to the id-based reads below — so the whole SQL
// layer stays internally id-based while nothing but this probe touches an id.
// Served by uniq_resource_meta (UNIQUE btree (kind, name)): a single index seek.
func (q *Queries) ResolveResourceIDByKindName(ctx context.Context, arg ResolveResourceIDByKindNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveResourceIDByKindName, arg.Kind, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveResourceIDKindVersionByKindName = `-- name: ResolveResourceIDKindVersionByKindName :one
SELECT m.id, r.kind_version FROM resource_meta m JOIN resources r ON r.id = m.id
WHERE m.kind = $1 AND m.name = $2
`

type ResolveResourceIDKindVersionByKindNameParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type ResolveResourceIDKindVersionByKindNameRow struct {
	ID          uuid.UUID `json:"id"`
	KindVersion int16     `json:"kind_version"`
}

// Resolve (id, kind_version) from the PUBLIC (kind, name) — the apply path's flip-detect
// probe: if the incoming apply's kind_version differs from the resource's pinned kind_version,
// the apply is a breaking KIND-VERSION FLIP routed to FlipResourceKindVersion instead of
// the ordinary in-place update. One index seek (uniq_resource_meta) + the row's
// kind_version. No row → the resource doesn't exist yet (a plain create at the applied
// kind_version).
func (q *Queries) ResolveResourceIDKindVersionByKindName(ctx context.Context, arg ResolveResourceIDKindVersionByKindNameParams) (ResolveResourceIDKindVersionByKindNameRow, error) {
	row := q.db.QueryRow(ctx, resolveResourceIDKindVersionByKindName, arg.Kind, arg.Name)
	var i ResolveResourceIDKindVersionByKindNameRow
	err := row.Scan(&i.ID, &i.KindVersion)
	return i, err
}

const resolveResourceIDsByKindName = `-- name: ResolveResourceIDsByKindName :many
SELECT m.id, m.kind, m.name
FROM unnest($1::text[]) WITH ORDINALITY AS k(kind, ord)
JOIN unnest($2::text[]) WITH ORDINALITY AS n(name, ord) ON k.ord = n.ord
JOIN resource_meta m ON m.kind = k.kind AND m.name = n.name
`

type ResolveResourceIDsByKindNameParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
}

type ResolveResourceIDsByKindNameRow struct {
	ID   uuid.UUID `json:"id"`
	Kind string    `json:"kind"`
	Name string    `json:"name"`
}

// Batch (kind, name) -> id resolution for the cross-owner scoping params
// (?owner=kind/name repeated). Zipped over two parallel arrays by ordinality,
// matched against uniq_resource_meta. Returns the resolved identity so the
// caller can map a requested ref back to its id (unresolved refs don't appear).
func (q *Queries) ResolveResourceIDsByKindName(ctx context.Context, arg ResolveResourceIDsByKindNameParams) ([]ResolveResourceIDsByKindNameRow, error) {
	rows, err := q.db.Query(ctx, resolveResourceIDsByKindName, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveResourceIDsByKindNameRow
	for rows.Next() {
		var i ResolveResourceIDsByKindNameRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollbackToSpec = `-- name: RollbackToSpec :one
SELECT rollback_to_spec($1, $2, $3)::bigint AS generation
`

type RollbackToSpecParams struct {
	PID        uuid.UUID `json:"p_id"`
	PTargetGen int64     `json:"p_target_gen"`
	PActor     string    `json:"p_actor"`
}

// Check out a historic root revision (by authored generation) as the live
// spec. See rollback_to_spec in 00001_schema.sql. Returns the resource's
// generation after checkout, or -1 if (id, generation) doesn't exist.
func (q *Queries) RollbackToSpec(ctx context.Context, arg RollbackToSpecParams) (int64, error) {
	row := q.db.QueryRow(ctx, rollbackToSpec, arg.PID, arg.PTargetGen, arg.PActor)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const scheduleEligible = `-- name: ScheduleEligible :one
SELECT schedule_eligible($1::uuid[])::int AS scheduled
`

func (q *Queries) ScheduleEligible(ctx context.Context, dollar_1 []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, scheduleEligible, dollar_1)
	var scheduled int32
	err := row.Scan(&scheduled)
	return scheduled, err
}

const unquarantineResource = `-- name: UnquarantineResource :one
SELECT unquarantine_resource($1, $2)::boolean AS released
`

type UnquarantineResourceParams struct {
	PID    uuid.UUID `json:"p_id"`
	PActor string    `json:"p_actor"`
}

// Clears a quarantine and re-arms the resource (schedule_eligible runs on it).
// Returns true if the row existed and was quarantined. See unquarantine_resource.
func (q *Queries) UnquarantineResource(ctx context.Context, arg UnquarantineResourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, unquarantineResource, arg.PID, arg.PActor)
	var released bool
	err := row.Scan(&released)
	return released, err
}
