// Hand-written query templates that sqlc 1.31 can't parse. NOT
// regenerated by `just sqlc` — edit this file directly.
//
// The aggregate / count / leaves queries take a user-supplied list of
// (label_key, label_value) pairs as the WHERE filter chain — one
// equality predicate per pair. The store package assembles the final
// SQL via fmt.Sprintf into the %s slots, plus a dynamically-built
// per-pair AND clause appended to args.
//
// Scoping is by owner_id: the resource whose children are being
// aggregated.

package dbq

// TopologyAggregateSQLTemplate: aggregate buckets at the next level.
//
//	$1 = owner_id
//	$2 = next_key (label key being grouped at this level)
//	$3..$N = path-segment (key, value) pairs and optional cursor
//	final $%d = bucket LIMIT (the page size)
//
// The DISTINCT bucket keys are bounded to the page LIMIT in the `keys` CTE
// BEFORE the per-phase aggregate runs, so a high-cardinality label (an
// attacker seeding thousands of distinct values) can't force a hash aggregate
// over the whole child set — the heavy GROUP BY only ever sees the page's
// worth of buckets. (Previously every bucket was aggregated and the cap was
// applied client-side, materializing the full grouping first.)
//
// Bucket rollup is by the generated `phase` scalar (Ready / Reconciling /
// Degraded / Failed / Deleting / Orphaned / Quarantined) — the same single
// source of truth every other readiness surface uses. The callers consume the
// per-phase counts as the bucket's status breakdown.
const TopologyAggregateSQLTemplate = `
WITH keys AS (
    SELECT DISTINCT COALESCE(m.labels->>$2, '') AS bucket
    FROM resources r JOIN resource_meta m ON m.id = r.id
    WHERE r.owner_id = $1%s%s
    ORDER BY bucket
    LIMIT $%d
)
SELECT
    COALESCE(m.labels->>$2, '') AS bucket,
    r.phase AS readiness,
    count(*)::bigint AS n
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id = $1
  AND COALESCE(m.labels->>$2, '') IN (SELECT bucket FROM keys)
GROUP BY bucket, r.phase
ORDER BY bucket`

// TopologyCountSQLTemplate: number of distinct buckets at the next
// level. Used for X-Total headers in paged topology responses.
const TopologyCountSQLTemplate = `
SELECT count(DISTINCT COALESCE(m.labels->>$2, ''))::bigint
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id = $1%s`

// TopologyLeavesSQLTemplate: drill all the way to leaves at the
// terminal path level. Column order MUST match the Scan in the
// store wrapper.
//
// Slim row shape: leaves render only kind/name/phase in the
// graph view. Spec/status/finalizers/descendants/annotations/shard_id
// are never displayed at the leaf level; the detail panel re-fetches
// via GET /api/resources/{id} when a leaf is clicked.
const TopologyLeavesSQLTemplate = `
SELECT
    r.id, r.kind, m.name, r.owner_id,
    r.generation, r.synced_gen,
    r.is_ready, r.phase,
    r.deletion_requested_at,
    m.labels,
    r.created_at, r.updated_at
FROM resources r JOIN resource_meta m ON m.id = r.id
WHERE r.owner_id = $1%s%s
ORDER BY m.name, r.id
LIMIT $%d`
