// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topology.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const topologyLabelKeys = `-- name: TopologyLabelKeys :many

SELECT DISTINCT k
FROM resources r
JOIN resource_meta m ON m.id = r.id,
     jsonb_object_keys(m.labels) AS k
WHERE r.owner_id = $1
ORDER BY k
LIMIT $2
`

type TopologyLabelKeysParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

// Topology queries for the hierarchy view. Free-form (group-by arbitrary
// label keys with variable WHERE chains) queries live as hand-written
// SQL constants in internal/dbq/topology_manual.go.
// Union of label keys actually present on resources in this owner subtree.
func (q *Queries) TopologyLabelKeys(ctx context.Context, arg TopologyLabelKeysParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, topologyLabelKeys, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var k *string
		if err := rows.Scan(&k); err != nil {
			return nil, err
		}
		items = append(items, k)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
